voxpupuli/beaker

lib/beaker/host_prebuilt_steps.rb

Create ~/.ssh and set perms before creating ~/.ssh/environments.

Fix ssh setup

---

lib/beaker/hypervisor/aws_sdk.rb

- no longer kill all orphan volumes when zombie hunting

(OPS-5099) [aws] -help with disappearing EBS volumes

---

lib/beaker/hypervisor/docker.rb
lib/beaker/hypervisor/vagrant.rb
spec/beaker/hypervisor/docker_spec.rb
spec/beaker/hypervisor/vagrant_spec.rb

This addresses #587 
I've tried to create an issue in JIRA, but I can't seem to find the correct project (I don't appear to have visibility for `QENG`) ; any help would be much appreciated.

(GH-587) SSH agent forwarding for Docker and Vagrant

---

Rakefile

- fix Rakefile to report correct exit code

(QENG-1641) jenkins beaker spec testing reporting green on failure

---

ext/completion/beaker-completion.bash

using this script, one can press tab after any portion (or none)
of a beaker option/command and bash will complete it or offer
suggestions.

(QENG-1628) Add bash completion scripts for beaker

---

lib/beaker/hypervisor/aws_sdk.rb

- ensure when looking for an appropriate security group that you are
looking in a) the provided vpc or b) in the default vpc - do not allow
a mix of vpcs.

(QENG-1662) beaker smoketests failing on ec2 with security group error

---

lib/beaker/command.rb
lib/beaker/dsl/install_utils.rb
lib/beaker/host.rb
lib/beaker/host/pswindows.rb
lib/beaker/host/pswindows/exec.rb
lib/beaker/host/pswindows/file.rb
lib/beaker/host/pswindows/group.rb
lib/beaker/host/pswindows/pkg.rb
lib/beaker/host/pswindows/user.rb
spec/beaker/dsl/install_utils_spec.rb

(gh-433) Adding support to use bitvise ssh server as an alternative ssh provider

---

lib/beaker/hypervisor.rb
lib/beaker/hypervisor/vagrant_parallels.rb
spec/beaker/hypervisor/vagrant_parallels_spec.rb

Added support for the Vagrant Parallels Provider + rspec.
More info at http://parallels.github.io/vagrant-parallels/docs/

Added Vagrant Parallels Hypervisor

---

lib/beaker/answers.rb
lib/beaker/answers/version40.rb
lib/beaker/options/presets.rb
spec/beaker/answers_spec.rb

- add 4.0/3.99 answer generation support

(QENG-1734) PE 4.0.x/shallow-gravy answers file

---

lib/beaker/host.rb
spec/beaker/host_spec.rb

- repair bug and add spec test coverage

(QENG-1834) Regression in Beaker 2.4.0 using do_scp_to

---

lib/beaker/dsl/install_utils.rb
spec/beaker/dsl/install_utils_spec.rb

- busted curl command on windows
- busted msiexec command for installation
- i cry myself to sleep every night

(QENG-1852) install_puppet unable to install windows msi (regression)

---

lib/beaker/dsl/install_utils.rb
spec/beaker/dsl/install_utils_spec.rb

Cleaner than previous PR (https://github.com/puppetlabs/beaker/pull/419)

(gh-474) Adding a utility method for puppet.conf file

---

spec/beaker/dsl/install_utils_spec.rb

- accidental breakage of spec tests
- also removed deprecated rspec method call

(MAINT) fix broken spec tests

---

lib/beaker/host/pswindows.rb

Moved from #666 into it's own PR

(MAINT) Fix indentation

---

lib/beaker/command.rb
lib/beaker/dsl/helpers.rb
lib/beaker/dsl/install_utils.rb
lib/beaker/dsl/wrappers.rb
lib/beaker/host.rb
lib/beaker/host/pswindows.rb
lib/beaker/host/pswindows/file.rb
lib/beaker/host/pswindows/pkg.rb
lib/beaker/host/windows.rb
lib/beaker/host/windows/file.rb
lib/beaker/host_prebuilt_steps.rb
spec/beaker/dsl/helpers_spec.rb
spec/beaker/dsl/install_utils_spec.rb
spec/beaker/dsl/wrappers_spec.rb
spec/beaker/host_spec.rb

- ensure that you can install PE
- deal with setting PATH/RUBY env vars
- update DSL methods to work on windows without bash

(QENG-1735) set up local windows vm without cygwin and get it working

---

CONTRIBUTING.md
README.md

- update contributor and readme doc to point to correct ticket tracker
information

(BKR-81) start using new public beaker jira project

---

lib/beaker/answers/version38.rb
spec/beaker/answers_spec.rb

- was attempting to add answers for a windows host, when we don't pass
answers to windows hosts
- updated spec test to include a windows style host to confirm that this
works

(BKR-156) Error generating answer file for Windows agent install

---

lib/beaker/host_prebuilt_steps.rb

- wrap ssh stop/start in a repeat loop

(BKR-151) periodic failure to restart ssh on windows

---

lib/beaker/dsl/install_utils/puppet_utils.rb
spec/beaker/dsl/install_utils/puppet_utils_spec.rb

Soon AIO builds will only be published to the repo "PC1" (not
products/devel or main as previously). This allows Beaker to install
from both new AIO repos or legacy repos.

(QENG-2096) Update dev repo for new AIO repo name

---

lib/beaker/dsl/install_utils/puppet_utils.rb
spec/beaker/dsl/install_utils/puppet_utils_spec.rb

This fixes the issue raised in PUP-2365

(gh-691) Add function to install certs on windows agents

---

Rakefile

(BKR-188) have beaker support a 'test' raketask.

---

lib/beaker/answers/version32.rb
lib/beaker/options/presets.rb
spec/beaker/answers_spec.rb

(BKR-182) Disable check_for_updates by default with beaker

---

lib/beaker/host_prebuilt_steps.rb

modifications for CentOS-7

---

lib/beaker/hypervisor/openstack.rb

Allows us to have already used an Openstack assigned address, rather than relying on floating IPs

(gh-732) Better Openstack IP address assignment

---

acceptance/tests/base/host.rb
lib/beaker/host.rb
lib/beaker/host/aix/exec.rb
lib/beaker/host/pswindows/exec.rb
lib/beaker/host/unix/exec.rb
lib/beaker/host/windows/exec.rb

- added host.reboot method
- added acceptance test to ensure functionality

(BKR-196) add 'reboot' host method

---

lib/beaker/hypervisor/openstack.rb

This reverts much of the previous behaviour and only falls back to introspecting the existing
data from openstack to assign an address (this is it failing over) - previously we'd have got a response from excon:
/Users/fids/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/excon-0.44.1/lib/excon/middlewares/expects.rb:10:in `response_call': Expected([200, 202]) <=> Actual(404 Not Found) (Fog::Compute::OpenStack::NotFound)
excon.error.response
:body          => "{\"itemNotFound\": {\"message\": \"FloatingIpPoolNotFound: Floating ip pool not found.\", \"code\": 404}}"
:headers       => {
"Content-Length"       => "97"
"Content-Type"         => "application/json; charset=UTF-8"
"Date"                 => "Tue, 28 Apr 2015 08:35:28 GMT"
"X-Compute-Request-Id" => …

(BKR-223) Change order of how we assign IPs to openstack instances

---

lib/beaker/dsl/install_utils/puppet_utils.rb

Prior to this we would use the `step` DSL method in a couple of places
inside Beaker.  This can be problematic when using Beaker as a library
and requires loading more of Beaker than is necessary for executing
certain helper methods.  This commit removes the internal usage of step
and replaces it with calls to the the logger that will output the same
style of notification that calling step does.

(maint) Remove step dsl usage from inside Beaker

---

lib/beaker/dsl/install_utils/pe_utils.rb
lib/beaker/dsl/install_utils/puppet_utils.rb
lib/beaker/dsl/structure.rb
spec/beaker/dsl/install_utils/pe_utils_spec.rb
spec/beaker/dsl/structure_spec.rb

- created install_pe_on, upgrade_pe_on, install_puppet_on that accept a
first argument of a host array and then correctly install pe/puppet on
provided hosts

(BKR-280) ability to install pe/foss on subset of hosts

---

lib/beaker/command.rb
lib/beaker/command_factory.rb
lib/beaker/host/unix/pkg.rb
lib/beaker/platform.rb
lib/beaker/ssh_connection.rb
spec/beaker/command_spec.rb
spec/beaker/host/unix/pkg_spec.rb
spec/beaker/host_prebuilt_steps_spec.rb

- add cisco to supported platforms
- add ability to send a prepend_cmd string to a command object

(BKR-292) Cisco platform changes + prepend command functionality

---

lib/beaker/hypervisor/vmpooler.rb

Fixes typo in the hypervisor/vmpooler.rb

(maint) Fix typo Error -> Errno

---

lib/beaker/dsl/install_utils/foss_defaults.rb
lib/beaker/dsl/install_utils/pe_defaults.rb
lib/beaker/dsl/install_utils/puppet_utils.rb
spec/beaker/dsl/install_utils/puppet_utils_spec.rb

- create configure_defaults_on that provided a type sets the correct
defaults per-host, will also remove any existing defaults

(BKR-317) More usable configure_foss_defaults_on

---

lib/beaker/cli.rb
lib/beaker/test_suite.rb
spec/beaker/cli_spec.rb
spec/beaker/test_suite_spec.rb

- was using the default value instead of the setting value

(BKR-322) --fail-mode fast doesn't seem to be failing fast

---

lib/beaker/dsl/helpers/puppet_helpers.rb
spec/beaker/dsl/helpers/puppet_helpers_spec.rb

Before, with_puppet_running_on bounced the puppet service before and after runs.
This was causing us a lot of pain as the last restart proved unnecessary for the
most part, and added 30 seconds to each test run on avg in our CI.
We've decided to improve this by removing the second bounce, since most tests using
puppet should already use this method, so the next test will ensure its wanted state
prior to yielding.
If people still want the old behavior, they can pass in `:restart_when_done` as a boolean
flag in the `conf_opts` argument of this method

(BKR-53) with_puppet_running_on only restarts before yielding

---

lib/beaker/dsl/install_utils/foss_utils.rb

- support 'latest' as puppet_agent_version in
install_puppet_agent_pe_promoted_on
- default to 'latest' for
install_puppet_agent_pe_promoted_on::puppet_agent_version

(BKR-377) Installing the Latest Puppet Agent Package

---

lib/beaker/dsl/install_utils/pe_utils.rb
lib/beaker/dsl/structure.rb
spec/beaker/dsl/install_utils/pe_utils_spec.rb
spec/beaker/options/pe_version_scaper_spec.rb

- ensure that we only confine to an array of hosts

(BKR-414) install_pe_on assumes hosts will be an array

---

lib/beaker/hypervisor/aws_sdk.rb
spec/beaker/hypervisor/aws_sdk_spec.rb
spec/helpers.rb

Hey puppet people, this is still blocked on BKR-348 and (probably) BKR-318 & BKR-367 that were submitted yesterday.
Putting this up prematurely so you can review when it's convenient.  It's grown to a large enough project I want to make sure I halt early if you hate it.
I'll continue pushing as pieces fall in place but it is currently only missing initial tests for #create_instance, #launch_nodes_on_some_subnet, and #launch_all_nodes

(BKR-349) AwsSdk Hypervisor Specs (for review <3)

---

lib/beaker/dsl/install_utils/foss_utils.rb
lib/beaker/host/unix/pkg.rb
lib/beaker/hypervisor/docker.rb
spec/beaker/host/unix/pkg_spec.rb

This commit adds a case condition for fedora-22 to use the 'dnf'
command where the 'yum' command would previously have been executed.

(BKR-439) Add DNF for fedora-22

---

lib/beaker/shared/host_manager.rb
spec/beaker/shared/host_manager_spec.rb

- make it possible to run commands like:
on 'vmhostname', "command"
on '0.0.0.0', "command"

(BKR-446) add ability to identify a host by vmhostname/ip

---

acceptance/pre_suite/puppet_git/install.rb
acceptance/tests/dsl/install_utils/clone_git_repo_on.rb

Prior to this, running the acceptance tests locally without specifying a specific load path would result in a require failure if attempting to test against puppet installed via git.
/cc @er0ck

(MAINT) Fix acceptance puppet_git load path

---

lib/beaker/hypervisor/vcloud_pooled.rb

Supply vmpooler auth token (if defined in `.fog`) on provision/destroy.

(BKR-486) Supply vmpooler auth token on provision/destroy

---

lib/beaker/dsl/install_utils/foss_utils.rb

This commit adds support for installing AIX 'packages' via the
install repo logic. AIX does not support repository management
and can only install 'RPM' files directly. Since this logic
is contained in the install repo logic in Beaker, we can use
this to install a package that has been mirrored to the standard
repo location.
This assumes that the package is mirrored to the repo location.
In other words, that the following files are the same.
* http://builds.delivery.puppetlabs.net/puppet-agent/1214e51d63b84a82df0c55cab99abc2a3f90a597/artifacts/aix/7.1/PC1/ppc/puppet-agent-1.2.5.49.g1214e51-1.aix7.1.ppc.rpm
* http://builds.delivery.puppetlabs.net/puppet-agent/1214e51d63b84a82df0c55cab99abc2a3f90a597/repos/aix/7.1/PC1/ppc/puppet-agent-1.2.5.49.g1214e51-1.aix7.1.ppc.rpm
It also assumes that …

(BKR-554) Install AIX packages via install repo

---

CONTRIBUTING.md

- update CONTRIBUTING.md to indicate change in policy

(BKR-568) no longer accept PRs marked as "(MAINT)"

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

This allows you to specify a name for your docker container if you so desire. If the container doesn't exist, it gets created as usual. If it does exist, it doesn't get created and will be reused. You'll also be able to refer to your containers using names you specify, rather than using container IDs or randomly generated names.
I usually create a master container, and an agent container to do my testing. Spinning up a master container every single test became unnecessarily time consuming and repetitive. I needed my master container to run only for the first time and remain there, while my agents would get created and destroyed regularly. 
Sample usage:
```YAML
HOSTS:
ubuntu-12-10:
platform: ubuntu-12.10-x64
image: ubuntu:12.10
hypervisor: docker
docker_container_name: ubuntu-container …
```

(BKR-427) Support for Docker Container Names and Container Reuse

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Allow user to override the automatically generated Dockerfile, externalise the generation of Dockerfiles to ERB templates, add an osfamily method to platform.rb

(BKR-539) simplified Dockerfile support

---

lib/beaker/dsl/install_utils/foss_utils.rb

Makes command cross-compatible for PSWindows

(BKR-584) Change to use mkdir_p helper command

---

docs/How-to-Write-a-Beaker-Test-for-a-Module.md

I hit some issues when trying to use beaker for the first time. These changes would have prevented that.
Should fall under the trivial patch exemption from signing the CLA.

(BKR-636) Fix module howto

---

acceptance/fixtures/package/deb/pl-puppetserver-latest-wily.list
acceptance/tests/base/packages_unix.rb
lib/beaker/options/presets.rb
lib/beaker/ssh_connection.rb
spec/beaker/ssh_connection_spec.rb

This PR contains several commits that add support for Ubuntu 15.10 so that it can pass the beaker acceptance tests.

(BRK-481) Add Ubuntu 15.10 Support

---

lib/beaker/dsl/install_utils/puppet_utils.rb

Reverts puppetlabs/beaker#1025

(BKR-660) Revert "Add privatebindir to PATH"

---

lib/beaker/options.rb
lib/beaker/options/parser.rb
lib/beaker/options/validator.rb
spec/beaker/options/parser_spec.rb
spec/beaker/options/validator_spec.rb

This commit separates the options parser from the validation piece. This narrows the focus of Parser and makes the class smaller in code.

(BKR-88) Split Validation Out Of Options Parser

---

lib/beaker/dsl/helpers/host_helpers.rb

(MAINT) made backup_the_file public

---

docs/Docker-Support.md
lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

Wasn't sure whether I was allowed to take over the JIRA ticket, so I left it "Accepted".  Please let me know if I should do otherwise.

(BKR-637) Support mounting volumes with docker

---

acceptance/tests/base/dsl/helpers/host_helpers/check_for_package_test.rb
acceptance/tests/base/dsl/helpers/host_helpers/install_package_test.rb
acceptance/tests/base/dsl/helpers/host_helpers/upgrade_package_test.rb

This reverts commit 9d400ef4e08aa89f6174af7fdef3c6b160fbe620.

Revert "(BKR-358) get ubuntu 15.04 builds green"

---

docs/hosts/cisco.md
docs/hosts/eos.md

Dependent on #1062.
Just docs changes, shouldn't need to wait/worry about Jenkins testing.  Probably should have included that in the git message, but oh well.  I'll try here.
[skip ci]

(MAINT) added cisco platform doc

---

lib/beaker/dsl/install_utils/foss_utils.rb
spec/beaker/dsl/install_utils/foss_utils_spec.rb

Taken the work from #1068, and added some tests to it to match our contributor docs.
Since this is the case, I'll be closing that PR in favor of this one.
@LuvCurves, let me know if I've missed anything or if it looks good from you, & hopefully we'll get this support in soon.

(BKR-669) added cisco-7 install release repo support

---

lib/beaker/host/cisco.rb
spec/beaker/host/cisco_spec.rb

The implementation of `#prepend_commands` for cisco hosts returns `'source /etc/profile;'` and optionally `"sudo ip netns exec #{vrf}"` but does not retain any user-specified prepends. Additionally, it supplies `'sudo'` always when the vrf is specified (regardless of whether the user is root) and never supplies `'sudo'` when the vrf is not specified.
(edit) Additionally, because 'sudo' is inserted in `prepend_commands`, any values from `environment_string` are lost when switching users
Fix 1: preserve user_pc.
Fix 2: prepend 'sudo' depending on whether user is root, independent of whether vrf is present.
(edit) Fix 3: Add `'source /etc/profile/; [sudo]'` in `environment_string` rather than in `prepend_commands`.
```
$ rspec spec/beaker/host/cisco_spec.rb 
Cisco::Host
#prepend_commands
for …
```

(BKR-722) Don't clobber user_pc in prepend_commands for cisco host

---

lib/beaker/dsl/install_utils/foss_utils.rb

The url path structure for osx dmg packages has changed. Also,
the `puppet-agent-latest.dmg` alias is no longer generated when
publishing packages to https://downloads.puppetlabs.com.
This commit updates the url structure to reflect the current
pattern. It also attempts to introspect the 'latest' published
version. If a `puppet_agent_version` has not been specified and
a 'latest' version cannot be found, an exception is raised.

(BKR-759) Update dmg url for puppet-agent install

---

docs/meta/ticket_process.md

(MAINT) fixed BKR.next label in JIRA ticket docs

---

docs/runner/test_suites.md

(MAINT) created test_suites.md

---

acceptance/tests/base/test_suite/export.rb
lib/beaker/dsl/outcomes.rb
lib/beaker/test_case.rb
lib/beaker/test_suite.rb
spec/beaker/test_suite_spec.rb

to properly test this we need a pre-suite for beaker acceptance that runs beaker on the SUT so we can check its output.  will file in another ticket

(BKR-776) test case methods for exporting structured data to junit xml

---

README.md

(MAINT) added maintainers section to README

---

lib/beaker/host/unix/exec.rb
lib/beaker/host/unix/pkg.rb
lib/beaker/host_prebuilt_steps.rb
lib/beaker/hypervisor/docker.rb
spec/beaker/host/unix/pkg_spec.rb
spec/beaker/hypervisor/docker_spec.rb
spec/helpers.rb

* (BKR-799) Use dnf on Fedora from 22 onwards
* (BKR-799) Use systemd for commands from Fedora 14+

(BKR-799) Update Fedora support

---

docs/Beaker-Libraries.md

This PR syncs the internal confluence docs with public Github
documentation.

(BKR-684) Update Beaker-Libraries doc

---

lib/beaker/tasks/rake_task.rb

Check the available rake method for the version of rake, to avoid deprecation errors/warnings.

(BKR-718) Check the available rake method

---

docs/File-a-Beaker-Bug.md

This file is redundant. This information is covered both in the 
- [CONTRIBUTING.md](https://github.com/puppetlabs/beaker/blob/master/CONTRIBUTING.md)
- [README.md](https://github.com/puppetlabs/beaker/blob/master/README.md)

(MAINT) rm File-a-Beaker-Bug doc, redundant

---

docs/hypervisors/README.md

(MAINT) added LXC hypervisor fork link

---

acceptance/tests/base/dsl/helpers/web_helpers/web_helpers_test.rb
acceptance/tests/puppet/web_helpers_test.rb
lib/beaker/dsl/helpers/web_helpers.rb

First pass at acceptance tests for web_helpers, for comment.

(BKR-355) - Adding acceptance tests for web_helper methods.

---

CONTRIBUTING.md

Revert "(BKR-568) no longer accept PRs marked as "(MAINT)""

---

lib/beaker/host/unix/pkg.rb
spec/beaker/host/unix/pkg_spec.rb

(BKR-799) Use DNF for Uninstall on Fedora 22+

---

CONTRIBUTING.md

added in user friendly docs & acceptance testing requirements
[skip ci]

(MAINT) updated contributor guidelines

---

acceptance/tests/base/packages.rb

This reverts commit 480cbad5f8b75c9cb96d104e2537bc8771ed4f8c.

Revert "(BKR-871) Don't test packages on Windows"

---

docs/Lets-Write-a-Test.md

(maint) remove TODO from lets_write_a_test doc

---

lib/beaker/test_suite.rb
spec/beaker/test_suite_spec.rb

(BKR-556) Print line number from test file in stack in summary on fail

(BKR-556) Print line number from test file in stack in summary on fail

---

docs/concepts/shared_options_for_executing_beaker_commands.md

[skip ci]
fix needed from #1195.

(MAINT) fixed broken link to run_in_parallel.md

---

lib/beaker/dsl/helpers/puppet_helpers.rb

Prior to this commit, the `@teardown_procs` value was not being created
to handle the teardown referenced by calling `stub_hosts_on` within
`with_host_stubbed_on`. This commit removes the reference to the method
and adds in the desired code directly.

(BKR-847) Fix with_host_stubbed_on

---

docs/README.md

(MAINT) Fix link to folder from /doc README

---

docs/how_to/archive_sut_files.md
docs/how_to/preserve_hosts.md

[skip ci]
@nwolfe what do you think? @puppetlabs/beaker?

(MAINT) added archiving SUT files doc

---

CONTRIBUTING.md

(MAINT) Modify PR instructions

---

lib/beaker/test_case.rb
spec/beaker/test_case_spec.rb

merge https://github.com/puppetlabs/beaker/pull/1187 first and I'll re-base to fix this.

(BKR-570) Errors in teardown do not obscure errors in test

---

docs/concepts/style_guide.md

(BKR-80) created style guide for beaker tests

---

MAINTAINERS.md

(MAINT) clarify reviewer vs maintainer roles

---

lib/beaker/hypervisor/docker.rb
spec/beaker/hypervisor/docker_spec.rb

See below relevant links:
* https://github.com/test-kitchen/kitchen-docker/pull/192
* https://github.com/test-kitchen/kitchen-docker/pull/216
* https://developerblog.redhat.com/2014/05/05/running-systemd-within-docker-container/

(BKR-528) Set ENV container docker

---

docs/how_to/upgrade_from_2_to_3.md
lib/beaker/options/presets.rb
spec/beaker/dsl/helpers/web_helpers_spec.rb

Reverts puppetlabs/beaker#1235

Revert "Revert "(BKR-712) changed default to not cache files locally""

---

lib/beaker/dsl/install_utils/windows_utils.rb
spec/beaker/dsl/install_utils/windows_utils_spec.rb

Prior to this commit, beaker always assumed a specific registry key for the
remembered properties when validating them for an MSI on install. However, on
32 bit installs, the registry key we right to is different. This commit updates
the validation to search for the correct, different, key based on host
architecture.
Signed-off-by: Moses Mendoza <moses@puppet.com>

(PA-514) correct key to remembered props on i386 win

---

docs/how_to/upgrade_from_2_to_3.md

(BKR-914) add fix info to upgrade doc

---

docs/how_to/test_arbitrary_beaker_versions.md
docs/how_to/upgrade_from_2_to_3.md

(maint) add doc for BEAKER_VERSION env vars

---

docs/how_to/upgrade_from_2_to_3.md

(maint) Update beaker-pe inclusion explanation

---

bin/beaker
lib/beaker/cli.rb
lib/beaker/options/options_hash.rb
lib/beaker/shared.rb
lib/beaker/shared/subcommands_util.rb
spec/beaker/shared/subcommands_util_spec.rb

Currently writing spec tests for this change, but wanted to get a discussion going on how things are headed

(BKR-956) implemented a beaker init subcommand

---

lib/beaker/dsl/install_utils/foss_utils.rb

(MAINT) fix method doc note

---

docs/concepts/beaker_libraries.md

(maint) Add reference to beaker-http

---

lib/beaker/dsl/helpers/puppet_helpers.rb
spec/beaker/dsl/helpers/puppet_helpers_spec.rb

This commit modifies the bounce_service helper method to try to restart
the service via a `reload` action, falling back to a `stop` and `start`
only on failure.  This change enables beaker to take advantage of
performance improvements which are possible with `reload` when the
service supports it.

(BKR-703) Utilize service reload in bounce_service helper method

---

lib/beaker/host/pswindows/exec.rb
lib/beaker/host/windows/exec.rb

- The current method of detecting a Windows host IP relies on parsing
very specific output from the `ipconfig` command using either
`grep` in Cygwin, or `find` in cmd / PowerShell.  This method
relies on finding the strings `IP Address`, `IPv4 Address` or
`IPv6 Address` in the output.
On internationalized versions of Windows, the word `Address` is
typically localized, as is the case with Japanese Windows. Further,
calling `grep` against such output, must have `LC_ALL=C` passed as
well, otherwise text won't be matched.
- Furthermore, the current method of using `ipconfig` has other
problems because it may return adapters that are not currently
IPEnabled, which could lead to retrieval of the an IP address
associated with a Pseudo-Interface.  By specifying IPEnabled=True
the list of …

(BKR-1012) Fix Host#ip on Non-English Windows

---

docs/how_to/hosts/archlinux.md
lib/beaker/dsl/install_utils/foss_defaults.rb
lib/beaker/dsl/install_utils/foss_utils.rb
lib/beaker/host/unix/exec.rb
lib/beaker/host/unix/pkg.rb
lib/beaker/host_prebuilt_steps.rb
lib/beaker/platform.rb
spec/beaker/dsl/install_utils/foss_utils_spec.rb
spec/beaker/host/unix/pkg_spec.rb

* Rebased from the original work by @jantman
* Allows testing of archlinux platform with Beaker

(BKR-524) Add support for the archlinux platform

---

lib/beaker/hypervisor/aws_sdk.rb
spec/beaker/hypervisor/aws_sdk_spec.rb

This patch immediately checks a keypair was created so we can detect early
any key creation failures or slowness for further debugging later.
This was created to debug issues we're having in PDB around failed key deletion. Basically, a keypair gets created for the first node, removal is meant to occur normally afterwards for the next creation - however there is a race in that they key shows up as not existing (even though its happy to use it for node creation - yeah, AWS can be weird). So we get an exception and the entire run fails.
https://jenkins-enterprise.delivery.puppetlabs.net/job/enterprise_puppetdb_integration-system-puppetdb_full-master/1398/INSTALL_TYPE=upgrade_latest,LAYOUT=ec2-west-el6-64mda-el6-64a,NIGHTLY=true,PUPPETDB_DATABASE=postgres,label=beaker-ec2/console
Or: …

(PDB-3193) Ensure key pair exists after creation

---

docs/concepts/testing_beaker_itself.md

(maint) Add beaker pipeline testing description

---

lib/beaker/hypervisor/openstack.rb

There is some sort of race condition that occurs when trying to
generate RSA keys during testing with ruby 2.2.5 and OpenSSL. This
change adds a retry to the key process generation.

(BKR-1054) Retry when RSA keygen fails

---

docs/how_to/hypervisors/README.md
docs/how_to/hypervisors/vmpooler.md
docs/how_to/hypervisors/vsphere.md

(MAINT) centralize fog docs

---

beaker.gemspec

(MAINT) update puppet company refs

---

acceptance/tests/subcommands/init.rb
lib/beaker/subcommand.rb
lib/beaker/subcommands/subcommand_util.rb
spec/beaker/subcommand/subcommand_util_spec.rb

(BKR-1059) beaker subcommands should return non-zero exit codes

---

docs/how_to/archive_sut_files.md

(MAINT) add conditional archive recommendation

---

docs/tutorials/subcommands.md

(maint) Update subcommand docs

---

docs/tutorials/subcommands.md
docs/tutorials/test_run.md

(maint) Revamp beaker test run documentation

---

docs/tutorials/lets_write_a_test.md

Updated docs to use HTTPD package.

(BKR-840) Fix docs to use more trivial package

---

lib/beaker/host/pswindows/exec.rb
spec/beaker/host/pswindows/exec_spec.rb

* This fix quotes the fact to avoid extra spaces

BKR-1089 Fix Custom Facts added to environment on windows hosts

---

lib/beaker/host/unix/pkg.rb
spec/beaker/host/unix/pkg_spec.rb

(BKR-1118) refactor PE puppet-agent install

---

docs/concepts/beaker_libraries.md

(MAINT) add beaker-puppet to libraries doc

---

docs/how_to/hypervisors/aws.md

(BKR-1148) Update docs to specify platform for amazon linux

---

lib/beaker/host/pswindows/exec.rb
spec/beaker/host/pswindows/exec_spec.rb

* Previous PR caused quoting issue which made this not work properly
on Windows with arrays.
Fixed the quoting in order to rectify this issue and updated tests.

BKR-1089: Cleanup array quoting

---

beaker.gemspec
docs/how_to/hypervisors/README.md

(BKR-1181) Add beaker-vcloud dependency

---

docs/how_to/hypervisors/README.md

(MAINT) add beaker-abs to hypervisors doc

---

docs/tutorials/creating_a_test_environment.md

Update links to right hypervisor libraries. consolidating at one place so we
don't need to keep changing links at multiple places every time
One last PR!
[skip ci]

(MAINT) Update creating a test env doc

---

CHANGELOG.md
acceptance/lib/beaker/acceptance/install_utils.rb
lib/beaker/host/unix/exec.rb
lib/beaker/host/unix/pkg.rb
lib/beaker/host_prebuilt_steps.rb
lib/beaker/perf.rb
lib/beaker/platform.rb
spec/beaker/host_prebuilt_steps_spec.rb
spec/helpers.rb

(QENG-5106) Revert "Update Beaker to support amazon as a platform"

---

CHANGELOG.md

(MAINT) Add changelog entry for BKR-1263

---

CHANGELOG.md

(MAINT) update changelog for 3.30.0 release

---

lib/beaker/dsl/helpers/host_helpers.rb
lib/beaker/host/unix/pkg.rb

(MAINT) deprecate deploy_package_repo methods

---

beaker.gemspec
lib/beaker/dsl/patterns.rb

takes the work from #1483 & adds a fix to 
doc generation so that it can pass through
doc generation & spec testing.

(MAINT) update yard dependency

---

CHANGELOG.md

(MAINT) add changelog for 3.34 release

---

CHANGELOG.md
lib/beaker/tasks/quick_start.rb

fixes [BKR-1458](https://tickets.puppetlabs.com/browse/BKR-1458)

(BKR-1458) Report accurate location of generated smoke test

---

CHANGELOG.md

(MAINT) fix changelog for release

---

.gitignore

Reorganizes the .gitignore and adds comments where appropriate.
Split from #1513

(BKR-1472) Document the .gitignore

---

CHANGELOG.md
CONTRIBUTING.md
DOCUMENTING.md
docs/tutorials/installation.md

Enhances directions for project contributors, including detailed installation instructions and process guidelines as well as Markdown formatting conventions.
Split from #1513
[skip ci]

(BKR-1472) Enhancements to Contributor Guidance

---

CHANGELOG.md

(MAINT) add changelog updates for 3.36.0

---

CONTRIBUTING.md

Also includes a rebase workflow.

(BKR-816) Expand contribution guidelines with PR requirements

---

CHANGELOG.md

(MAINT) release 3.37.0

---

lib/beaker/dsl/roles.rb

This commit fixes a few bugs that surfaced as a part of the effort to
get git-based acceptance tests working

(PUP-8305) Enable git-based acceptance testing

---

CHANGELOG.md

Fixes changelog entry for BKR-463 and adds an entry for BKR-1499
[skip ci]

(MAINT) Changelog fixes

---

docs/how_to/the_beaker_dsl.md

(BKR-1505) update beaker DSL listing doc

---

lib/beaker/dsl/roles.rb

This reverts commit 731661b5427dd74a2348bc77e39a15b9cd362f51.

Revert "(PUP-8305) Enable git-based acceptance testing"

---

CHANGELOG.md
lib/beaker/host.rb
spec/beaker/host_spec.rb

See https://tickets.puppetlabs.com/browse/BKR-1432

(BKR-1432) Test if puppet module is directly in source host root

---

CHANGELOG.md

(MAINT) add changelog for 4.1.0 release

---

CHANGELOG.md

(MAINT) update changelog for 4.2.0 release

---

lib/beaker/options/command_line_parser.rb
lib/beaker/options/presets.rb
lib/beaker/subcommand.rb
lib/beaker/test_suite.rb
lib/beaker/test_suite_result.rb

Persist errors and fails to file of choice.

(BKR-1523) Add only-fails capability to beaker.

---

CHANGELOG.md

Fix beaker ticket number for nexus device fix, change BKR-1526 to BK-1562.

Fix ticket number in changelog

---

CHANGELOG.md

(MAINT) update beaker 4.5.0 changelog

---

CHANGELOG.md

Update CHANGELOG.md for 4.6.0 release

---

CHANGELOG.md

(MAINT) update beaker 4.7.0 changelog

---

CHANGELOG.md

Update CHANGELOG.md for 4.8.0 release

---

CHANGELOG.md

(MAINT) add changelog for 4.10.0 release

---

CHANGELOG.md

(MAINT) add changelog for 4.11.0 release

---

lib/beaker/platform.rb

This adds the redhatfips platform to the recognized platform list.

(PE-27037) Add redhatfips as recognized platform

---

CHANGELOG.md

(MAINT) add changelog for 4.12.0 release

---

CHANGELOG.md

(MAINT) update changelog for 4.13.0 release

---

CHANGELOG.md

(MAINT) add changelog for 4.13.1 release

---

spec/beaker/host/unix/exec_spec.rb

Also refactors stubbing overall for reboot tests
[skip ci]

fix spec sleep execution by stubbing repeat_for_and_wait

---

CHANGELOG.md

(MAINT) add changelog for 4.14.0 release

---

CHANGELOG.md

(MAINT) add changelog for 4.14.1 release

---

lib/beaker/host/mac/exec.rb

...and be more permissive regarding OS X versions in exec.rb

(BKR-1621) Add support for macOS Catalina

---

CHANGELOG.md

(maint) Add changelog for 4.15.0 release

---

beaker.gemspec
lib/beaker/host.rb
lib/beaker/host/unix/exec.rb
lib/beaker/ssh_connection.rb
spec/beaker/host/unix/exec_spec.rb
spec/beaker/host_spec.rb

These are the same changes as in #1609, but rebased on the master branch after https://github.com/highb/beaker/pull/1 was merged.
Created this as a separate PR because I was a little worried about rebasing, so I want to be able to go back if this doesn't work out, but the latest failures seen in #1609 are a known failure that was fixed in #1615, so rebasing should fix the issue.

(QENG-7422) host.reboot mob rebased

---

CHANGELOG.md

(MAINT) add changelog for 4.16.0 release

---

CODEOWNERS

(MAINT) add DIO to code owners

---

CHANGELOG.md

(maint) Add changelog for 4.17.0 release

---

CHANGELOG.md

(maint) Add changelog for 4.18.0 release

---

CHANGELOG.md

(maint) add changelog for 4.21.0 release

---

CHANGELOG.md

(maint) Added changelod for 4.22.0 release

---

lib/beaker/host/unix/exec.rb
spec/beaker/host/unix/exec_spec.rb

* Replace the check for 'uptime' to compare the actual boot times of the
system between what should have been a reboot.
* Use a single command to reboot the system falling back from systemd to
reboot to shutdown -r which should cover all of the usual suspects
* The previous 'shutdown -r' would not always actually trigger a
reboot on systemd-enabled systems
BKR-1653 #close

[BKR-1653] Fix reboot time check

---

lib/beaker/host/pswindows/exec.rb
lib/beaker/host/unix/exec.rb
spec/beaker/host/pswindows/exec_spec.rb
spec/beaker/host/unix/exec_spec.rb

Implementation for which command that works on unix and windows(powershell)

(BKR-1646) Which command for unix and windows

---

acceptance/tests/base/dsl/helpers/host_helpers/deploy_package_repo_test.rb
acceptance/tests/base/host/packages.rb
docs/tutorials/creating_a_test_environment.md
lib/beaker/host/unix/exec.rb
lib/beaker/host/unix/file.rb
lib/beaker/host/unix/pkg.rb
lib/beaker/host_prebuilt_steps.rb
lib/beaker/perf.rb
lib/beaker/platform.rb
spec/beaker/host/unix/file_spec.rb
spec/beaker/host/unix/pkg_spec.rb
spec/beaker/host/unix_spec.rb
spec/beaker/host_prebuilt_steps_spec.rb
spec/beaker/perf_spec.rb

Add initial opensuse support

---

.github/workflows/release.yml
.github/workflows/test.yml
Gemfile
README.md
Rakefile

this setup is now identical to our setup in https://github.com/voxpupuli/puppet-lint_modulesync_configs

Align release setup with other gems

---

lib/beaker/host/pswindows/pkg.rb
lib/beaker/host/windows/pkg.rb

While refactoring this bug crept in.
Fixes: dc0a2fb676d6caac6da3722106c4ee91434f169a

Correct Windows 64 check

---

CHANGELOG.md
lib/beaker/version.rb

This changelog was crafted by hand, due to https://github.com/github-changelog-generator/github-changelog-generator/issues/971 I used https://github.com/voxpupuli/beaker/compare/4.39.0...master to figure out the merged pull requests. A few of them only touched the CI config or the tests, so I didn't include them.

Release 5.0.0

---

lib/beaker/host/unix/exec.rb

Use systemctl to restart SSH on EL9

---

CHANGELOG.md
lib/beaker/version.rb

Changelog was crafted by hand :cry:

Release 4.40.2

---

CHANGELOG.md
lib/beaker/version.rb

Changelog was crafted by hand :cry:

Release 5.3.1

---

CHANGELOG.md
lib/beaker/version.rb

Releasing activity for Beaker 4.42.0

Releasing activity for Beaker 4.42.0

---

acceptance/tests/base/host_prebuilt_steps/ssh_environment_test.rb
lib/beaker/host/unix.rb
lib/beaker/host_prebuilt_steps.rb
lib/beaker/platform.rb
spec/beaker/host_prebuilt_steps_spec.rb

Since some time Puppet doesn't support F5 appliances anymore.

Drop EoL F5 support

---

Gemfile
lib/beaker/host/unix/exec.rb
spec/helpers.rb

(#1928) Prevented regex meant for EOL OS flavors matching el-10
