voxpupuli/beaker

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
The original fix: f2c1b1efd4d36575032294d504b15c56e3cda4e7 was appending
carriage returns instead of prefixing them. This patch corrects the order,
so QENG-1594 can be closed again.
Signed-off-by: Ken Barber <ken@bob.sh>
=> (QENG-1594) Prefix carriage returns during sshd_config append

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
In QENG-299, a hack was required to get around an issue w/EOS
for root ssh key setup.  A change was submitted to the
sshkeys repo to fix this.  This fix removes the hack, and
sets up the correct root ssh key procedure in Beaker for EOS
Conflicts:
spec/beaker/host_prebuilt_steps_spec.rb
=> (QENG-1538) fixes EOS hack

lib/beaker/host.rb, spec/beaker/host_spec.rb
Because of the functionality within do_scp_to which allows certain files and directories to be ignored when copying, each specific file/directory is copied individually. In the existing code the source and target paths are effectively the same, causing directories to be copied as subdirectories of themselves. This PR ensures that all files and directories are copied to their parent directories.
This PR also includes some additional expectations for the spec tests for do_scp_to. Some tests which are supposed to test whether files and directories are excluded from copies were only testing that non-excluded files *were* copied, and didn't test that excluded files *weren't* copied. The relevant commit explicitly tests that excluded files are not copied. Although not directly related to the …
=> (gh-503) (QENG-1485) Fix recursive copying in do_scp_to

lib/beaker/hypervisor/vagrant.rb
In some cases an underlying issue causes the vagrant hypervisor to fail but gives no usable output.
By adding the stderr output to the raise gives the user more info on why it failed.
=> Add stderr output to stacktrace

lib/beaker/dsl/helpers.rb
When upgrading, the agent service is already stopped. On Centos4, this
causes a failure from the init script. We want to ignore that failure.
=> (QENG-1684) Allow exit code of '1' when stopping puppet agent on centos4

lib/beaker/hypervisor/aws_sdk.rb
For LEIG testing with a busy PuppetDB host, the default AMI volume size is inadequate.
=> (QENG-1676) Enable root volume size changes with volume_size in the config file

lib/beaker/dsl/install_utils.rb, lib/beaker/host_prebuilt_steps.rb, lib/beaker/hypervisor/vagrant.rb, lib/beaker/hypervisor/vagrant_virtualbox.rb
* Fixes for root key location copy
* Adds a Vagrant VB OSX option
* Fixes PermitRootLogin regex
* Adds option to enable GUI
* Raises error if version not given for DMG
Now works with an example OSX Virtualbox image :+1:
=> (QENG-1695) Improves OSX Support

lib/beaker/dsl/install_utils.rb, spec/beaker/dsl/install_utils_spec.rb
I had misunderstood the install_puppetlabs_dev_repo method before, thinking that it would install packages
from within the dev repo, but it's actually just installing the dev repo itself.  These changes add a
corresponding installation method to install the packages found in these repos after they've been installed
=> (QENG-1690) added in helper installation method for packages

lib/beaker/host.rb, spec/beaker/host_spec.rb
The issue here is that when you either have a machine with the roles master and agent, or agent, the AIO paths were set correctly when the Beaker run was given the `:type` parameter with the value 'aio'.
The issue is that if you have a machine that doesn't have the agent role at all, it is still getting the 'aio' paths.  In the simple case of having two separate master and agent machines, the master machine currently has an incorrect path.  This fix queries the roles, and if the system doesn't have the 'agent' role, it will come back as FOSS, which is the default for this setup.
=> (QENG-1714) fixed get_type for a machine with only non-agent roles

lib/beaker/dsl/helpers.rb, spec/beaker/dsl/helpers_spec.rb
This helper function allows for writing the hiera.yaml file
It currently makes the assumption only the yaml backend is used.
=> Add helper function to write hiera.yaml file

lib/beaker/host/unix.rb
This commit updates the default aio puppetpath to /etc/puppetlabs/agent
=> (gh-660) Update default aio puppetpath path for unix

lib/beaker/dsl/structure.rb, spec/beaker/dsl/structure_spec.rb
- add expect_failure method
- add expect_failure spec tests
=> (QENG-1629) Add expect_failure() to Beaker DSL (the code is provided)

lib/beaker/hypervisor/vagrant.rb
Missed new line:
```
/Users/petersouter/projects/puppet-chocolatey/.vagrant/beaker_vagrant_files/default.yml/Vagrantfile:9: syntax error, unexpected tIDENTIFIER, expecting keyword_end
v.vm.guest = :windows    v.vm.provider :virtualbox do |vb|
```
=> (MAINT) Fix Vagrantfile syntax error

lib/beaker/hypervisor/docker.rb, spec/beaker/hypervisor/docker_spec.rb
Right now when docker not found, you get:
```
Hypervisor for debian-7 is docker
Beaker::Hypervisor, found some docker boxes to create
/opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/excon-0.43.0/lib/excon/unix_socket.rb:14:in `connect_nonblock': No such file or directory - connect(2) (Errno::ENOENT) (Excon::Errors::SocketError)
from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/excon-0.43.0/lib/excon/unix_socket.rb:14:in `connect'
from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/excon-0.43.0/lib/excon/socket.rb:28:in `initialize'
```
This improves the message and gives a little guidance
=> (MAINT) Improve error message when docker not found

lib/beaker/dsl/ezbake_utils.rb, spec/beaker/dsl/ezbake_utils_spec.rb
This involves a rework of the ezbake_utils to provide more capability to fully
install PuppetDB using these helpers.
* Some of the original API has been simplified, and the YAGNI parts removed
since no one was using them today.
* We now do the lein install process, but using a local maven repository to
avoid collision with other projects running on the same host.
* install_termini_from_ezbake now added to install that component
* I've switched to using the install.sh methodology on ezbake.
* This now is compatible with lein-ezbake.
* ezbake_local_cmd has been added to generalize this kind of system invocation
and simplify testing.
* ezbake_installsh generalizes the way we invoke install.sh, and simplifies testing.
* install_ezbake_tarball_on_host has been created to generalize this step …
=> (PDB-1034) Ezbake changes to get PDB source based builds working

lib/beaker/host/unix.rb
Reverts puppetlabs/beaker#667
This is because the Puppet user was being confused for the Beaker user.  
This means that people were using `host['user']` and `host['group']` for puppet stuff incorrectly.
=> Revert "(QENG-1784) updated FOSS group to be root instead of puppet"

lib/beaker/host/windows.rb
Previously, beaker would add `puppetbindir` to the `~/.ssh/environment`,
which on Windows, excluded the ruby that the MSI installs. As a result,
puppet setup steps that rely on `gem`, e.g. when adding sources, would
fail.
This commit adds the ruby in the MSI to the `~/.ssh/environment` simply by
it being included in `puppetbindir`. Note the actual location depends on
whether we are installing x86 puppet on x64 windows, or not, so we
include both possibilities like we do for puppet's main bin directory.
=> (maint) Add ruby to windows PATH

lib/beaker/dsl/install_utils.rb
If the 'bundle' directory is present, ignore it during setup/scp. Often has self-referential symlinks which do NOT play will with the scp which does a dereference of all symlinks. This results in infinite copy during setup. There's a similar PR which was merged in Sept for the '.bundle' directory but I've never seen bundler create a dir by that name so that ignore may be unnecessary.
=> (MAINT) also ignore the 'bundle' directory

lib/beaker/host.rb, spec/beaker/host_spec.rb
Originally, I had assumed that machines with the master role would keep their old paths, or be updated
with a completely new set.  It looks like the master pathing will actually be based upon the agent though,
since masters will be installed on top of agents now
=> (QENG-1809) removed master path resets for AIO test setups

lib/beaker/host/unix.rb
Previously, when executing AIO acceptance tests, the beaker method
`with_puppet_running_on` would attempt to start and stop the
`puppetmaster` service. This is because the AIO defaults for
`puppetservice` and related conf.d were not specified, and would
fallback to the FOSS defaults.
This commit updates the AIO defaults to match the `puppetserver`
service, and related conf.d.
=> (QENG-1813) Use puppet-server service names

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
Beaker sets the PATH and RUBYLIB environment variables in
~/.ssh/environment, but it was previously difficult to tell what the end
result was.
This commit cats the ~/.ssh/environment file so we know what the PATH
and RUBYLIB environment variables are for the current SSH session.
=> (QENG-1812) Print beaker ssh environment

lib/beaker/hypervisor/vcloud_pooled.rb, spec/mocks.rb
This PR facilitates use of vmpooler's batch-request POST API
(https://github.com/puppetlabs/vmpooler#post-vm) within beaker.
=> (QENG-780) request sets of VMs instead of one VM at a time

lib/beaker/host.rb
This commit adds `Errno::ETIMEDOUT` to the rescue logic of the
port_open? method in lib/beaker/host.rb.
Adding this this rescue prevents the ETIMEDOUT error from short circuiting of
the logical intention of the port_open? method.
=> (QENG-1867) Add ETIMEDOUT rescue to host.rb

lib/beaker/hypervisor/docker.rb
Addresses #700 - This allows `docker_options` to be set in the nodeset YAML, allowing the timeouts to be easily extended.
=> GH-700 - Allow Docker::options to be set from config hash

lib/beaker/hypervisor/vagrant.rb
Rolling back the change made in bf353c1 as it is no longer required.
The subsequent change in 3aa080c for vagrant 1.7 properly fixed the issue
and so the work around can now be removed.
=> (MAINT) Rolling back change for windows in the vagrant hypervisor

lib/beaker/dsl/wrappers.rb, spec/beaker/dsl/install_utils_spec.rb, spec/beaker/dsl/wrappers_spec.rb
=> (gh-688) Fixing the powershell wrapper to use an array of arguments

beaker.gemspec, lib/beaker/dsl/helpers.rb, lib/beaker/dsl/install_utils.rb, lib/beaker/host.rb, spec/beaker/dsl/helpers_spec.rb, spec/beaker/host_spec.rb
During my testing from Belfast, using vcloud+beaker is very, very slow over the built-in SCP. It is common for an acceptance test to take 5 or 10 minutes to start due to the module upload. Rsync reduced this to literally a few seconds!
As such, I have created some code to add rsync support for beaker. It requires the 'rsync' gem which is a wrapper for the system binary (thus, you need rsync already on your system). To use it, you simply use the following in your spec helpers:
```
copy_module_to(host, :source => proj_root, :module_name => 'firewall', :protocol => 'rsync')
```
or
```
rsync_to host, proj_root, "#{host['distmoduledir']}/netscaler", {:ignore => [".bundle", ".git", ".vagrant"]}
```
or
```
create_remote_file(master, File.join(path, "site.pp"), pp, :protocol => 'rsync')
```
It's …
=> Added support for rsync

lib/beaker/hypervisor.rb, lib/beaker/hypervisor/docker.rb, lib/beaker/options/presets.rb
Do not restart the sshd service when using Docker as it causes the container to stop.
Fix #611
=> [docker] No need to restart sshd

lib/beaker/hypervisor.rb, lib/beaker/hypervisor/vmpooler.rb, spec/beaker/hypervisor/hypervisor_spec.rb, spec/beaker/hypervisor/vmpooler_spec.rb
This PR renames the 'VcloudPooled' hypervisor to 'Vmpooler', and
includes a few fixups as ride-alongs:
- resourcepool, folder, datastore not needed for Vmpooler
- small syntax/wording changes
=> (maint) VcloudPooled -> Vmpooler

lib/beaker/host/windows/file.rb
- In 9c32cac7a7a5bf52f21b628b14ddba9bfc44510c a change was
introduced to add a new Windows::File.file_exist? method
that relied on using test -e.  The code assumes that the
path does not contain spaces and does not need to be
quoted.
Unfortunately, this assumption is incorrect and causes
pre-suites to fail because this test is performed on
Puppets :vardir.  On Windows, Puppets :vardir is always
rooted at %ALLUSERSPROFILE%\PuppetLabs
When running on Windows 2008 or higher, the
%ALLUSERSPROFILE% directory is C:\ProgramData\
However, on Windows 2003, the path structure is different
and that directory is located at
C:\Documents and Settings\All Users\Application Data
With an unquoted path passed to test -e a failure is
generated, which breaks Windows pre-suites on 2003.
=> (QENG-1955) Windows::File.file_exist? fails on 2003

lib/beaker/answers/version20.rb, lib/beaker/answers/version28.rb, lib/beaker/answers/version30.rb
Before this commit Beaker would attempt to merge custom answers on
platforms where answers are not used. This commit guards against merging
custom answers unless there are already answers specified.
=> (QENG-1970) Guard against merging custom answers on Windows

lib/beaker/host.rb, spec/beaker/host_spec.rb
Introduced in f551c0ad124bb8ab782f7dd90ab30ae9cc49fafa
This actually breaks Beaker, because the host variable is nil:
```
/opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/beaker-136d9c3cccbc/lib/beaker/host.rb:305:in `mkdir_p': undefined local variable or method `host' for #<FreeBSD::Host:0x007f8abe0e20b8> (NameError)
from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/beaker-136d9c3cccbc/lib/beaker/host.rb:364:in `block in do_scp_to'
from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/beaker-136d9c3cccbc/lib/beaker/host.rb:361:in `each'
from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/beaker-136d9c3cccbc/lib/beaker/host.rb:361:in `do_scp_to'
from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/beaker-136d9c3cccbc/lib/beaker/dsl/helpers.rb:207:in `block in scp_to'
```
=> (MAINT) Fix mkdir bug on PSWindows and fix test

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
- use correct path separator for cygwin vs. correct separator for
non-cygwin windows
- remove un-used RUBYLIB env var
* no dependencies on this anywhere, might as well pull it out
=> (BKR-7) beaker's prebuild_steps corrupts PATH on windows+cygwin

Gemfile
- add ability to set GEM_SOURCE to internal rubygems mirror
=> (BKR-60) failures caused by rubygems timeouts

lib/beaker/answers/version38.rb, lib/beaker/answers/version40.rb
This commit adds a 38-specific answer file to beaker, which introduces an
answer for whether to stop the upgrade and proceed to do the NC database
migration. It defaults to 'n' to enable upgrades to continue.
Signed-off-by: Moses Mendoza <moses@puppetlabs.com>
=> (PE-8260) add answer for new NC migrate question

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
Hashicorp added new behavior that generates a new SSH key
when generating a box, and will remove any existing "insecure"
key found on a box. See https://github.com/mitchellh/vagrant/pull/4707
This has the unfortunate side effect of breaking the automation
used in Beaker to setup SSH keys, since it relied on the default
"insecure" vagrant keys being used. This workaround disables
the new Vagrant behavior with the `ssh.insert_key = false` config option.
=> (BKR-148) Stop vagrant from generating ssh key

lib/beaker/hypervisor/docker.rb, spec/beaker/hypervisor/docker_spec.rb
As @richardc pointed out, the commit 25909d02608f9ec6fb69be972750d39ed08f2c41 actually removes being able to see the error raised.
This fixes that, so you can actually see what the issue is.
=> (MAINT) Show error from docker

lib/beaker/dsl/install_utils/module_utils.rb, spec/beaker/dsl/install_utils/module_utils_spec.rb
This allows copying the module over to non-cygwin Windows boxes
=> (MAINT) Fix copy module to on non-cygwin

lib/beaker/dsl/install_utils/ezbake_utils.rb
This previously used 'echo -n', which is not a universally available
feature of echo. When running with an OS X host, this caused the string
to look like "-n PACKAGE-1.2.3\n", which caused cascading failures in
the code that uses this data. printf is a more portable replacement.
=> Fix ezbake version string extraction

lib/beaker/hypervisor/vmpooler.rb, lib/beaker/options/presets.rb
- Use JOB_NAME for 'project' tag default if it exists
- Set 'beaker_version' tag in vmpooler hypervisor
=> (BKR-161) Beaker tagging improvements

lib/beaker/host_prebuilt_steps.rb, lib/beaker/hypervisor/docker.rb, spec/beaker/hypervisor/docker_spec.rb
This replaces #742 - with a new branch tied to an issue in JIRA
This PR adds support for adding hosts to `/etc/hosts` on all docker instances in the nodeset; using the hack_etc_hosts method without this change results in a hosts file which contains `0.0.0.0` for all entries, since the `host['ip']` for the docker instance is set to `0.0.0.0` and the ssh port which has been exposed for the particular container. Instead, we set a new key, `host['vm_ip']` in the provision method, and set the entry in the host file to this if it's present.
=> (BKR-165) hack_etc_hosts method doesn't work for Docker provider

lib/beaker/host.rb, lib/beaker/host/freebsd.rb, lib/beaker/platform.rb
Breaking up #615 into easier to merge chunks :+1: 
* Main change is location of Puppet data under `/usr/local/etc` rather than `/etc/`
=> (BKR-113) Add FreeBSD host class

.simplecov, spec/spec_helper.rb
- accidentally busted when we dropped ruby 1.8 support
- updated to look nice with the current beaker directory structure
- updated env var to meet beaker standards
=> (BKR-183) simplecov busted in beaker

lib/beaker/network_manager.rb, lib/beaker/options/presets.rb, spec/beaker/network_manager_spec.rb
- the hosts file was being defaulted to to provide a log name prefix -
it needs a default value for when there is no user provided value plus
no hosts file
=> (BKR-192) can't run beaker without a host file specified

lib/beaker/hypervisor/openstack.rb
This PR enables root access on each node in turn, after it is provisioned.  Previously,
the code did all nodes on the first pass, before some were even a twinkle in Openstack's
eye.
=> (gh-687) [openstack] multi node root user enable

lib/beaker/hypervisor/vagrant.rb
With Vagrant we use rsync for folder sync, as nfs has a character restriction of  88 characters. So depending on the module name and where it's being stored, it can error out with:
```
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -t nfs '10.0.1.1:/Users/petersouter/projects/reallylongpathnameover88characterssothatmountfswillfail12345678910111213141516' '/vagrant'
Stdout from the command:
Stderr from the command:
mount_nfs: 10.0.1.1:/Users/petersouter/projects/reallylongpathnameover88characterssothatmountfswillfail12345678910111213141516: File name too long
```
Further reading if interested:
http://www.secnetix.de/olli/FreeBSD/mnamelen.hawk …
=> (BKR-113) Adds FreeBSD Vagrantfile logic

lib/beaker/host/unix/pkg.rb, lib/beaker/host_prebuilt_steps.rb
this change fixes check_for_package on sles10 in which zypper always
returns 0, even if a package is not found.
This change also removes ntp package from the host pre-build steps.
sles10 comes with ntp_command installed.
=> (BKR-209) check for package and host prebuild sles10

lib/beaker/hypervisor/openstack.rb
Add optional :openstack_region config key to tell beaker which region to use
Fixes https://tickets.puppetlabs.com/browse/BKR-27
=> [openstack] enable support for multiple regions

lib/beaker/dsl/install_utils/module_utils.rb
The rsync method uses 'source' as the variable to rsync from, but sadly it's nil
=> (BKR-225) rsync module_utils method source is always nil

lib/beaker/dsl/helpers/facter_helpers.rb, lib/beaker/dsl/helpers/hiera_helpers.rb, lib/beaker/dsl/helpers/host_helpers.rb, lib/beaker/dsl/helpers/puppet_helpers.rb, lib/beaker/dsl/helpers/tk_helpers.rb, lib/beaker/dsl/helpers/web_helpers.rb, lib/beaker/dsl/install_utils/pe_utils.rb, lib/beaker/host.rb, lib/beaker/host/pswindows/pkg.rb, lib/beaker/host/unix/pkg.rb, lib/beaker/host/windows/pkg.rb, lib/beaker/host_prebuilt_steps.rb, spec/beaker/dsl/install_utils/pe_utils_spec.rb, spec/beaker/host/unix/pkg_spec.rb
- updates shared options to be current (with info for
accept_all_exit_codes and friends)
- yard doc does a single pass and you can't guarantee file ordering, so
you have to have the common options macro in each file that needs it -
duplication yay!
- update usage of acceptable_exit_codes to accept_all_exit_codes when we are just passing acceptable_exit_codes a mega array
=> (BKR-215) Document all of the options to #on and friends

lib/beaker/shared/host_manager.rb
- if a logger is defined then send a warning message if attempting to
run a command against an array of 0 nodes
=> (BKR-224) on(node, 'puppet agent -t') raises no warning when node = []

lib/beaker/hypervisor/aws_sdk.rb
(BKR-217) aws_sdk: given CONFIG subnet_ids, try each in turn
This should help alleviate the EC2 InsufficientInstanceCapacity.
The new policy will only be applied to a host if there isn't a CONFIG
subnet_id and there isn't a host-specific subnet_id.  When it does
apply, try each subnet in subnet_ids once for each relevant host.
The new option can be used like this:
CONFIG
vpc_id: foo
subnet_ids:
- x
- y
- z
=> (BKR-217) aws_sdk: given CONFIG subnet_ids, try each in turn

lib/beaker/answers/version30.rb, spec/beaker/answers_spec.rb
This involves the customizability of a number of answers required in order to setup an external postgres through Beaker.
=> (BKR-235) Added Customization for External Postgres

lib/beaker/dsl/install_utils/pe_utils.rb, spec/beaker/dsl/install_utils/pe_utils_spec.rb
We were only using puppet-agent for 4.0, this
commit bumps that down to 3.99.
=> (QENG-2009) Fix windows MSI name for 3.99

lib/beaker/host/freebsd/exec.rb, spec/beaker/host/freebsd/exec_spec.rb
Previous command didn't wrap printf string in `"`
Stops command working:
```
freebsd-9-x64 executed in 0.04 seconds
Warning: ssh connection to 10.255.52.108 has been terminated
freebsd-9-x64 20:12:47$ printf 127.0.0.1\tlocalhost localhost.localdomain\n10.255.52.108\tfreebsd-9-x64\n > /etc/hosts
Attempting ssh connection to 10.255.52.108, user: root, opts: {:config=>"/var/folders/nn/408ddhln26s1b356ry19q6yr0000gp/T/freebsd-9-x6420150518-65951-3jag0b"}
printf: missing format character
```
=> (BKR-276) Fixes `#echo_to_file` for FreeBSD

lib/beaker/hypervisor/vagrant_virtualbox.rb
Extends the Vagrant VirtualBox hypervisor to allow per host definitions
of storage volumes, for testing things like ceph and other storage
technologies.
An example nodeset provisions the VM with 3 attached storage volumes
available as sdb, sdc, sdd (on linux systems) at at SCSI addresses
2:0:0:0, 3:0:0:0, 4:0:0:0.  Sizes are specified in MB.
HOSTS:
osd0:
hypervisor: vagrant
volumes:
osd0_0:
size: 10000
osd0_1:
size: 10000
journal:
size: 1000
=> (BKR-281) VirtualBox: Add support for storage arrays

lib/beaker/dsl/helpers.rb, lib/beaker/dsl/helpers/test_helpers.rb, lib/beaker/dsl/install_utils/puppet_utils.rb, lib/beaker/test_case.rb, spec/beaker/dsl/helpers/test_helpers_spec.rb, spec/beaker/dsl/install_utils/puppet_utils_spec.rb, spec/beaker/dsl/structure_spec.rb
- beaker-rspec needs access to @metadata, broken with beaker 2.12.0
- Beaker-rspec missing @logger accessor
Added both logger and metadata accessors so that beaker-rspec can be
repaired to work with latest beaker releases.
=> (BKR-283)/(BKR-262) missing @metadata/@logger accessors for beaker-rspec

beaker.gemspec
Prior to this we were using the hocon gem and pinning to a z release.
This commit relaxes the version dependency to pull in an pre-1.0 hocon
release.
This is necessary for testing the hocon module itself.
=> (maint) Relax constraint on hocon

lib/beaker/hypervisor/openstack.rb
Some cloud-init configuration does not have `manage_etc_host: true` so the VM does not have a valid FQDN which is quite annoying because some services refuse to start without a valid FQDN.
This patch force cloud-init to manage `/etc/host` and thus set a valid fqdn.
=> (BKR-300) Always manage_etc_hosts in cloud-init

lib/beaker/hypervisor/docker.rb, spec/beaker/hypervisor/docker_spec.rb
Several fixes to be able to use Swarm with beaker.
When we want the IP address of the container with running swarm we have to fetch the IP of the swarm slave it self.
This is required since DOCKER_HOST env var will point to the Swarm Master and not the resulting docker host where the image will be running.
By default the build command is ran on a random node, the Container create + run command could be executed on a completely different node causing the create to fail since that node does not have just built image.
To distribute the same built image between all swarm slaves we need to push the image to a private registry.
If the image does not exist yet ( first build ) we tag + push it, If it does exist we will re-use it.
If we built the image on Node A but then the run command is …
=> (BKR-242) Docker swarm

acceptance/pre_suite/puppet_git/install.rb
This is in our puppet_git acceptance tests.
This will make our testing more stable in the future (movie from release to release rather than running on a branch).
=> (MAINT) moving from stable to a release for facter & hiera

lib/beaker/options/parser.rb, spec/beaker/options/parser_spec.rb
- check to see if a custom ssh user has been defined, if so then use
that instead of the default user per-OS type
=> (BKR-248) support connecting to SUTs with user/password

lib/beaker/platform.rb
@anodelman @melissa @camlow325 
This should fix the debian8 failure on the puppet-server pipeline. I believe the Beaker team will be releasing a new dot release this afternoon, hopefully this patch will be included which would minimize the effort necessary to get the debian8 cells green on the puppet-server master branch pipeline.
=> (BKR-307) Add Beaker::Platform support for debian jessie (aka 8)

lib/beaker/host.rb
Before this commit, the method Beaker::Host.do_scp_to would request
copying of both directories and files from the underlying scp
connection. This resulted in a lot of redundant copying since the
scp connection, when handed a directory, would copy it recursively.
This commit ensures that only the files are copied. This is safe
because all remote directories are already created in a preceding
step.
=> (BKR-304) Prevent redundant copying when doing scp

lib/beaker/hypervisor/vmpooler.rb, spec/beaker/hypervisor/vmpooler_spec.rb
When beaker's vmpooler is provided with an empty `~/.fog` file, a failure with a cryptic message has been the result.  This changes that behavior to be more user-friendly (continuing without authentication, posting a friendly warning); as well as improving test coverage in this area, and making other failures more user-friendly as well.
/cc @anodelman @kevpl
=> [BKR-301] add warning when empty fog file is encountered

lib/beaker/hypervisor/aws_sdk.rb, spec/beaker/hypervisor/aws_sdk_spec.rb, spec/helpers.rb
When bringing up an instance in a VPC there won't always be a public address.  This allows fallback to assign the private ip to host['ip'] for instances without a public address.
When the hypervisor is set to ec2, beaker can't currently connect to an instance that we're provisioning unless we have provisioned first then set a R53 public ip for subsequent runs.  This change would allow users inside a VPC to achieve complete end-to-end beaker runs from either a bastion or across whatever VPN solution they have set up.
Either insight on anything we might be missing or a merge would both be much appreciated!  Thanks :)
=> (BKR-311) Allow AWS IP Fallback

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
Currently this step uses `echo_to_file`, which actually overwrites the file with the one line. This changes it to use the perl regex instead.
=> (BKR-326) Fixes enabling user environments

lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/dsl/install_utils/pe_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb, spec/beaker/dsl/install_utils/pe_utils_spec.rb
- check the pe_ver/version to see if aio pathing should be installed
instead of foss/pe
=> (BKR-325) AIO detection for install_puppet() and install_pe()

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
- As per suggestion in [BKR-314](https://tickets.puppetlabs.com/browse/BKR-314?focusedCommentId=182682&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-182682) by @MikaelSmith, add `--replacepkgs` to rpm install
- Update tests accordingly
=> (BKR-314) Ensure install_puppetlabs_release_repo is idempotent for EL

lib/beaker/dsl/install_utils/module_utils.rb, lib/beaker/host/pswindows/exec.rb, lib/beaker/host/unix/exec.rb, spec/beaker/dsl/install_utils/module_utils_spec.rb, spec/beaker/host/unix/exec_spec.rb, spec/beaker/host/windows/exec_spec.rb
Without this patch, the `copy_module_to` function will not work correctly to copy updated module files into the target directory on the hosts. Acceptance test spec files can be updated, but not module sources. Additionally the module copy will fail on the second non-provisioning run.
The patch simply executes a delete of the target directory on the host, ensuring it does not exist prior to the mv command.
=> (BKR-339) Remove the target module directory on host during copy_module_to

lib/beaker/options/parser.rb, spec/beaker/options/parser_spec.rb
- make sure that we are sorting through env variables, command line
arguments, host file options, options file argument and presets
correctly
=> (MAINT) add spec testing to option parsing prioritization

lib/beaker/answers.rb, lib/beaker/shared/semvar.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb, spec/beaker/shared/semvar_spec.rb
- update semver matching to understand that 3.0.0 < 2015.3.0.0
- update answer file generation to provide 4.0 answers for version 2015+
=> (BKR-344) Support year.release versioning (e.g. 2015.2)

lib/beaker/host/unix/pkg.rb
- accidentally changed as a ride along to puppet-agent installation
work, return to correct state
=> (BKR-378) RHEL4 runs fail due to the absence of yum

lib/beaker/answers/version30.rb, spec/beaker/answers_spec.rb
- not correctly using 'answer_for' to determine if there is a provided
value for all questions
- fixed up some variable naming for clarity
=> (BKR-370) beaker doesn't use answers set as env vars

acceptance/tests/hypervisor/communication.rb, lib/beaker/host/pswindows/exec.rb, lib/beaker/host/unix/exec.rb, lib/beaker/host/windows/exec.rb, lib/beaker/hypervisor/aws_sdk.rb
- add acceptance/tests/hypervisor/communication.rb, checks to ensure
that hosts can ping each other
- enable ping for aws ec2 instances created by beaker
- create host.ping method to ping from host to a second host, return
'true' when ping is successful, 'false' otherwise
=> (BKR-367) create beaker ec2 smoketest

lib/beaker/host.rb, spec/beaker/host_spec.rb
As discussed here: https://tickets.puppetlabs.com/browse/BKR-365 
With this fix we can now move forward with https://tickets.puppetlabs.com/browse/BKR-277
which would allow us to use rsync to sync fixtures over to the SUT.
=> BKR-365 - allow beaker to use ssh config with rsync

lib/beaker/dsl/install_utils/foss_utils.rb
- should use #{variant} and not hardcoded debian, otherwise pukes on
ubuntu
=> (MAINT) bad hardcoded 'debian' in puppet-agent promoted installation

lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/platform.rb
(BKR-384) install_puppet_agent_dev_repo needs to support osx
- able to install dev puppet-agent on osx
example:
install_puppet_agent_dev_repo_on(host,
{ :puppet_agent_sha => 'c2946821d1bcd7e43a34bd1f9cd2f86160ca4fe0',
:puppet_agent_version => '1.2.1.23.gc294682'    })
(BKR-385) beaker needs to be able to convert mac codename to version number
- add support to the platform object to handle yosemite -> 10.10 and
mavericks -> 10.9 conversions for osx variant
=> (BKR-384) & (BKR-385) support for dev puppet-agent installation on osx

lib/beaker/hypervisor/aws_sdk.rb
AMIs using the instance storage root device type are now supported
allowing users who don't want/need EBS backed AMIs to add nodesets
more easily.
Tests aren't easily done for this chunk of the AWS hypervisor currently. A
separate ticket (BKR-349) has been added to wrap in testing for this method
along with a number of other currently untouched AWS methods.
All existing tests pass currently and everything is (for now) rebased up to master.
=> (BKR-348) AWS: Adding instance storage support

lib/beaker/host/mac.rb, lib/beaker/host/mac/exec.rb, spec/beaker/host_spec.rb
- ensure that you can run the host.touch command successfully on mac
- ride along: touch also broken on windows, fixed and operational
- added acceptance test to ensure that this works against all platforms
=> (BKR-388) Beaker::Host::Mac#touch returns non-existent path

lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/dsl/install_utils/pe_utils.rb, lib/beaker/dsl/roles.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb, spec/beaker/dsl/install_utils/pe_utils_spec.rb, spec/beaker/dsl/roles_spec.rb
- only use aio defaults on agents that are not master, database or
dashboard (was previously using aio defaults/paths on all hosts
identified as being >= 4.0)
=> (BKR-390) Scooter pipeline is using pe-httpd instead of pe-puppetserver

lib/beaker/dsl/install_utils/pe_utils.rb, spec/beaker/dsl/install_utils/pe_utils_spec.rb
Previously we installed puppet-agent on a host if there was the agent
role and no other role assigned to it. This prevents assigning a
puppet-agent node the "default" role to be used as the default test
target, or allow any other custom roles.
To allow assigning the "default" or custom roles to a puppet-agent node
we list the non-puppet-agnet roles we know how to generate installation answers
for and use that list to determine what nodes are puppet-agent or not.
=> (maint) Allow PE puppet-agent installs on custom roles

lib/beaker/hypervisor/openstack.rb
Implement the storage array feature introduced for vagrant virtual box
to OpenStack users.  Unlike virtual box the bus type is outside of our
control.  If you need SCSI support this must be attached to the image
in glance.  How to do this is in the method documentation
=> (BKR-347) Openstack: Add support for cinder attached volumes

lib/beaker/dsl/install_utils/foss_utils.rb
Prior to this we used rpm, which means puppet-agent won't resolve its dependency on dmidecode for EL systems.
To ensure that it correctly resolves that dependency we need to use yum.
=> (BKR-397) Use yum for installing pe promoted puppet-agent

lib/beaker/dsl/install_utils/foss_utils.rb
In BKR-397 we updated rpm using platforms to use yum instead of rpm in
the install_puppet_agent_pe_promoted_repo, however it wasn't noticed
that SLES was also an rpm using platform in the match that doesn't also
include yum.
This patch moves SLES platforms into their own branch of logic that uses
the old rpm installation method while retaining the yum based
installation for other platforms.
=> (BKR-403) Use rpm on sles for pe puppet-agent

lib/beaker/dsl/install_utils/aio_defaults.rb, lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/dsl/install_utils/pe_defaults.rb, lib/beaker/dsl/install_utils/pe_utils.rb
- provide a sane default for puppetservice for aio defaults, but allow
override with a user setting
=> (BKR-402) Regression in Beaker 2.18.0 AIO testing for PuppetDB usage

lib/beaker/hypervisor/vagrant_virtualbox.rb
Looks like these got moved into the `if` logic for `disk_path` accidentally around v2.8. This means that you can no longer use these options without adding disk_path logic in later versions of Beaker. This moves them back into their own section.
=> (maint) Moves various VB options out of `disk_path` logic

lib/beaker/hypervisor/openstack.rb
There is a delay between a volume being detached from a virtual machine and
when it is ready to be deleted.  The code as it stands is likely to hit a 400
error as the volume is still in the 'detaching' state.  Add in a wait_for
statement to allow the volume to get back into the 'available' state before
deleting
=> (BKR-401) fix race in OpenStack volume deletion

lib/beaker/dsl/install_utils/foss_utils.rb
Prior to this we were over eagerly failing if there was no puppet-agent
version explicitly set.  Having install_puppet_agent install the latest
released version of puppet-agent is a desired and common workflow.
This patch removes the aggressive failing on non-specified puppet-agent
versions in `install_puppet_agent_on`
=> (BKR-420) Allow easily installing latest puppet-agent

lib/beaker/dsl/install_utils/pe_utils.rb
When installing Windows agents with cygwin or any other means, always
prefer `start /w` over just calling msiexec.
This adds to what was first introduced in 9c32cac.
Also adds using `type` over `cat` in pure Windows
- If the host is not a cygwin environment, prefer `type` to produce the
contents of the log file over `cat`. `type` is built-in, where `cat` is
only available if someone has put *nix tools on the path, whether
through a git install (MinGW tools), installing GnuWin utils or some
other method.
=> (maint) Always wait for Windows agent installs

lib/beaker/hypervisor/vagrant_virtualbox.rb, spec/beaker/hypervisor/vagrant_spec.rb, spec/beaker/hypervisor/vagrant_virtualbox_spec.rb
(BKR-417) This patch adds support for configuring the number of CPUs for vagrant VirtualBox instances. The `vagrant_cpus` config option is used to set the value.
=> (BKR-417) Add support for specifying # of CPUs in VirtualBox

lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/host/freebsd.rb, lib/beaker/host/freebsd/pkg.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
Refactored to use native method and allow installing on an array of hosts
=> (BKR-326) Fixes FreeBSD install to use ports

lib/beaker/dsl/structure.rb, spec/beaker/dsl/structure_spec.rb
- add support to confine to all hosts *except* those in provided host
array
=> (BKR-410) `confine :except, {}, [host1,host2]` does not work as expected

lib/beaker/options/presets.rb
- not quite sure what is going on here, but removing the timeout and
using the Net::SSH default allows ubuntu15.04 to reboot successfully
(was stuck on a blocking call to Net::SSH.start)
=> (BKR-372) add support for ubuntu 15.04, Vivid, amd64 & i386

lib/beaker/host.rb, lib/beaker/host/windows/exec.rb, lib/beaker/ssh_connection.rb, spec/beaker/host_spec.rb, spec/beaker/hypervisor/aixer_spec.rb, spec/beaker/hypervisor/solaris_spec.rb, spec/beaker/ssh_connection_spec.rb, spec/helpers.rb
- to fix current smoketest redness change how we connect to beaker boxes
- do three separate connection attempts (with retries)
* first with ip
* then the virtual hostname (vmhostname)
* then the name of the box provided by the user (hostname)
- Only when all three fail do we fail out
- decrease the Net::SSH timeout so that we can move through the various
attempts in a reasonable amount of time
- add a sleep post windows reboot, getting reds here because windows
takes so long to come back up
=> (BKR-422) debian7 fails to reboot during smoketest

lib/beaker/dsl/install_utils/aio_defaults.rb, lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/dsl/install_utils/pe_utils.rb, lib/beaker/dsl/install_utils/puppet_utils.rb, lib/beaker/dsl/roles.rb, lib/beaker/host_prebuilt_steps.rb, lib/beaker/options/options_hash.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb, spec/beaker/dsl/install_utils/pe_utils_spec.rb, spec/beaker/dsl/install_utils/puppet_utils_spec.rb, spec/beaker/dsl/roles_spec.rb, spec/beaker/host_prebuilt_steps_spec.rb, spec/beaker/options/options_hash_spec.rb, spec/mocks.rb
- having made 'aio' a type meant that we were losing pe/foss specific
information (like the puppet service)
- make 'aio' a role that a host can have, meaning that the aio defaults
will be installed overtop of any foss/pe defaults
- assume hosts with no pe/foss puppet version provided are aio
=> (BKR-412) clarify 'types' in beaker

lib/beaker/hypervisor/vmpooler.rb
Per QENG-1304 and https://github.com/puppetlabs/vmpooler/pull/118, vmpooler requires a token be used during the 'cleanup' phase if one was specified during the 'checkout' phase.
=> (maint) Supply token (if exists) during VM cleanup

lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/dsl/install_utils/pe_utils.rb, lib/beaker/dsl/install_utils/windows_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb, spec/beaker/dsl/install_utils/pe_utils_spec.rb, spec/beaker/dsl/install_utils/windows_utils_spec.rb
- Refactor the do_install portion of pe_utils so that it no longer uses
the installer_cmd helper when on Windows.  Instead, extract out a new
MSI installation helper to WindowsUtils called install_msi_on.
- There are 4 separate points in the code where an MSI installation can
be launched from, that all differ in foss_utils.  Unify all entry points to use the
helper install_msi_on from WindowUtils.
Simplify the logic in the foss_utils install_a_puppet_msi_on
- install_msi_on expects 4 parameters
hosts - to run the installer on
msi_path - can be a local path on disk or uri
msi_opts - options passed to the installer to configure behavior
opts - additional options, currently only :debug to emit the log
after installation
- After completing an MSI install, verify the service status of the …
=> (BKR-421) Refactor MSI installation

acceptance/lib/beaker/acceptance/install_utils.rb, acceptance/pre_suite/puppet_git/install.rb, acceptance/tests/foss_utils/clone_git_repo_on.rb, lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
This change merges changes to install_from_git that were overloaded into
puppet and other repos' acceptance libraries.
We also split the cloning portion of install_from_git into its own
method, added options that are passed through to on() and moved a method
to beaker's acceptance library that needs to be shared across tests
(install_packages_on).
This addition of an acceptance library for beaker *may require changes* to
the jenkins CI configuration, to add the library to the test-runner's
load-path.
The merge-up also brought in helpers for install_from_git,
build_git_url() and lookup_in_env().
=> (BKR-366) merge-up install_from_git changes from deployer and puppet

lib/beaker/test_case.rb, spec/beaker/test_case_spec.rb
Prior to this, if a teardown method ran code which contained assertions, and an assertion failed, the exception raised by the assertion failure was uncaught and beaker would crash.
This change treats the assertion failure as a test failure and allows beaker to continue running.
/cc @anodelman @kevpl @cowofevil
=> [BKR-428] gracefully handle assert failure in teardown

lib/beaker/hypervisor/vagrant_virtualbox.rb
This retains the ability to set CPUs and memory at the global level, but will also allow you to set it in the nodeset file. It will use the most specific setting.
```yaml
aio-master-2.vm:
roles:
- passive_master
platform: el-6-x86_64
box: puppetlabs/centos-6.5-64-nocm
box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-6.5-64-nocm
hypervisor: vagrant
ip: '10.120.115.9'
vagrant_memsize: 5120
vagrant_cpus: 2
```
=> (BKR-423) Added the ability to set CPUs and memory per node

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
- incorrectly adding additional '.' to ubuntu version strings that were
already correct
- added spec test to ensure correct behavior
- passed local testing
=> (BKR-447) Ubuntu PE puppet-agent urls not being generated correctly

lib/beaker/host.rb, spec/beaker/host_spec.rb
The close method for hosts assumed the connection object existed when
trying to set the hostname; this fix checks to ensure the connection
object exists prior to calling any methods on it.
=> (BKR-448) Check for connection object during host.close

lib/beaker/host_prebuilt_steps.rb
Some fixes so beaker also works on solaris ( startup a solaris vagrant box)
for now only some host_prebuilt_steps.rb fixes
- copy certs to solaris root home folder /
- gsed of CSW to update sshd_config to allow ssh root login
- restart sshd daemon
Tested on this solaris 10 vagrant box made by packer https://github.com/biemond/packer-vagrant-builder
=> BKR-408 Supporting solaris as a beakernode

acceptance/fixtures/package/deb/pl-puppetserver-latest-lucid.list, acceptance/fixtures/package/deb/pl-puppetserver-latest-precise.list, acceptance/fixtures/package/deb/pl-puppetserver-latest-squeeze.list, acceptance/fixtures/package/deb/pl-puppetserver-latest-trusty.list, acceptance/fixtures/package/deb/pl-puppetserver-latest-vivid.list, acceptance/fixtures/package/deb/pl-puppetserver-latest-wheezy.list, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-el-6-i386.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-el-6-x86_64.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-el-7-i386.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-el-7-x86_64.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-20-i386.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-20-x86_64.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-21-i386.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-21-x86_64.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-22-i386.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-22-x86_64.repo, acceptance/tests/base/packages.rb, acceptance/tests/base/packages_unix.rb
Add acceptance tests that exercise the host packages functionality. There are two test files: one for all hosts and one targeting unix hosts specifically.
This includes fixtures for supporting the deploy_*_repo methods.
=> (maint) Add Package Acceptance Tests

lib/beaker/dsl/install_utils/aio_defaults.rb, lib/beaker/dsl/install_utils/module_utils.rb, lib/beaker/host/pswindows/exec.rb, spec/beaker/dsl/install_utils/module_utils_spec.rb, spec/beaker/host/windows/exec_spec.rb
- beaker powershell regressions discovered while working on this bug,
mostly around ensuring that we are using the correct path separator on
pswindowns machines
=> (BKR-293) PowerShell Hangs on Windows 2008 R2 WMF 5.0 Beta

lib/beaker/hypervisor.rb, lib/beaker/hypervisor/noop.rb
- support for a 'noop' hypervisor that does no
configuration/validation/provision/cleanup/proxy-ing
=> (BKR-458) add beaker notouch hypervisor

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
Adds Solaris support for installing packages in the
install_puppet_agent_dev_repo_on helper.
Also rewrites the Solaris 10 host pkg utils to use the system tools,
pkgadd and pkgrm, because pkgutil won't install the Solaris package we
produce without asking questions.
=> (BKR-470) Add Solaris to install_puppet_agent_dev_repo_on

lib/beaker/dsl/helpers/host_helpers.rb, spec/beaker/dsl/helpers/host_helpers_spec.rb
Prior to this, the host helper method `add_system32_hosts_entry` was available to any windows platform, including cygwin-enabled windows installs. This method only actually works on non-cygwin windows platforms. This discrepancy was uncovered during work for BKR-358, where we are adding acceptance tests for the host helper methods.
/cc @puppetlabs/beaker
=> (MAINT) constrain `add_system32_hosts_entry`

lib/beaker/hypervisor/aws_sdk.rb, spec/beaker/hypervisor/aws_sdk_spec.rb
Doing this without a lot of duplicate code required me to add new functionality into the `wait_for_status` method, whereby you could pass a block to do more involved checking for a particular status of a given instance.
=> (BKR-469) added f5 wait checks

lib/beaker/cli.rb, spec/beaker/cli_spec.rb
- instead of just removing the pre_suite/post_suite/tests from
the options, explicitly set it to be []
- this means that you don't end up accidentally running a pre-suite
defined in a secondary options file
=> (BKR-440) host_preserved.yml file should disable the pre_suite

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
The planned Solaris package names for the puppet-agent package were
changed to incorporate a release version, as already handled for other
platforms. Update the Solaris package name to include the hard-coded
release `1` naming.
=> (BKR-504) Update Solaris package name for release version

acceptance/tests/base/dsl/structure_test.rb, lib/beaker/dsl/structure.rb
Prior to this, use of `confine_block` would result in all following code in the test case being skipped in situations where the host list had no matches for the confine_block.  The entire purpose of `confine_block` is to limit the scope of the confine to the passed block.
Also, `ensure` and `rescue` at the method level do not require an additional wrapping `begin..end` block.
This was tested locally against the acceptance test suite still in development (and currently partially blocked by this bug) at https://github.com/puppetlabs/beaker/pull/930
/cc @puppetlabs/beaker @justinstoller
=> (BKR-505) rescue `SkipTest` in `confine_block`

lib/beaker/host_prebuilt_steps.rb, lib/beaker/platform.rb
- correctly turn on ssh user environment support
- update platform list
=> (BKR-482) Add support for OSX 10.11 El Capitan (x86_64)

lib/beaker/hypervisor.rb, lib/beaker/options/presets.rb, spec/beaker/hypervisor/hypervisor_spec.rb
This helps to identify hosts if you do not destroy them.
If defined, hostname is prefixed.
=> (BKR-515) add config option host_name_prefix

lib/beaker/hypervisor/aws_sdk.rb, spec/beaker/hypervisor/aws_sdk_spec.rb, spec/helpers.rb
Used the EnvCredentials class provided by the AWS SDK to fetch credentials. You can (optionally) set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables instead of populating ~/.fog. If they aren't both set, then we fall through to loading .fog, which behaves as it did before.
New tests added around the new load_credentials and load_env_credentials. Also added tests for load_fog_credentials which had been mocked out in the spec to return the entire .fog file fixture rather than just the credentials.
=> BRK-431: Find AWS credentials from environment variables

lib/beaker/dsl/helpers/puppet_helpers.rb, lib/beaker/dsl/install_utils/pe_utils.rb, lib/beaker/host_prebuilt_steps.rb
The curl command on AIX does not support the `-k flag`. This commit
creates condition statements to replace the `-k` flag in the curl
options with `--tlsv1` when the platform is AIX.
=> (BKR-520) Add curl options for AIX

lib/beaker/hypervisor/docker.rb
Capture the strange error message from docker (and all other internal docker errors) and display the message as a logged warning instead of a stack trace.  This will preven the message from causing a CI test failure as the exit status is now zero.
Doesn't address the root-cause of this warning message but handles it in a more graceful way
=> (BKR-523) Beaker prints error message on exit when using docker containers

lib/beaker/hypervisor/vmpooler.rb, lib/beaker/options/presets.rb
- increase timeout to 15 minutes
- write out failure message to get more information about why the pool
request failed
=> (BKR-514) increase polling timeout when requesting vpool instances

lib/beaker/dsl/structure.rb, spec/beaker/dsl/structure_spec.rb
- make it possible to confine to a subset of hosts + all hosts not in
the subset.
To confine to only windows agents + any non-agent hosts
confine :to, { :platform => 'windows' }, agents
To confine to non-windows agents + any non-agent hosts
confine :except, { :platform => 'windows' }, agent
- Useful for cases where you want to use your master, but only operate
on a subset of agents
=> (BKR-533) Beaker's `confine` overwrites the array of all hosts

lib/beaker/host_prebuilt_steps.rb, lib/beaker/options/presets.rb, spec/beaker/host_prebuilt_steps_spec.rb
Some new code to hopefully pass tests. Adds support for epel7 in epel_info_for and add_el_extras, as wel as adding a test for el7 url retrieval.
=> (BKR-327) Add support for EL7 to epel_info_for and add_el_extras method

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
This commit updates install_utils/foss_utils to use `p5p` as
the expected package suffix for puppet-agent when the platform
is Solaris 11. Solaris 10 will continue to use `pkg.gz` as its
expected suffix.
=> (BKR-545) Use p5p for Solaris 11 puppet-agent pkgs

lib/beaker/dsl/install_utils/foss_utils.rb
This commit dups the `opts[:puppet_agent_version]` in the foss_utils to
prevent a `RuntimeError: can't modify frozen String` error
=> (BKR-545) Dup solaris puppet_agent_version

beaker.gemspec
- pin fog-google to 0.0.9, 0.1 release removed ruby 1.9 support
=> (BKR-564) beaker no longer works on ruby 1.9.3

lib/beaker/hypervisor/aws_sdk.rb, spec/beaker/hypervisor/aws_sdk_spec.rb
Before, ec2 keys would only be created if this was the first run for
a particular user/coordinator. This is a problem for F5 testing, in
which F5 hosts needed to be created with a particular key. We were
using cached keys, which weren't the ones being used in ec2.
The original solution was to delete the keys in ec2, so that they'd
be recreated as if this was the first run by a user. @justinstoller
brought up the good point that if this were to happen, certain
Beaker runs would have their keys deleted from a new F5 run. The
solution became that each Beaker run would generate its own key,
deleting it on cleanup.
/cc @LuvCurves
=> (BKR-522) now creates new ec2 keys per run

lib/beaker/host.rb, lib/beaker/host/windows/exec.rb, lib/beaker/ssh_connection.rb, spec/beaker/ssh_connection_spec.rb
- improve the 'wait_for_connection_failure' ssh connection method
* increase the timeouts
* send actual data down the pipe, seems to improve the function of
the test
* remove 'abort' calls from the code, we can recover and retry
* added yard docs
- add /f to the windows reboot call
* forces closure of any open applications
=> (BKR-488) Add support for Windows 10 (x86, x64)

lib/beaker/dsl/helpers/host_helpers.rb, lib/beaker/dsl/wrappers.rb, lib/beaker/host/pswindows/exec.rb, spec/beaker/dsl/wrappers_spec.rb
- create new powershell dsl helper:
execute_powershell_script
* takes as input a string representing a powershell script
* create a file on the host containing the script
* executes the script using powershell -File
=> (BKR-275) PowerShell Wrapper Does not Handle Quoting

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
(BKR-380) beaker vagrant windows box support issues
Without "auto_correct" we got error if source Vagrantfile of box already contains this port forwarding.
```
Error:
vm:
* Forwarded port '3389' (host port) is declared multiple times
with the protocol 'tcp'.
```
I think we need add this change as most part of Windows boxes in Vagrant Atlas already have this port forwarding:
- https://github.com/joefitzgerald/packer-windows/blob/master/vagrantfile-windows_2012_r2.template
- https://github.com/boxcutter/windows/blob/master/tpl/vagrantfile-eval-win2012r2-standard.tpl
=> (BKR-380) Fix '3389' (host port) is declared multiple times

lib/beaker/dsl/helpers/puppet_helpers.rb, lib/beaker/dsl/patterns.rb, lib/beaker/shared/host_manager.rb
tried in #978 to update to a simple array of results in `apply_manifest_on`, but that breaks compatibility with current uses (check there for more details).
Since that's the case, I've updated the docs appropriately for current usage, & added a note for update during Beaker 3.0 changes later.
=> (BKR-571) updated documentation on return types

lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/host/unix/pkg.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
This commit adds a `remove_puppet_on` method that can be used to
ensure that puppet packages have been expunged from hosts.
This method is intended to be used in a pre-suite. It is currently
limited to the AIX and Solaris platforms.
=> (BKR-573) Add remove_puppet_on

lib/beaker/dsl/helpers/puppet_helpers.rb, spec/beaker/dsl/helpers/puppet_helpers_spec.rb
Previously, setting `:restart_when_done` to false on the master host, or
globally in options, did not work, because the `with_puppet_running_on`
method was checking for a truthy value.
This commit checks if the key is in the hash instead. It also preserves
the behavior where the options passed in by the test case take
precedence over the host's value.
=> (BKR-574) Allow global restart_when_done => false

lib/beaker/hypervisor/aws_sdk.rb, lib/beaker/hypervisor/vmpooler.rb, lib/beaker/options/parser.rb, lib/beaker/options/presets.rb, spec/beaker/hypervisor/aws_sdk_spec.rb, spec/beaker/hypervisor/vmpooler_spec.rb, spec/beaker/options/parser_spec.rb, spec/beaker/options/presets_spec.rb
This commit adds the ability to specify arbitrary tags and have them applied to AWS or vmpooler instances. The configuration parameter is called "host_tags" to avoid confusion with test tagging. Host tags can be specified at the host or CONFIG level.
The presets have been modified to pre-populate "host_tags" with: project, department, and created_by.
Example:
```
HOSTS:
'agent1':
roles:
- agent
host_tags:
created_by: 'me'
some_key: 'yes it is'
CONFIG:
host_tags:
project: 'beaker'
```
=> (QENG-2604) Add Host Tags

lib/beaker/dsl/install_utils/module_utils.rb, spec/beaker/dsl/install_utils/module_utils_spec.rb
The "copy_module_to" method does not detect if the target machine is Windows
after SCP copy of the module. It attempts to move the directory because path
joining does not account for "/" separators in the path.
=> (BKR-596) Fix Windows Path Support

lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/host/unix/pkg.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb, spec/beaker/host/unix/pkg_spec.rb
Without this patch applied, the call to rpm in Beaker::DSL::InstallUtils ignores the package_proxy option.
We add two new methods, extract_rpm_proxy_options and install_package_with_rpm.
The extract_rpm_proxy_options method is needed as the rpm command expects command line options --httpproxy and --httpport.
The install_package_with_rpm method is needed in order to install rpms from a remote URL address.  The existing install_package method uses yum and yum can't install an rpm from a remote URL.
Spec tests are provided for the extract_rpm_proxy_options method.  A redundant spec test is deleted.
=> (BKR-579) rpm calls to respect package_proxy opt

README.md
This was missed in the final change-over from Home.md during BKR-602. Updating so that
this points to the new correct place.
/cc @puppetlabs/beaker
=> (MAINT) Update main README.md docs link

beaker.gemspec
This commit adds a < 1.35.0 dependency constraint to the fog entry in
beaker's gemspec file. This fixes a problem introduced in fog 1.35.0
where it starts depending on a newer version of fog-google than beaker
currently allows.
=> (BKR-592) Add < 1.35.0 dep constraint to fog

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
This commit adds logic for gathering installed puppet packages
on cumulus for removal in the `remove_puppet_on` method
=> (BKR-597) Add cumulus logic to remove_puppet_on

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
Prior to this commit, Beaker installed -- and removed -- tar as
a dependency of the puppet-agent package on AIX. This dependency
has been removed from puppet-agent.
This commit removes the logic to install and remove the tar rpm
from AIX. It also updates the rpec test for `remove_puppet_on`
on AIX to remove the expectation that `tar` would a dependency.
=> (BKR-607) Remove tar dependency for AIX

docs/hypervisors/README.md, docs/hypervisors/aws.md, lib/beaker/hypervisor/aws_sdk.rb, lib/beaker/options/presets.rb, spec/beaker/hypervisor/aws_sdk_spec.rb
This property allows the user to make the AWS EC2 key name unique in their
Beaker runs. This property can be set from the CONFIG section of the hosts
file.
=> (BKR-598) made AWS EC2 key name collision impractical

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
Unset the RUBYLIB variable before shelling out to run vagrant.  Fixes dependency on outdated version of bundler
=> (BKR-511) Beaker fails to launch Vagrant VMs when run within Bundler

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
`version` variable missing, so get error:
`<NameError: undefined local variable or method 'version'>`
Rather than the correct error to raise:
`<RuntimeError: Puppet MSI at /puppet-agent-VERSION-x86.msi does not exist!>`
=> (BKR-583) Fixes incorrect error when MSI missing

acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb, acceptance/tests/base/dsl/helpers/host_helpers/rsync_to_test.rb, acceptance/tests/base/host_test.rb, lib/beaker/logger.rb, spec/beaker/logger_spec.rb, spec/mocks.rb
- [QENG-3063](https://tickets.puppetlabs.com/browse/QENG-3063)
Prior to this change, the `host_test.rb` check for rebooting systems could sometimes fail, only on our Beaker acceptance jenkins, but in such a way that it was clear that something was happening after the attempt to reboot started, but no further output was available.
Exploratory work showed that when a rebooted host changes IP address, it is possible for not only the normal long sequence of Fibonacci-fallback connect retries to happen, but for also various low-level TCP connection failures (with their own long timeouts) to occur.
Since output was being buffered, and not flushed, and neither of these phases was generating a lot of output (enough to trigger a buffer flush on its own), it was possible for more than our 10 minute …
=> [QENG-3063] Fix reboot test timeout issues on jenkins

lib/beaker/test_case.rb
Some exceptions implement the `#inspect` method to only print the class
name or otherwise change the output to not include the error message in
question, which makes such exceptions very challenging to deubg. This
commit changes the test case exception printing method to explicitly
print the exception class and message so that there's always relevant
context available when an exception is raised.
=> (BRK-617) Print exception message for test cases

docs/hypervisors/vagrant.md, lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
Without this patch there is no way to mount a local folder inside the beaker nodes.
With this patch folders can be mounted similar to below using the `mount_folders` option:
```
HOSTS:
ubuntu-1404-x64-master:
roles:
- master
- agent
- dashboard
- database
platform: ubuntu-1404-x86_64
hypervisor: vagrant
box: puppetlabs/ubuntu-14.04-64-nocm
box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
mount_folders:
folder1:
from: ./
to: /vagrant/folder1
tmp:
from: /tmp
to: /vagrant/tmp
ip: 192.168.20.20
ubuntu-1404-x64-agent:
roles:
- agent
platform: ubuntu-1404-x86_64
hypervisor: vagrant
box: puppetlabs/ubuntu-14.04-64-nocm
box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
ip: 192.168.21.21
CONFIG:
nfs_server: none
consoleport: 443
```
In the above beaker …
=> (BKR-625) Added ability to mount a folder.

beaker.gemspec
This commit will add an explicit dependency on the mime-types gem to
beaker's gemspec that installs versions less than 3.0 on systems with
a Ruby version less than 2.0.
This has to be done in order for beaker to install freshly on systems
where it hasn't been installed before.  The mime-types gem dropped
ruby 1.9.2 support with 3.0 and one of beaker's dependency, fog
depends on any version of mime-types greater than 0.
=> (BKR-633) Explicitly depend on mime-types.

lib/beaker/hypervisor/vcloud.rb
This commit adds a custom guestinfo keyword and hostname variable
that allows the VMware Tools to query the hostname.
Related to puppetlabs/vmpooler#139
=> (BKR-635) Add VM hostname to VMX data during cloning operations

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb, spec/helpers.rb
Without this patch applied the hostname can sometimes be incorrectly picked up and this
creates problem with all the hostnames getting the same IP addresses on a multi-node setup.
Example Nodeset that can cause this problem:
```
HOSTS:
staging:
roles:
- sta
- master
platform: el-6-x86_64
box: puppetlabs/centos-6.6-64-puppet
box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-puppet
hypervisor: vagrant
shared_folder: abc
NetworkSettings:
IPAddress: 10.255.50.100
etl:
roles:
- etl
platform: el-6-x86_64
box: puppetlabs/centos-6.6-64-puppet
box_url: https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-puppet
hypervisor: vagrant
NetworkSettings:
IPAddress: 10.255.50.120
CONFIG:
type: git
destroy: no
```
In the above scenario, the hostname 'etl' is also available when you search …
=> (BKR-622) Fix Regular Expression to give correct Host IP Address

lib/beaker/platform.rb, spec/beaker/platform_spec.rb
The version of Psych shipped with Ruby 1.9.3-p194 did not support
subclasses of String that added additional ivars to the String class.
The Beaker::Platform class does just that - subclassing String and
additional ivars - which meant that round tripping a Beaker::Platform
object would create an object with improperly initialized instance
variables. Psych commit e2fcf9af9e95535401f816bc893839b9ad743a9e
resolved that issue but we still use platforms that have the old version
of psych.
To resolve this issue, this commit implements a custom #init_with method
that explicitly sets all instance variables on the Beaker object that
were defined inside of the YAML map instance, and then reconstructs the
string value based on those fields.
/cc @er0ck
=> (BKR-634) Fix YAML deserialization for Beaker::Platform

lib/beaker/dsl/install_utils/foss_utils.rb
When trying to install puppet-agent collection packages through
`install_pe_on`, eventually `install_puppet_agent_pe_promoted_repo_on`
gets called but has no entry for where the solaris packages are kept.
This commit adds the ability for solaris to install PC puppet-agent
packages.
=> (BKR-472) (BKR-475) Fix solaris for install_pe_on with 2015.2

.gitignore, Rakefile
Since moving the wiki docs into the repo itself, there's been
an issue where if you ran the yard rake tasks, you'd blow away
the in-repo docs, because the default yard doc location is the
same as the in-repo docs location: . This change makes
yard create the  folder, and use it for local doc
generation
=> (MAINT) updated yard doc location

lib/beaker/dsl/install_utils/foss_utils.rb
Fixes typo introduced in #1016
=> (maint) Fix typo in solaris install_pe util function.

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
Previously, install_puppet_agent_dev_repo_on did not work for fedora,
because we were constructing a URL of the form:
http://<host>/puppet-agent/<sha>/repos/fedora/22/PC1/x86_64/puppet-agent-1.3.2-1.fedora22.x86_64.rpm
However, we unfortunately prepend 'f' to the version string when
publishing the package, see RE-4191.
This commit prepends an 'f' to the version string for fedora-only, so
the new URL is:
http://<host>/puppet-agent/<sha>/repos/fedora/f22/PC1/x86_64/puppet-agent-1.3.2-1.fedoraf22.x86_64.rpm
Note f22 appears in two places, "fedora/f22" and
"puppet-agent...-fedoraf22.x86_64.rpm"
=> (BKR-644) Prepend 'f' to the fedora version

lib/beaker/hypervisor/vagrant_libvirt.rb, spec/beaker/hypervisor/vagrant_libvirt_spec.rb
This add the possibility to specify the memory for each host separately
or for every host.
=> (BKR-631) Add memory option to vagrant libvirt.

lib/beaker/host.rb, lib/beaker/host/unix/exec.rb
This commit will rework the way PermitUserEnvironment is added to
sshd_config by putting it at the top of the file.
Without this commit you will create a bad sshd_config if your sut's
base image containes matching blocks the end of its sshd_config
because the PermitUserEnvironment option is not allowed there.  This
ordering is likely perferred since it is generally the norm to put
matching blocks at the end of the sshd_config.
=> Swap the placement of PermiteUserEnvironment

lib/beaker/dsl/install_utils/puppet_utils.rb
This commit will add privatebindir to the list of paths added to the
PATH variable stored in ~/.ssh/environment.
This needs to happen so that the gem command and any excutables
installed using that gem command are available for use during a suite.
A requirement if your suite deploys dependencies with r10k on both aio
and foss agent types.
=> Add privatebindir to PATH

lib/beaker/host/freebsd/pkg.rb, lib/beaker/host/unix/pkg.rb, spec/beaker/host/freebsd/pkg_spec.rb
* pkg_* is EOL as of Sept 2014 https://lists.freebsd.org/pipermail/freebsd-ports-announce/2014-February/000077.html
* On most base boxes, the pkg_* pointers are now 404:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
pkg_add -r rsync
Stdout from the command:
Error: Unable to get ftp://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-9-stable/Latest/rsync.tbz: File unavailable (e.g., file not found, no access)
```
* Also fixes (BK-438), as we're changing package install result to be the result, as is the same with other pkg helpers.
=> (BKR-661) Change to use pkgng for package installs

lib/beaker/options/presets.rb
This commit removes the keepalive_interval setting in presets.rb. This
was introduced to detect disconnections that were otherwise not noticed
unless beaker tried to write to the SSH session.
This change does still have keep alive enabled, but is now adhering to
the default interval of 300 (5 minutes).
=> (MAINT) Remove keepalive_interval

acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-23-i386.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-23-x86_64.repo
This change adds the fixtures needed for beaker to pass base acceptance for Fedora 23.
=> (BKR-480) added support for fedora23

lib/beaker/test_case.rb
I didn't consult anyone on this, but it is confusing to me when looking at logs, when my test case completes and when the teardown begins.  This message would help remove some of that confusion, especially in the case where you run into https://tickets.puppetlabs.com/browse/BKR-570
=> Add info log when teardown begins

docs/Beaker-Recipes.md, docs/README.md
This change adds a document containing some recipes for solving common
problems with Beaker.  It is currently housed on confluence.
=> (maint) move recipes from confluence

lib/beaker/host/pswindows/user.rb, lib/beaker/host/windows/user.rb, spec/beaker/host/pswindows/user_spec.rb, spec/beaker/host/windows/user_spec.rb
- Existing functionality used an overly restrictive regex that didn't
account for characters like - or . in Windows user names, which are
completely valid.
Use a less restrictive regex to capture the value correctly.  The
results of wmic always include the username immediately after the
= in the Name= string
=> (maint) Fix Windows user_list functionality

lib/beaker/command.rb, lib/beaker/dsl/helpers/host_helpers.rb, lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/host.rb, lib/beaker/host/pswindows/exec.rb, lib/beaker/host/unix/exec.rb, lib/beaker/host/unix/file.rb, lib/beaker/host/unix/pkg.rb, lib/beaker/host/windows/exec.rb, spec/beaker/command_spec.rb, spec/beaker/dsl/helpers/host_helpers_spec.rb, spec/beaker/dsl/install_utils/module_utils_spec.rb, spec/beaker/host/pswindows/exec_spec.rb, spec/beaker/host/unix/exec_spec.rb, spec/beaker/host/unix/file_spec.rb, spec/beaker/host/unix/pkg_spec.rb, spec/beaker/host/windows/exec_spec.rb, spec/beaker/host_spec.rb
Adds support for both puppet-agent install methods on wrlinux-5:
`install_puppet_agent_on` (from yum.puppetlabs.com)
`install_puppet_agent_dev_repo_on` (from builds.puppetlabs.net)
=> (BKR-668) wrlinux5 puppet-agent install support added

README.md, docs/Beaker-Libraries.md, docs/README.md
Update the Beaker docs README to point to the public Beaker libraries.
=> (MAINT) Add README Information for Beaker Libraries

lib/beaker/host.rb, lib/beaker/options/command_line_parser.rb, lib/beaker/result.rb, lib/beaker/ssh_connection.rb, spec/beaker/host_spec.rb
Removed $dry_run as a global variable.
Should be able to overwrite value from calling methods or use the parsed options hash value as default.
Returning from the original method if dry_run instead of continuing on and attempting a host connection.
=> (BKR-48) Change how --dry_run is defined - should not be global variable.

lib/beaker/hypervisor/docker.rb, spec/beaker/hypervisor/docker_spec.rb
Without this patch, a nodeset using relative `from:` paths under
`mount_folders:` with the `docker` hypervisor will encounter a
test-halting `Docker::Error::ClientError`.  This is a problem because
it forces docker-based nodesets to specify host-side mounts with
absolute paths, which isn't portable.
This patch fixes the issue by using Ruby's `File.expand_path()` method to
translate any relative `mount_folders:`/`from:` entries into absolute
paths before passing them on to docker.
=> (BKR-704) Allow relative `mount_folders` in docker

lib/beaker/hypervisor.rb, lib/beaker/network_manager.rb, spec/beaker/hypervisor/hypervisor_spec.rb
If it has been set. Otherwise use global timesync value.
Add spec tests.
example usage (hosts file):
```
q6zus77jx2ww8tf.delivery.puppetlabs.net:
roles:
- agent
- frictionless
timesync: false
platform: el-6-x86_64
template: Delivery/Quality Assurance/Templates/vCloud/centos-7-x86_64
hypervisor: vcloud
```
=> (BKR-99) - Populate host[:timesync] with host configured value.

lib/beaker/hypervisor/vmpooler.rb, spec/beaker/hypervisor/vmpooler_spec.rb
The issue is when one of the specified host cannot be acquired.
Raise an error and attempt again until timeout (the same as with other provisioning errors).
=> (BKR-671) - Add error handing for Beaker failing to acquire a VM from vmpooler

lib/beaker/hypervisor/docker.rb, spec/beaker/hypervisor/docker_spec.rb
* Frontload the DOCKER_HOST variable, as it's the easiest thing to check
* boot2docker-cli is deprecated (https://github.com/boot2docker/boot2docker-cli#deprecated)
* Error could also occur on Windows
=> (maint) Improves error message for Docker failure

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb
The `warning` methods in `deploy_package_repo` should have been simply
`warn`. This PR changes them to warn and adds appropriate spec testing
for the methods to ensure they `warn` correctly.
=> (BKR-451) Fix broken logger warnings

lib/beaker/host/windows/pkg.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
If a `puppet_agent_version` is specified, use it in
`install_puppet_agent_dev_repo_on` to fetch the MSI, so we get an MSI
unique to that SHA. This provides a work-around for BKR-712, and
normalizes behavior with `install_puppet_agent_on`.
=> (BKR-715) Use puppet_agent_version for MSI from dev repos

lib/beaker/dsl/install_utils/foss_utils.rb
The docs for `install_puppet_agent_on` specify that the `opts` arg is
optional, but it doesn't have a default value so in practice it's
required. Update the call signature to specify a default empty hash, so
the function matches its description.
=> (maint) Correct install_puppet_agent_on args

lib/beaker/hypervisor/docker.rb, lib/beaker/network_manager.rb, spec/beaker/hypervisor/docker_spec.rb
Per BKR-658, the Docker provisioner does not behave correctly when `BEAKER_provision=no` is used from beaker-rspec.  This corrects that behavior so the container is reused.  It defers to ::Docker::Container.create throwing raising an exception if `BEAKER_provision=yes` and the container currently exists, rather than blindly reusing the container (the previous behavior). 
Also added is a best effort at sshd_config repair for root logins.  Puppet users will often disable root logins, which breaks Beaker, so this attempts to revert such changes via Docker::Container#exec.
=> (BKR-658) Fix BEAKER_provision=no when using Docker

lib/beaker/command.rb
Quick and dirty fix for BKR-753 (breakage from #1085). It concerns me that we have no spec tests for the overall `cmd_line` construction for the Cisco platforms, which would have found this issue immediately if present.
A bigger-picture suggestion would be to reconsider the design for `Command.cmd_line` since now we have interdependencies between `command.cmd_line`, `host.prepend_commands`, and `host.environment_string`. Might be better in the long term to refactor this and have a single API like `host.munge_cmd_line` that takes all of `[cmd, env, pc]` as parameters just like `Command.cmd_line` does.
=> (BKR-753) Cisco IOS XR broken by BKR-749

Rakefile, acceptance/config/base/acceptance-options.rb, acceptance/config/hypervisor/acceptance-options.rb, acceptance/config/puppetgem/acceptance-options.rb, acceptance/config/puppetgit/acceptance-options.rb, acceptance/config/puppetpe/acceptance-options.rb, acceptance/config/puppetpkg/acceptance-options.rb, beaker.gemspec
'rake acceptance' for the main acceptance run.
Also the following individual tasks for individual sets of tests.
rake test:base
rake test:hypervisor
rake test:puppetpe
rake test:puppetgem
rake test:puppetgit
rake test:puppetpkg
=> (BKR-430) Adding rake tasks for running beaker acceptance tests.

lib/beaker/test_suite.rb
Noticed that Jenkins isn't picking up skipped status, so I updated the junit output based on schema at - https://svn.jenkins-ci.org/trunk/hudson/dtkit/dtkit-format/dtkit-junit-model/src/main/resources/com/thalesgroup/dtkit/junit/model/xsd/junit-7.xsd
=> (maint) change junit skip to skipped to match schema

lib/beaker/host/unix/exec.rb, lib/beaker/host/unix/pkg.rb, lib/beaker/platform.rb, spec/beaker/host/unix/exec_spec.rb, spec/beaker/host/unix/pkg_spec.rb, spec/helpers.rb
This PR adds support for the Huaweios platform. The LXC that this support adds is a Debian jessie variant, so the Huaweios platform will just be the same as any other Unix::Host.
=> (BKR-680) Add Huaweios support

lib/beaker/dsl/helpers/puppet_helpers.rb, spec/beaker/dsl/helpers/puppet_helpers_spec.rb
This commit adds a check for each host's :is_puppetserver key when using
the `with_puppet_running_on` command. Previously, it would only check
the global option for this key.
=> (BKR-219) Add support for :is_puppetserver per host

docs/Beaker-Installation.md
This change clarifies the notion of beaker as a test coordinator that
runs tests on a host separate from the SUT.
=> (maint) Clarify beaker installation guide

lib/beaker/dsl/install_utils/windows_utils.rb, spec/beaker/dsl/install_utils/windows_utils_spec.rb
- The puppet-agent package contains information about the various
component versions present, so log it after the MSI installation
has completed.
Without having this information logged by Beaker, it can be painful
to cross reference the agent commit vs the included component
versions.
=> (maint) Log Windows versions.txt post MSI install

lib/beaker/dsl/install_utils/foss_utils.rb
Using Ruby 2.2, the `opts` assignment in the Windows case of
`install_puppet_agent_dev_repo_on` overwrites the `opts` method
argument. This causes installs after Windows to fail in Puppet
acceptance runs. Fix by avoiding using the same variable name.
=> (maint) Avoid scoping change in Ruby 2.2

lib/beaker/host.rb, spec/beaker/host_spec.rb
Make acceptable_exit_codes override accept_all_exit_codes => true as the more specific of the two options.
=> (BKR-521) handle priority of :acceptable_exit_codes

lib/beaker/host/unix/pkg.rb
Puppet only publishes packages under the major version of a Solaris
release. Currently, if Beaker is passed a Solaris host with a minor
version (eg. solaris 11.2), it fails to find and install package.
This commit truncates the Solaris version to its minor component
in the solaris_puppet_agent_dev_package_info and
solaris_install_local_package  methods.
=> (BKR-767) Only use Solaris major version for pkg

beaker.gemspec
google-api-client dropped ruby 1.9 support in 0.9.5.
Ubuntu Trusty (current LTS) still have Ruby 1.9 by default, so it's
impossible to run beaker on this platform with official packaging.
See https://github.com/google/google-api-ruby-client/issues/397
=> (MAINT) bump google-api-client to ~> 0.8, < 0.9.5

lib/beaker/options/presets.rb, spec/beaker/host_prebuilt_steps_spec.rb
Change the default EPEL package name for EL7 from "epel-release-7-5.noarch.rpm" to "epel-release-7-6.noarch.rpm"
=> (BKR-770) Update EPEL package name for EL7

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb
Images used in beaker tests might have all kinds of preinstalled
packages on them, some of which may be out of date. In our case, we
were preinstalling the puppetlabs el 7.10 release package on images,
but then running beaker's install_puppet function as a provisional step
in our tests. Since a new release package was added, this started
failing[1]. We were able to fix this easily by fixing our images, but
users depending on externally hosted images, such as vagrant boxes, may
not be so lucky.
This patch changes the -i flag of the rpm install command to -U so that
the package will be either installed or, if already present but out of
date, upgraded. This will not change functionality for users with clean
images who do not need to upgrade anything. The --replacepkgs flag that
was already …
=> (MAINT) Use the upgrade install option for rpm packages

lib/beaker/hypervisor/vmpooler.rb
This commit gives a better error message to the user when beaker fails
to request a host set that doesn't exist in vmpooler.
Example updated error message:
```
Failed: errored in Vmpooler.provision
#<RuntimeError: Vmpooler.provision - response from pooler not ok. Requested host set ["fedora-20-x86_64"] not available in pooler>
/Users/brian/.rvm/gems/ruby-2.1.1@beaker-strings/gems/beaker-rspec-5.3.0/lib/beaker-rspec/spec_helper.rb:46
/Users/brian/.rvm/gems/ruby-2.1.1@beaker-strings/gems/beaker-rspec-5.3.0/lib/beaker-rspec/spec_helper.rb:5
/Users/brian/workspace/puppetlabs-strings/spec/spec_helper_acceptance.rb:1
/Users/brian/workspace/puppetlabs-strings/spec/spec_helper_acceptance.rb:1
/Users/brian/workspace/puppetlabs-strings/spec/acceptance/running_strings_yardoc.rb:1 …
```
=> (maint) Improve the error message returned when failing to request vms

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
Without this change, it is not possible to run beaker against solaris
hosts with --no-provision, which means for every test run the VMs must
be re-provisioned, which has a big impact on the length of time to be
able to run tests during development lifecycle.
For Solaris the 'rolemod' command is used, but this can only be run
successfully once, the second time it runs it fails because the root
user has already been changes from a role to a user.  This change adds a
check to ensure rolemod is only run if it is needed.
=> (BKR-789) enable --no-provision for Solaris 11 guests

acceptance/tests/base/dsl/platform_tag_confiner_test.rb, acceptance/tests/base/dsl/structure_test.rb, lib/beaker/dsl/structure.rb, spec/beaker/dsl/structure_spec.rb
Moving confine message stating that criteria match has been unsuccessful in finding a matching host, to the specific case logic.
This means that we can be more detailed in what exactly has failed to be found.
=> (BKR-688) Moving confine message(s) up a level

spec/beaker/dsl/structure_spec.rb
Changes to minitest 5.9 broke a single test that used assert_equal to
generate a minitest assertion; this change uses the simplest assertion
possible, so changes to minitest are less likely to break a spec test.
=> (maint) Change spec test to use simplest assertion

docs/README.md
This confusion isn't actually about the docs themselves. Both phrases "beaker-installation" and "how to install" link to the same document. But they are listed in the same TOC, which doesn't make much sense.
This PR is to clarify between the two entries and gain a little more consistency here.
=> (MAINT) clarifying between install docs

lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/host/windows/file.rb, lib/beaker/host_prebuilt_steps.rb, lib/beaker/hypervisor/vagrant.rb
Bitvise has largely been unable to function due to hard coded linux/cygwin commands, this merge request fixes bitvise ssh windows issues.
Additionally Vagrant has a regression bug where intermittent versions fail to forward ssh when os is windows. Reference: https://github.com/mitchellh/vagrant/issues/7202
=> (BKR-758) Fix Bitvise SSH issues and Various vagrant versions not forwarding ssh properly

lib/beaker/dsl/helpers/host_helpers.rb
Shell cannot accept a host, so update inline docs accordingly.
=> (maint) Fix documentation example for shell

Gemfile
This change allows for Beaker's CI to detect PR testing from beaker-pe
and pull in that branch for additional testing.
=> (BKR-813) Add support for beaker lib PR testing

lib/beaker/dsl/helpers/host_helpers.rb, spec/beaker/dsl/helpers/host_helpers_spec.rb
In commit f78c2db, we neglected to ensure that an environment passed in
through the options specified by #on overrides the environment specified
in the Beaker::Command object. This change ensures that #on checks for
the environment in its own options to override the command options.
=> (BKR-822) Ensure env options applied to bkr commands with #on

docs/Beaker-Libraries.md
beaker-library howto is tough to find from beaker docs. This change
links to it from the beaker-library list in docs
[skip ci]
=> (maint) link to beaker template from beaker library docs

lib/beaker/host.rb, spec/beaker/host_spec.rb
When determining the ip address of a machine, beaker normally ssh'd into
the box and would run a command that would return the ip configured on
that box. However, this doesn't work for several cloud hypervisors, as
the public ip of the box may not match the internally configured ip
address. This change allows for hypervisor specific logic to be executed
instead of sshing into the box. Specifically, this commit changes all
ec2 instances to use the public ip address instead of the private one.
=> (BKR-843) Use hypervisor specific logic for ip

lib/beaker/dsl/install_utils/windows_utils.rb, spec/beaker/dsl/install_utils/windows_utils_spec.rb
- Adds quotes around the "if exist path type path" command passed to
cmd.exe, which also requires that quotes around filenames have
their quoting escaped
=> (maint) Extra quoting for Windows versions.txt

docs/hypervisors/README.md
=> Changed link for lxc hypervisor

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
This commit expands platform support for the `remove_puppet_on` install
helper method to include `sles` and all `el` derivatives.
This allows hosts declared with a `hypervisor` of `none` on these
platforms to have puppet uninstalled as part of a pre-suite.
=> (BKR-856) Add el/sles support to remove_puppet_on

lib/beaker/options/parser.rb, spec/beaker/cli_spec.rb, spec/beaker/options/parser_spec.rb
If you provide bad beaker-hostgenerator input (such as `poobah-baily` in my example below), you'll get this output from running beaker with this change:
```
beaker --log-level trace --hosts poobah-baily --tests ../my_beaker_files/tests/smoke_simple.rb
Hosts file 'poobah-baily' does not exist.
Trying as beaker-hostgenerator input.
WARNING: Starting with beaker-hostgenerator 1.x platform strings for "el" hosts
will correspond to the actual linux distribution name. ie, the platform string
corresponding to a host specified as "centos4_64a" will be "centos-4-x86_64"
rather than "el-4-x86_64". It is recommended that you update your project's test
suites ASAP or be forced to do so when beaker-hostgenerator development moves on
to the 1.x series. We don't intend to backport features or platforms …
```
=> (MAINT) improved error output from beaker-hostgenerator workflow

beaker.gemspec
Currently beaker is pinning the hocon gem at a version less than 1.0
but beaker-pe requires hocon 1.0 or greater so we are essentially stuck
at an older version of beaker-answers.
This commit bumps the hocon gem in beaker to be at least 1.0 to allow us
to test with the latest beaker-answers.
=> (PE-16065) Bump hocon gem to get latest beaker-answers

lib/beaker/dsl/install_utils/aio_defaults.rb
In https://github.com/puppetlabs/beaker/pull/932 code was added to AIO to support "pure windows"/pswindows/bitvise directory paths. Unfortunately this hard coded the distmoduledir to C:\ProgramData\PuppetLabs\code\environments\production\modules causing many functions to utilize that directory path, this does not work very well when when the SUT test require different environments (or the node flows through different environments). 
This change modifies distmoduledir to C:\ProgramData\PuppetLabs\code\modules
=> (BKR-849) Change AIO distmoduledir to global module directory

docs/Creating-A-Test-Environment.md
All the particular hypervisor docs are now in
a sub directory.
=> Fix links to hypervisors

acceptance/tests/base/packages.rb
An update to the Windows2008r2 image template broke the packages test
because it tries to run installation from a folder that has restricted
permissions. This commit makes it so CI will skip testing packages on OSX;
it should be reverted when the install_package method is fixed.
=> (BKR-871) Don't test packages on Windows

lib/beaker/dsl.rb
Prior to this commit, there was a missing closing paren in the code
examples in the DSL documentation.
This commit adds the missing paren.
=> (maint) Add missing parenthesis in dsl.rb docs

lib/beaker/dsl/install_utils/module_utils.rb
Updated the filtering on PUPPET_MODULE_INSTALL_IGNORE to exclude .svn,
junit, pkg and example folders
Without this change, unnecessary files are copied to the SUT which slows down test execution time.  
The changes filters out build generated files as well, created when using puppetlabs_spec_helper.
=> BKR-874 PUPPET_MODULE_INSTALL_IGNORE

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
This commit fixes a bug where timesync causes beaker to error if the host has ntpd already running.
The fix is simply to use the -u option for ntpdate to use an alternate network port.
Tested new command on Redhat and Ubuntu.
Ran rake test:spec locally
=> (BKR-797) timesync helper should handle ntpd already running

acceptance/tests/base/packages_unix.rb
Because we are missing packages for Fedora for puppetserver, we should
skip them until they become available.
=> (BKR-869) Skip deploy_package_repo tests when Fedora

beaker.gemspec, lib/beaker/tasks/quick_start.rb, lib/beaker/tasks/rake_task.rb
For generating hosts file, test suite and running test (on vmpooler).
Needed to make beaker-hostgenerator a runtime dependency in order for gen_hosts task to work.
As it stands, I think it's useful to be able to generate default host file and test files for a new user. But not sure how useful the run task would be as they would probably need to edit the files before they kicked off a test run.
Not sure about the tasks as they stand. Some questions (@kevpl @tvpartytonight) :
Should we make the gen_hosts tasks configurable so a different host config string can be passed in?
Should we make the run task configurable so that it can be used to run different pre-suite/tests?
Or do we keep this as simple as possible, as a way to show the workflow to a new user? And address the other issues if we …
=> (BKR-859) Add rake quick start tasks

beaker.gemspec
This PR pins gems that are transitive dependencies that dropped ruby
1.9.3 support. This should be removed eventually, as these gems are not
actually needed by beaker itself, but by gems beaker relies on.
=> (maint) Pin gems that removed ruby 1.9.3 support

lib/beaker/shared/host_manager.rb, spec/beaker/shared/host_manager_spec.rb
Need to check if opts[:run_in_parallel] == true.
If it evaluates to [], it will go into the if statement as it stands.
=> (BKR-884) Fix issue in run_block_on

beaker.gemspec
The AWS SDK gem has had a backwards compatible major release.
However, in projects that want to use both v1 and v2 of the SDK gem, the .gemspec must refer to 'aws-sdk-v1' to satisfy Bundler dependency management.
=> (BKR-882) Explicitly refer to AWS SDK v1 gem

Rakefile, beaker.gemspec
These gems are not necessary for beaker itself, and they do not need to
be specified in the the gemspec.
=> (QENG-4068) Remove unnecessary gem documentation dependencies

acceptance/tests/puppet/stub_host.rb, lib/beaker/dsl/helpers/puppet_helpers.rb, spec/beaker/dsl/helpers/puppet_helpers_spec.rb
This commit adds an `aliases` parameter to the `stub_hosts_on`
and the `with_host_stubbed_on` to facilitate adding multiple host aliases when
stubbing hosts.
This commit also updates the `stub_forge_on` and `with_forge_stubbed_on`
methods to add the `puppet.com` and `puppetlabs.com` variants of `forge`
and `forgeapi` in order to support both domain names.
=> (BKR-847) Support puppet.com in forge stubs

acceptance/tests/install/from_file.rb, lib/beaker/dsl/install_utils/windows_utils.rb, lib/beaker/host/mac/pkg.rb
This commit adds a generic dmg installer to the OS X package facility.
This allows either a either a local file location or a URL to be specified
to install a dmg on an OS X host. It is based on the existing `install_dmg`
method, but requires the Volume location and package name to be specified by
the caller. These values cannot be introspected without making assumptions
about the packaging.
It also adds a generic msi installer as a helper. It is based on the
`install_msi_on` helper. The additional helper requirements make it a larger
effort to port to the Windows package facility which is not pursued in this
commit. The interface of the `generic_install_msi_on` method is the same as
the `install_msi_on`, it simply removes the validations that are puppet
specific.
=> (MAINT) add generic dmg and msi installers

acceptance/tests/install/from_file.rb
This commit confines the `acceptance/tests/install/from_file.rb`
test to Windows and OSX which are currently the only platforms supported
by the test.
=> (MAINT) confined file install acceptance to win/osx

lib/beaker/test_case.rb, spec/beaker/test_case_spec.rb
BKR-890 - Print failure message and stack trace inline when a test failure occurs
=> (BKR-890) Surface and provide more visibility into where failures occured

lib/beaker/host_prebuilt_steps.rb
This commit adds logic to the `set_etc_hosts` method to change the
preferred DNS resolution order on AIX platforms.
By default, AIX will first use external DNS to resolve a name even
if the name has an entry in the `/etc/hosts` file. This means that
an externally resolvable hostname cannot be overridden by a local
entry in `/etc/hosts` unless the resolution order is changed. The
logic added with this commit adds the configuration to give precedence
to local DNS resolution.
=> (BKR-894) AIX - prefer local DNS if hosts file changed

docs/how_to/ssh_agent_forwarding.md
I literally spent hours understanding that the `@option` / `option` hash in the code was coming from the `CONFIG` section of the hosts file…  Such a howto would have saved my day :-)
=> (MAINT) Document how to do ssh agent forwarding.

lib/beaker/dsl/helpers/tk_helpers.rb, spec/beaker/dsl/helpers/tk_helpers_spec.rb
`JSON.dump` ruins the formatting of JSON files, which can make TK config files difficult to read. This commit replaces `JSON.dump` with `JSON.pretty_generate` to preserve config file formatting and readability.
=> (MAINT) Use JSON.pretty_generate to create JSON output

lib/beaker/ssh_connection.rb
The previous behavior output this as a warning message, causing it to appear in red with the default configuration which is probably not desired since this is expected in normal conditions.
The new behavior use the same debug level to indicate the connection attempt and the connection terminaison.
=> (MAINT) Output informational message at debug level.

lib/beaker/host/unix/pkg.rb, lib/beaker/host_prebuilt_steps.rb
Prior to this commit Solaris 10 would blow up if pkgutil wasn't
installed. Solaris 11 was not verifying that curl/ntp were installed.
This commit adds logic to install pkgutil if it isn't found on
Solaris 11, as well as adding package checks for Solaris 11 so that
it actually verifies that ntp/curl are installed.
=> (PE-17093) Solaris 10/11 pkg/pkgutil fixes

lib/beaker/hypervisor/aws_sdk.rb, spec/beaker/hypervisor/aws_sdk_spec.rb
Prior to this change, provisioning in ec2 would set each host's hostname
to the `name` attribute of the host. This change removes that behavior
and sets each host's hostname to be the public facing `dns_name`
provided by ec2 to allow traffic from outside ec2 to route correctly to
that host.
=> (BKR-916) Use dns_name for ec2 hostnames

lib/beaker/hypervisor.rb, lib/beaker/hypervisor/vagrant_custom.rb, spec/beaker/hypervisor/vagrant_custom_spec.rb
* Gives the ability to specify users own Vagrantfile.
* Useful if there's a bug in beaker, you have a custom Vagrant provider missing from Beaker...
* or you just want to be super explicit about your Vagrantfile
=> (BKR-907) Add vagrant_custom hypervisor

docs/how_to/hypervisors/openstack.md, lib/beaker/hypervisor/openstack.rb, spec/beaker/hypervisor/openstack_spec.rb, spec/helpers.rb
Because Puppet has it's own security group that is not default but is necessary to connect to an openstack instance, I'd like to add a security group option to the hosts config file so that the user can specify security group(s) to add to an instance on creation.
This is just an initial commit. I'm not sure how to test or verify the work I've done, so any help in that area would be excellent!
=> (maint) Add security group option to openstack hypervisor initialization

docs/how_to/hypervisors/openstack.md, lib/beaker/hypervisor/openstack.rb, spec/beaker/hypervisor/openstack_spec.rb, spec/helpers.rb
This PR:
* Moves the logic of getting or allocating a floating IP to it's own function
* Adds allocation functionality for if no floating IPs are available
I realized that in my last PR, I bypassed the error handling for when no floating IPs are available. This puts it back in.
=> (QA-2599) Allocate IP if none is available

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb
Prior to this commit I attempted to use a variable that doesn't exist
`noask_directory`.
This commit uses the `opts[:copy_dir_external]` varible instead, which
should be provided by beaker, and default to `/root`
Added typo fix to @highb's PR here since I don't have write permissions to his fork.
=> (PE-17093) Fix noask directory path

lib/beaker/host.rb, lib/beaker/hypervisor/openstack.rb, spec/beaker/host_spec.rb, spec/beaker/hypervisor/openstack_spec.rb
Fixes in issue in Host.port_open? where an exception Errno::EHOSTUNREACH is
raised but not rescued.  Creates a wait_for_port wrapper around this function
to wait upon a specific port for a specific time.  Also allows the interval
between checks to be specified to prevent spamming the host.
=> (BKR-904) Provide A Way To Wait For A Host Reboot

docs/concepts/shared_options_for_executing_beaker_commands.md
This commit updates the reference to a document that exists.
=> (maint) Fix typo to how_to document

docs/tutorials/README.md
Before this, our docs pointed to the tutorials
folder, but that just listed a directory, ruining
the idea of leading someone "by the hand." This PR
adds an overview README doc, giving people context
for the other tutorial docs.
[skip ci]
=> (MAINT) add tutorial README

acceptance/tests/base/host/host_test.rb, lib/beaker/host/unix/exec.rb, spec/beaker/host_spec.rb
Previously the regular expression to add, get or clear an environment variable
were too loose, matching lines which were not intended e.g. `get_env_var("abc")`
would match `abc=123`, `xx_abc_xx=123` and `123=abc` however the intent of the
function would be to only match `abc=123` i.e. Get the env var called 'abc'.
This commit modifies the `add_env_var`, `get_env_var` and `clear_env_var` grep
statements to prefix `#{key}` with `^` and a trailing `=` to ensure that the
matches are as intended.  This commit also includes additional acceptance tests
for this behavior.
=> (BKR-914) Fix loose checking in add, get and clear env_var

lib/beaker/dsl/install_utils/windows_utils.rb, spec/beaker/dsl/install_utils/windows_utils_spec.rb
This commit adds two checks to make sure that after install our Windows agents
still have the appropriate registry value setting & location for
RememberedPuppetAgentStartupMode (which is Disabled) and that the service does
in fact have a startup type of Disabled. This is after a regression was
introduced in the MSI packaging which wrote these values to the wrong location
and then they were not retained/honored after upgrade.
The MSI flag for setting startup mode is PUPPET_AGENT_STARTUP_MODE, and it
accepts three values:
* Automatic
* Manual
* Disabled
Of these three, "Automatic" is the only on that does not correspond directly to
the equivalent value returned by `WMIC SERVICE` - for this case, `WMIC SERVICE`
returns "Auto" and not "Automatic. "Manual" and "Disabled" are both returned …
=> (PA-514) Ensure windows reg value & startup type

docs/how_to/upgrade_from_2_to_3.md
=> (maint) Mention ruby 1.9.3 dropped support

acceptance/pre_suite/pe/install.rb, lib/beaker.rb
This change pulls in beaker-pe if it is available in the ruby
$LOAD_PATH. This makes it so that project repos only have to specify
beaker-pe in their Gemfile, not require beaker-pe itself in their
test setup.
=> Require beaker-pe if available

lib/beaker/host/mac/exec.rb, lib/beaker/platform.rb
Add the osx 10.12 entry to the platform config, and update the
ssh_permit_user_environment function to also use /private/etc/sshd_config
instead of /etc/sshd_config for osx-10.12.
osx-10.11 and 10.12 both need that location to be updated (with the addition
of /private) in order for the ssh environment to work correctly.
=> (BKR-911) Add OSX Sierra (10.12) support

beaker.gemspec
In the release of beaker 3.0, we said that we gave up supporting
ruby 1.9, but we didn't actually stop anyone from using it. This
change will prevent anyone from using beaker 3.0 with any ruby
< 2.2.5
=> (BKR-948) require ruby >= 2.2.5

lib/beaker/hypervisor/vmpooler.rb
Prior this commit, if a user had an old token and attempted to run
beaker to request vms, it would claim that the requested hosts were not
available in the pooler when in reality their token was invalid and not
authorized to make the request. This commit updates that to check the
status code of the request and print the appropriate error message.
=> (maint) Improve beaker vmpooler error response

lib/beaker/host/freebsd/pkg.rb, lib/beaker/host_prebuilt_steps.rb, spec/beaker/host/freebsd/pkg_spec.rb
This PR enables beaker to install and query packages on new (>=9.3) and old (<9.3) versions of FreeBSD. The proposed code was used by me as [a workaround](https://github.com/ptomulik/puppet-portsng/blob/master/spec/patches/lib/beaker/host/freebsd/pkg.rb) in [ptomulik/puppet-portsng](https://github.com/ptomulik/puppet-portsng/) puppet module and worked for all FreeBSD versions between 9.0 and 11.0, where the older versions (9.0 .. 9.2) used the old pkg toolstack and newer (9.3 ... 11.0) the new pkgng suite. A similar patch was proposed for specinfra as  PR [specinfra/581](https://github.com/mizzy/specinfra/pull/581).
=> (BKR-942) let beaker use either old pkg or new pkgng tools on FreeBSD

acceptance/tests/base/dsl/helpers/hocon_helpers_test.rb, docs/how_to/use_hocon_helpers.md, lib/beaker/dsl/helpers.rb, lib/beaker/dsl/helpers/hocon_helpers.rb
In Everett, PE will be moving away from using the node classifier
to classify nodes, and instead relying on pe.conf HOCON files. This
change introduces basic CRUD style interactions with HOCON files
for beaker testing.
=> (BKR-928) add hocon DSL helpers

lib/beaker/hypervisor/vmpooler.rb
Before this commit it was not possible to tell via [vmfloaty](https://github.com/briancain/vmfloaty) or [vmpooler-bitbar](https://github.com/johnmccabe/vmpooler-bitbar/) what a particular vmpooler vm was being used for when created by beaker.
This commit adds tags with the name and roles for vmpooler vms, for example via vmpooler-bitbar:
=> (maint) add name and roles tags to vmpooler vms

lib/beaker/options/parser.rb, spec/beaker/options/parser_spec.rb
In previous versions (such as 2.14.1, which was previously
used to run our ec2 zombie killer), beaker could be run
without a hosts file argument. This would allow beaker test
logic to be run without needing to stand up SUTs. During the
time where beaker-hostgenerator support was added, this
ability was removed. This change allows us to run without
the hosts file argument, as was previously done.
=> (MAINT) Allow no hosts option to be passed

lib/beaker/hypervisor/aws_sdk.rb, spec/beaker/hypervisor/aws_sdk_spec.rb
With Tony's [check-in](https://github.com/puppetlabs/beaker/commit/a5bbdab25281745e7ee053ffd8bc01dae1180f69) the default hostnames of ec2 VMs went from whatever was configured in the beaker hosts file, to the DNS-name given by the Amazon ec2 service. Unfortunately, this broke the pe_acceptance_tests tooling on ec2, which is used for release scale testing.
This check-in makes the old behavior available again, but only if you set :use_beaker_hostnames: true in the beaker hosts file. In other words, this should NOT break any testing that required Tony's original check-in.
=> (BKR-965) Re-enable the prior way of setting hostnames but keep the new default

docs/how_to/hypervisors/aws.md
This PR updates the docs to reflect the PR at https://github.com/puppetlabs/beaker/pull/1268
and should not be merged until the above has been merged.
=> (BKR-965) DOC Update the docs for host naming

lib/beaker/options/command_line_parser.rb
In #1266, we added the ability to have the  CLI
argument be omitted for a beaker run. This was restoring
old behavior, but there was no guide on what values could
be passed. This change sets the CLI help text to explain
the possibilities to the user, clearing up the ways we
intend the  argument to work.
=> (MAINT) Update CLI hosts option help text

acceptance/tests/base/host/host_test.rb, lib/beaker/ssh_connection.rb, spec/beaker/ssh_connection_spec.rb
Previous to this commit, beaker scp errors would leave the ssh
connection in a dangling state because of Exceptions that would bubble
up without closing out the ssh connection. This change ensures that when
errors are raised, the #close method is called. While the exceptions are
swallowed, the #close methods called end up raising errors from the
state of the connection object, thus not requiring that the original
asserts be raised.
=> (BKR-971) Ensure scp errors close ssh connections

lib/beaker/hypervisor/openstack.rb, spec/beaker/hypervisor/openstack_spec.rb
Fixes a regression in 2.51.0 whereby the hostname was updated to be based upon the
server IP, and get a domain.  Random keypair generation is based upon this hostname
however OpenStack deems the period character unsafe, therefore this functionality
got broken.  This commit attaches both the hostname and fqdn to the host object.  To
maintain backwards compatibility all references to vmhostname now refer to vmfqdn.
Key generation now uses the safe vmhostname variable, and clean up uses vm.key_name
cached in the Fog Server object.
=> (BKR-949) Fix Keypair Generation on OpenStack

beaker.gemspec
- This version of net-ssh includes UTF-8 related fixes when commands or paths exceed 127 characters.
Unfortunately the author is discontinuing any releases in the 2.* or 3.* series, hasn't yet released any non-alpha or beta
4.* releases, and has versioned this last release in the 3 series with a beta1 name, so it must be referenced explicitly.
=> (BKR-40) Pin net-ssh gem to 3.3.0beta1

lib/beaker/hypervisor/openstack.rb, spec/beaker/hypervisor/openstack_spec.rb
Fixes a race where one instance would allocate a floating IP and while
creating the server other instances (e.g. parallel invokations in travis)
would try to use the allocated but unassociated address and fail in
all manner of ways.  This enforces aloocation of a new floating IP each
and every time.
=> (BKR-983) OpenStack Must Allocate New Floating IP

lib/beaker/host/mac/pkg.rb, lib/beaker/host/unix/pkg.rb, spec/beaker/host/mac_spec.rb
Doing work for 4be19a3, I found that
the OS X package info method uses the
option's :download_url parameter, but
doesn't require or assert that it exists.
Added an assertion to validate it's
existance since it's necessary.
=> (MAINT) assert on OSX pkg info requirement

lib/beaker/dsl/install_utils/foss_utils.rb
Clarifies the puppet_agent_version parameter.
Also pulls some value setting logic out of a loop based on
hosts iteration, since that it's required for the value setting itself.
=> (MAINT) clarify puppet_agent_version parameter

Gemfile.lock, beaker.gemspec
In order to keep ruby dependencies from breaking the last 2.x version of
beaker, we can add a Gemfile.lock file to the release so that all
versions are pinned exactly and ranged versions cannot introduce
failures to bundle install.
=> (BKR-976) Finalize 2.x dependencies

acceptance/tests/base/host/packages.rb, lib/beaker/host/windows/pkg.rb
- Newer Windows templates in vmpooler have been produced through a
Packer process, and install packages differently than earlier
templates based on how Cygwin was installed.
Two additional switches must now be passed for package installs to
succeed using Cygwins package manager.
See https://tickets.puppetlabs.com/browse/IMAGES-424 for more detail
This fixes a bug where `cmdline_args` passed to Cygwins setup*.exe
are injecetd into the wrong location.  When specify a -R, the
rootdir value must be passed next.  Previously, additional args
were injected in between the -R and the rootdir value.
=> (BKR-1010) Fix Cygwin install_package helper

lib/beaker/host.rb, lib/beaker/host/windows/exec.rb, spec/beaker/host/windows/exec_spec.rb, spec/beaker/host_spec.rb
When using `Windows::Exec::reboot`, the SSH connection is expected to
fail. However, it can take a long time to do so (greater than 30 minutes
in some cases). This should be faster, as we know the connection will
fail.
Add a new option to `exec`, `:reset_connection`, that immediately closes
the connection after sending a message. Use it when performing reboot on
a Windows host.
=> (BKR-1006) Close connection immediately when rebooting Windows

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
I was running into an issue when using the vagrant_custom hypervisor and not using any private_network with a known ip address (only the NAT interface, no hostonly). In all examples, I am using the virtualbox provider.
The first run with provisioning worked perfectly. If I ran it a second time without reprovisioning I would get an exception stating "Unable to determine ip for vagrant box #{hostname}". This was because only on reprovisioning does beaker attempt to parse out an ip address from the Vagrantfile.
I propose that instead of raising an exception, we just return nil for the ip address. As far as I can tell, beaker connects to the machines using the ssh config file generated from the set_ssh_config method. I compared the host.host_hash from a fresh run and a run without …
=> (BKR-1009) Don't fail when ip is unavailable in Vagrantfile

acceptance/tests/base/host/user_test.rb, lib/beaker/host/pswindows/user.rb, lib/beaker/host/windows/user.rb
- The existing mechanism is tightly coupled to English / ASCII output
and should instead use exit codes.
Fix both the PowerShell and CMD hosts.
Add a new acceptance test so that this can be validated on a
non-English Windows host (for instance Japanse Windows 2012R2
template win-2012r2-ja-x86_64)
=> (BKR-1008) Fix Windows user_get error detection

acceptance/tests/base/host/group_test.rb, acceptance/tests/base/host/user_test.rb, lib/beaker/host/pswindows/group.rb, lib/beaker/host/pswindows/user.rb, lib/beaker/host/windows/group.rb, lib/beaker/host/windows/user.rb
- The existing mechanism is tightly coupled to English / ASCII output
and should instead use exit codes.
Fix both the PowerShell and CMD hosts.
Add a new acceptance test so that this can be validated on a
non-English Windows host (for instance Japanse Windows 2012R2
template win-2012r2-ja-x86_64)
=> (BKR-1011) Fix Windows group_get error detection

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb
This commit adds support for RHEL variants to the
`puppet_agent_dev_package_info` method. Prior to this commit, if
this method was invoked with a host whose platform was in the `el`
family but did not equal `el`, an error would be raised that the
platform was unknown.
=> (BKR-1014) Add RHEL variants to puppet_agent_dev_package_info

beaker.gemspec
- aws-sdk-v1 transitively requires the `json` gem, which was added to
the Gemfile in 8c76afcce87cf7c23adaa6d7c76f00b7040a2e54
However, it doesn't appear that the `json` version for Beaker was
specified for any compelling reason, and can cause issues on Windows
systems when other gems requiring `json` are added to a Gemfile that
also references Beaker, for instance with puppet modules like
Registry or ACL.
Even in Puppet modules, where `bundle install --without system_tests`
is specified to prevent Beaker installation, if other gems require the
`json` gem as a dependency, Bundler looks at the requirements of the
`beaker` gem and its dependencies when determining which `json` gem
version satisfies the requirement.
This can lead to Bundler attempting to install a newer `json` gem
than the …
=> (BKR-987) Remove explicit json gem dependency

lib/beaker/dsl/helpers/puppet_helpers.rb, spec/beaker/dsl/helpers/puppet_helpers_spec.rb
This commit modifies the implementation of the `stub_forge_on` and
`with_forge_stubbed_on` methods to resolve the `forge_host` from
the host on which the targeted `forge_host` will be accessed.
This is done to address the case where the SUT and the Beaker
runner have different resolution of the given `forge_host` name.
=> (BKR-1016) resolve stub forge from SUT

lib/beaker/host_prebuilt_steps.rb, lib/beaker/hypervisor/vagrant.rb, spec/beaker/host_prebuilt_steps_spec.rb, spec/beaker/hypervisor/vagrant_spec.rb
The new Windows vagrant boxes built by John have already root-level
ssh access through the vagrant user. They don't need any of the ssh
munging of the vagrant hypervisor.
The other changes are to fix up some commands that would not work on
cygwin/windows.
=> (BKR-1015) Improve vagrant/windows interactions

docs/how_to/install_puppet.md
=> (MAINT) add install puppet doc

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/xcopy.mspx?mfr=true
> /i : If Source is a directory or contains wildcards and Destination does not exist, xcopy assumes destination specifies a directory name and creates a new directory. Then, xcopy copies all specified files into the new directory. By default, xcopy prompts you to specify whether Destination is a file or a directory.
> 
> /y : Suppresses prompting to confirm that you want to overwrite an existing destination file.
=> (BKR-1018) copy_ssh_to_root not working on windows

beaker.gemspec
The documentation generation is generating warnings with the definition
for #run_block_on not working. Pinning for now until we find a better
solution.
=> (BKR-1028) Pin yard to below 0.9.6

acceptance/fixtures/files/sles-11-x86_64.repo, acceptance/fixtures/files/sles-11-x86_64.repo.txt, acceptance/fixtures/files/sles-12-x86_64.repo.txt, acceptance/fixtures/package/deb/pl-puppetserver-latest-xenial.list, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-fedora-24-x86_64.repo, acceptance/fixtures/package/rpm/pl-puppetserver-latest-repos-pe-sles-12-x86_64.repo, acceptance/tests/base/dsl/helpers/host_helpers/deploy_package_repo_test.rb, acceptance/tests/base/host/packages.rb, acceptance/tests/base/host/packages_unix.rb
These changes update the base acceptance tests to match our currently
supported systems. Notably, it adds back in SLES testing, adds xenial
support for package testing, and adds fedora back into the mix as well.
=> (BKR-940) update base test configuration

lib/beaker/platform.rb
This changes adds support for Debian 9 "Stretch", Ubuntu 16.10
"Yakkety", and Ubuntu 17.04 "Zesty".
=> (BKR-1037) Add support for Zesty, Yakkety, and Stretch

beaker.gemspec, lib/beaker/dsl/helpers.rb, lib/beaker/dsl/helpers/facter_helpers.rb, spec/beaker/dsl/helpers/facter_helpers_spec.rb
This reverts commit 4d0e29fe1c7dc842c171f89f2acf6c74cba4ed42, reversing
changes made to 59cfccedf25a4cdce6296fe010ee22bba07e5855.
In our documentation, we make references to only utilizing elements of
the the DSL directly, instead of using them as a lump sum in TestCase.
During a major version, these paths should never change.
=> (BKR-1047) Don't change module paths for the DSL

lib/beaker/dsl/install_utils/foss_utils.rb, lib/beaker/host/unix/pkg.rb
To avoid unnecessarily expanding our build times, our initial support
for AIX 7.2 is through the existing 7.1 package. This will be replaced
with a single unified AIX build in the Agent 2.0 timeframe, but for now
we need to add a little bit of special-case logic to handle 7.2 with
existing packages.
=> (BKR-937) Add support for installing AIX 7 agent on 7.2

acceptance/tests/base/host/host_test.rb, beaker.gemspec
Previous to this commit, we pinned net-ssh for fixes related to
UTF-8. This had the unfortunate side effect of breaking "gem install
beaker", as a Gem::DependencyError prevented installation because Gem
couldn't tell that version "3.3.0.beta1" met the dependency for "=>
2.6.5" for net-scp.. Now that version 4.0 has been released, we should
move the pin to that version so that `gem install beaker` can happen
successfully from rubygems.
=> (BKR-995) Update requirement for net-ssh

lib/beaker/hypervisor/aws_sdk.rb, spec/beaker/hypervisor/aws_sdk_spec.rb
The kb.exists? check fails intermittently; it one of the failures, manual
inspection shows that the key pair was in fact created. This heavily implies
that there's a race at work; where the key pair doesn't show as existing until
some time after the initial creation.
Add a retry loop around the kb.exists? check to attempt to work around this
issue.
=> (BKR-1051) Add retry loop for aws key check

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
This fixes enable_root_login for osx 10.11 and 10.12 where the wrong ssh config file was being used.
=> Fix for enable_root_login on OSX 10.11 & 10.12

lib/beaker/dsl/helpers/puppet_helpers.rb, spec/beaker/dsl/helpers/puppet_helpers_spec.rb
This commit changes the implementation of the
`sleep_until_puppetdb_started` helper method to query the PuppetDB
status endpoint to verify that the PDB web services are available.
=> (BKR-1046) Use pdb status for started validation

lib/beaker/hypervisor/vagrant_libvirt.rb, spec/beaker/hypervisor/vagrant_libvirt_spec.rb
The libvirt provider expects a mac address with colons. This change
updates the libvirt class to generate a random mac address with colons
so libvirt can configure the network correctly.
=> (BKR-917) libvirt requires a correctly formatted mac

docs/how_to/preserve_hosts.md
Prior to this commit we were linking to the `docs/topics` directory, this has been replaced by the `docs/concepts` directory.
This commit fixes the remaining references to the obsolete directory.
=> (maint) fix references to files under concepts

docs/how_to/hypervisors/openstack.md, lib/beaker/hypervisor/openstack.rb, spec/beaker/hypervisor/openstack_spec.rb
Fog defaults to the V2 API on clouds that support it, but the parameters
have changed, in particular `display_name` becomes `name`.  This checks
the cinder client type and uses the old value for V1 and the new one for
newer versions.
=> (BKR-982) OpenStack Cinder V2

Rakefile, acceptance/config/subcommands/acceptance-options.rb, acceptance/pre_suite/README.md, acceptance/pre_suite/subcommands/05_install_ruby.rb, acceptance/pre_suite/subcommands/08_install_beaker.rb, acceptance/tests/subcommands/init.rb
This PR adds in acceptance testing for beaker subcommands, using beaker
to install ruby and configure beaker on a SUT. The tests can be run
using rake with `rake test:subcommands` defined in the Rakefile at the
root of the repo.
The testing jenkins jobs that will run this rake task is [here](https://jenkins-beaker.delivery.puppetlabs.net/job/qe_beaker_intn-sys_beaker-acceptance-subcommands-vpool/). #1323 is required for merge before testing will pass for this build, as `gem install beaker` needs to function for this pre-suite to work.
=> (BKR-966) Add acceptance tests fo subcommands

lib/beaker/dsl/install_utils/foss_utils.rb, spec/beaker/dsl/install_utils/foss_utils_spec.rb
EL and Fedora systems were not installing the pc1 version of Puppet
when :type = aio. This ensures that the case is properly addressed.
BKR-931 #close
=> (BKR-931) Ensure that :type = 'aio' works in EL

lib/beaker/dsl/helpers/puppet_helpers.rb, spec/beaker/dsl/helpers/puppet_helpers_spec.rb
This commit adds logic based on `pe_ver` to use the PuppetDB `version`
API endpoint when the version includes PuppetDB version less than 4.0
which do not include the `status` API endpoint.
Prior to this commit, the status check on PE versions less than 2016.1.0
would fail because the `status` endpoint was not available.
=> (BKR-1046) Use version for pdb status in legacy

beaker.gemspec, lib/beaker/dsl/helpers/puppet_helpers.rb, lib/beaker/dsl/helpers/tk_helpers.rb
This fixes calls to the IniFile constructor to reflect the changed api in inifile 3.0.0 and bumps the dependency in beaker.gemspec.
=> (BKR-230) Update inifile gem dependency

docs/how_to/hypervisors/ec2.md
Without the user option beaker fails to login.
```
Please login as the user "ec2-user" rather than the user "root".
```
Setting the user triggers sanitizing of sshd_config and
authorized_keys.
=> (BKR-1052) Document user config option for ec2 hypervisor

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
When using `$PATH`, quote it to accomodate spaces in file paths. This is
common on Windows systems, and causes the command to fail.
=> (BKR-1066) Quote PATH to allow for spaces

lib/beaker/host/unix/exec.rb, spec/beaker/host/cisco_spec.rb, spec/beaker/host/unix/exec_spec.rb
This commit fixes an issue where the `environment_string` method of a
host unconditionally upper-cased the keys of the environment variables
of a command
=> (BKR-1035) Environment variable keys always get upper-cased

docs/tutorials/installation.md
[skip ci]
This PR documents https://github.com/puppetlabs/beaker/pull/1329,
and should be merged at the same time as that one is, so that the
change is described as soon as it goes in.
@puppetlabs/beaker, @tvpartytonight what do you think?
I originally thought this requirement would be mentioned in other
places, but I'm having trouble finding any. Am I missing some?
=> (BKR-1049) update ruby version doc

beaker.gemspec
PE and puppet-agent currently shipped with 2.1.9
Oldest supported PE release ships with 2.1.8
https://puppet.com/misc/puppet-enterprise-lifecycle
This is to keep beaker aligned with oldest supported PE release and
current puppet-agent vendored ruby.
=> (BKR-1049) Updating require to align with oldest supported PE version

lib/beaker/hypervisor/openstack.rb
The openstack hypervisor previously distinguished between fqdn and
hostname. However, nothing else in Beaker uses the fqdn, and beaker-pe
appears to use fqdn to identify the node. Report the fqdn as the host's
hostname.
=> (BKR-1071) Return fqdn as hostname

lib/beaker/subcommand.rb
This PR adds in the ability to accept and pass through options from a subcommand
to a Beaker::CLI object. Prior to this change, subcommands could not configure
beaker execution; this PR opens up virtually every option.
=> (BKR-1083) Pass beaker run options through from subcommands

lib/beaker/host/unix/exec.rb, spec/beaker/host/cisco_spec.rb, spec/beaker/host/unix/exec_spec.rb
Original implementation of BKR-1035 uses just
the capitalization given to set environment
variables. This change sets the given env var
as well as the capitalized version, so that
we're backward compatible until the next major
release
/cc @joshcooper, @puppetlabs/beaker
=> (BKR-1035) add old env var behavior

acceptance/tests/subcommands/provision.rb, bin/beaker, lib/beaker/cli.rb, lib/beaker/subcommands/subcommand_util.rb, spec/beaker/cli_spec.rb, spec/beaker/subcommand/subcommand_util_spec.rb
Prior to this commit, a Beaker::CLI object would do all options parsing
during initialization; now that parsing is needed by subcommands, we
should pull the parsing from initialization and call it after the object
has been instantiated.
=> (BKR-1075) Remove parsing from CLI intialize

acceptance/tests/subcommands/init.rb, acceptance/tests/subcommands/provision.rb, lib/beaker/cli.rb, lib/beaker/options.rb, lib/beaker/options/parser.rb, lib/beaker/options/subcommand_options_file_parser.rb, lib/beaker/subcommand.rb, lib/beaker/subcommands/subcommand_util.rb, spec/beaker/cli_spec.rb, spec/beaker/options/parser_spec.rb, spec/beaker/options/subcommand_options_parser_spec.rb, spec/beaker/subcommand_spec.rb
This changes beaker init to focus on setting up a repository for
beaker subcommands, rather than focusing in on generating host files
themselves. This also adds the functionality to create files that
contain the configured options; that is, all options that are not
presets after beaker parses its OptionsHash.
=> (BKR-1076) Refactor beaker init and provision

acceptance/tests/subcommands/exec.rb, bin/beaker, lib/beaker/cli.rb, lib/beaker/subcommand.rb, spec/beaker/subcommand_spec.rb
These changes introduce new subcommand functionality for beaker; the
exec subcommand takes a file, directory, or beaker suite name and
launches beaker to test that resource specifically. If no resource is
specified, it reads in default configuration that should already be set
up by previous subcommands.
=> (BKR-1004) beaker exec implementation

lib/beaker/hypervisor/openstack.rb, spec/beaker/hypervisor/openstack_spec.rb
Primary change is to add in optional user and project domain names for authentication
against a Keystone V3 endpoint.  The secondary change is to tidy up how keystone
credentials are handled as there was a whole bunch of duplication.  If there is any
concern around the disappearing conditional protecting the region selection worry not
as Fog checks for nil before populating the authentication request body.
=> (BKR-1092) Keystone V3 Support

docs/how_to/hypervisors/vsphere.md, lib/beaker/hypervisor/vcloud.rb, lib/beaker/hypervisor/vsphere_helper.rb, spec/beaker/hypervisor/vcloud_spec.rb, spec/beaker/hypervisor/vsphere_helper_spec.rb, spec/mock_vsphere.rb, spec/mock_vsphere_helper.rb
Prior to this commit you couldn't specify the datacenter to search for a
given folder.  The `find_datacenter` method will return the first found
datacenter, and in the case that you have linked vcenters this falls
apart.  This commit adds the ability for `datacenter` to be included in
@options.  Related, folder search now respects datacenter as well as
uses the traverse method.  Prior to this commit some folder searches
were not possible (for example a base level because it didn't contain a
`/` which was being split on).
Other minor updates; docs updated and template can be provided as ENV var.
=> (BKR-1091) vCloud datacenter selection support

lib/beaker/hypervisor/openstack.rb, spec/beaker/hypervisor/openstack_spec.rb
Firstly this fixes the rspec test that doesn't work, shame on me.  Secondly it
ensures only the hostname part of the host's FQDN is used in keypair generation,
as the FQDN includes periods and is illegal according to Nova.
=> (BKR-1093) Fix Nova Keypair Generation

acceptance/pre_suite/puppet_git/install.rb
- When Ruby < 2.0.0, Puppet will issue warnings.  This was changed
in 2015 in the Puppet repository pre-suite, but looks to have
never been changed in Beaker.
https://github.com/puppetlabs/puppet/commit/e7f0cef0d50d7ded9659c7c8a81b0f6ea3aeca90
=> (maint) Ruby 2.1 in Windows git acceptance tests

acceptance/tests/base/external_resources_test.rb, lib/beaker/host_prebuilt_steps.rb, lib/beaker/options/presets.rb, spec/beaker/host_prebuilt_steps_spec.rb
EPEL5 has recently been moved to [archives](http://dl.fedoraproject.org/pub/epel/5/README).
This PR allows beaker to install from the archives, so that EL5 users can continue using EPEL.
@puppetlabs/beaker please review, automated testing should be starting soon.
=> (BKR-1102) install EPEL5 from archives

docs/how_to/hypervisors/vmpooler.md, lib/beaker/hypervisor/vmpooler.rb, spec/beaker/hypervisor/vmpooler_spec.rb
In order to set up a test environment for Red Hat Satellite, we need a
disk that's larger than the default vmpooler allotment (about 5 GB free
vs the 1.5GB that are free on a redhat host after all is said and done).
This adds a step to the provision function in the vmpooler hypervisor to
add a disk of x size to any host in the host configuration file. It is
then up to the tests to partition, mount, expand, or whatever they
decide to do with it.
=> (MODULES-4594) vmpooler hypervisor: add disks

docs/how_to/hypervisors/vmpooler.md, docs/how_to/hypervisors/vsphere.md
[skip ci]
@genebean, @joel-m-allen, I think one of you were talking about needing the SSH doc for vmpooler hosts. Is that correct?
=> (MAINT) add SSH setup link to vmpooler doc

docs/how_to/hypervisors/openstack.md, lib/beaker/hypervisor/openstack.rb, lib/beaker/options/presets.rb, spec/beaker/hypervisor/openstack_spec.rb
Prior to this commit beaker openstack support assumed that the
`volumes` service was provisioned.  This service is not always
available in an Openstack deployment.  This commit gives you the
option to disable that functionality.  If you do not disable it
on an instance that does not publish this functionality, even if
you don't configure the volumes setting in `CONFIG`, beaker runs
will fail.
=> (BKR-954) Add Ability to Disable Openstack Volume Management

lib/beaker/hypervisor/docker.rb, spec/beaker/hypervisor/docker_spec.rb
This patch adds `UseDNS no` to the sshd configuration added to Docker
containers. This prevents SSH connections from triggering revers DNS lookups
which can take up to 30 seconds to time out per connection. Disabling this
behavior cut a simple beaker-rspec "hello world" from 14 minutes to 12 seconds
on the centos:centos7 image.
=> Disable reverse DNS on Docker containers

lib/beaker/tasks/quick_start.rb
`rake beaker_quickstart:gen_hosts[hypervisor]` commands create a config file in `.beaker/acceptance/config/` directory and while the `rake beaker_quickstart:run_test[hypervisor]` is looking for the config file at `acceptance/config/`.
Changed the default directory where the config file is created to match the one used by the test command.
=> (BKR-1112) Change path for host file created by quickstart

CONTRIBUTING.md
This commit replaces the stale link to the old puppet wiki with a link to the
contributor guidelines.
=> (maint) Update contributing resource links

lib/beaker/test_suite.rb, spec/beaker/test_suite_spec.rb
Spec test breaking [here](https://github.com/puppetlabs/beaker/blob/master/spec/beaker/test_suite_spec.rb#L247)
`summary_logger` is the instance that logs the summary to terminal and the file.
`print_test_result` was passing the test_cases that failed to be notified using `@logger` instance [here](https://github.com/puppetlabs/beaker/blob/master/lib/beaker/test_suite.rb#L155)
I changed it to return the string and then am notifying it using the `summary_logger` instance.
=> (BKR-1124) Pass info text to summary logger to print on file

acceptance/tests/subcommands/init.rb, acceptance/tests/subcommands/provision.rb, lib/beaker/subcommand.rb, spec/beaker/subcommand_spec.rb
Removed hosts as a Thor class_option so it cannot be used by all subcommands. It is restricted to be used only with init command. Hosts is added as Thor method_option with init. Changed spec and acceptance tests accordingly.
=> (BKR-1096) Block hosts flag with provision subcommand

lib/beaker/options/parser.rb, lib/beaker/options/subcommand_options_file_parser.rb, spec/beaker/options/parser_spec.rb, spec/beaker/options/subcommand_options_parser_spec.rb
This patch changed options priority to read options from $HOME/.beaker/subcommands_options.yaml with the lowest priority after the presets.
Added respective spec tests and modified others to fit this in the priority chain. Please note that as the priority hierarchy is changing there are some places in the module and their spec files that require modification in order to fit this in.
The new options priority now (from highest to lowest):
1. ENV variables
2. ARGV variables
3. 'CONFIG' section of hosts file
4. Options file
5. Subcommand options
6. Subcommand options file from home directory (this patch)
7. Presets
PS - Also, there was an empty file (`lib/beaker/options/homedir_options_file_parser.rb`) merged from my poor github management that is being deleted here :(
=> (BKR-994) Read subcommands options from home directory

lib/beaker/ssh_connection.rb, spec/beaker/ssh_connection_spec.rb
Some hosts' IP address are changed on reboot. Connecting with IP first would fail and then it will try connecting with vmhostname (DNS) and this process takes time because of timeouts on retries.
This patch will try to connect with vmhostname (DNS) first and then attempt the same with IP address on failure.
=> (BKR-834) Connect to host first with DNS name and then IP address

lib/beaker/hypervisor/docker.rb, spec/beaker/hypervisor/docker_spec.rb
Currently beaker acceptance tests will fail if executed behind a proxy.
By exposing the buildargs build parameter, it can be configured via ENV
DOCKER_BUILDARGS, or per host docker_buildargs
=> BKR-1114: Added buildargs for Docker::Image::build invocation

lib/beaker/subcommand.rb
When the beaker run options were defined, those listed as deprecated
were left out; in order to have parity with the current beaker
functionality, those should have been included.
=> (maint) Add in beaker run options listed as deprecated

lib/beaker/hypervisor/aws_sdk.rb
The aws_sdk hypervisor overrides the hostname to the public fqdn of the
vm so that puppet initializes with a cert matching it's public fqdn.
This allows agents to reach the master server, for example.
However these changes, on an Amazon Linux vm, are not preserved on
reboot. The host comes back with its hostname reset to the internal fqdn
(based on its private ip). This was causing a failure in PE
acceptance tests which expected the current facter fqdn output to
match the node's certname
Amazon Linux requires updating /etc/sysconfig/network to preserve
hostname changes across reboots.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-hostname.html
Also note that without an elastic ip set, while this will preserve the
hostname across a full shutdown/startup of the vm (as opposed to a …
=> (RE-7005) Preserve hostname on amazon linux on reboots

acceptance/tests/base/dsl/install_utils/clone_git_repo_on_test.rb
On Solaris 10, git package installation poisons curl and libssl.
Tried installing git using the same command beaker uses on a fresh vmpooler
Solaris 10 instance and it is producing the same error.
=> (BKR-1153) Confine solaris 10 from git clone test

lib/beaker/command.rb
We have found that the prepend commands for Cisco need to
come before the environment variables are set.
=> (BKR-1154) place prepend cmds before env vars for Cisco

lib/beaker/hypervisor/vagrant.rb, spec/beaker/hypervisor/vagrant_spec.rb
I'm not sure what the correct solution is here. In one case if beaker generates an invalid Vagrantfile then beaker will remain stuck without a way to get unstuck unless you manually go find the Vagrantfile and delete it.
In another case if the destroy fails to destroy an existing VM and the original Vagrantfile is deleted the user might be in a very bad state where there's a VM but Vagrant will not work with that existing VM unless the Vagrantfile is restored. I'm not sure what the chances of this actually happening.
Another solution might be to try to destroy then raise a custom exception to let the user know about these 2 states and extend beaker's cleanup rake task to clear the Vagrantfile. This moves the decision from here to the user's judgment.
Let me know what the best choice is …
=> Issue where beaker gets stuck when an invalid Vagrantfile had been generated

lib/beaker/hypervisor/aws_sdk.rb, spec/beaker/hypervisor/aws_sdk_spec.rb
The private_key() method was previously wrong. It used the last key
found in a loop, but did not verify that both the public and private key
exists for the chosen key before continuing. This meant that the ssh key
specified in the hosts file was ignored.
=> (BKR-437) Correctly detect public/private keys

lib/beaker/host.rb, lib/beaker/hypervisor.rb, lib/beaker/ssh_connection.rb, spec/beaker/hypervisor/hypervisor_spec.rb, spec/beaker/ssh_connection_spec.rb
This patch adds a new API method for hypervisors called connections_preference.
Hypervisor authors can overwrite this method to return an array of SSH
connection method preference of their choice when that hypervisor is used. This
option is then added to host_hash.
In host.rb file, we are sending ssh_connection.rb file an object of
:ssh_connection_pereference as an option. And we loop through each of the
element of the array in connect method of ssh_connection file.
The overall idea here is to create an API endpoint for hypervisor authors to set
their connection preference. As of now we dont want end user to set this in
their hosts config as there are no use case for it.
=> (BKR-1155) Allow configurable ssh connection preference

lib/beaker/host/windows/exec.rb, lib/beaker/host/windows/pkg.rb, lib/beaker/host_prebuilt_steps.rb, spec/beaker/dsl/install_utils/windows_utils_spec.rb, spec/beaker/host/windows/exec_spec.rb, spec/beaker/host/windows/pkg_spec.rb, spec/beaker/host_prebuilt_steps_spec.rb, spec/beaker/host_spec.rb
Previous to this commit, beaker would ensure that the cygwin executable
was available prior to package installation and download the executable
if it was not found. Later versions of cygwin fixed a flaw in permissions
for the executable, which broke the way beaker ensured and downloaded
the cygwin executable.
This change removes the notion of checking for cygwin at all. Rather
than conflate the installation of cygwin with package installation,
beaker should separate those concerns. Cygwin should be downloaded and
installed separately from package installation, or handled at the image 
level for the VM used.
Also included in this PR is an optimization for determining the the
architecture of the host; rather than spend time introspecting the
system, a host should just examine its own …
=> (BKR-871) Remove cygwin installation from package installation

acceptance/tests/base/dsl/helpers/host_helpers/archive_file_from_test.rb, beaker.gemspec, lib/beaker/dsl/helpers/host_helpers.rb
minitar 0.5.4 has a security issue in some code beaker doesn't use. Still,
updating will avoid this to be flagged on security scans.
=> (BKR-1163) update minitar to newest version

lib/beaker/host/unix/pkg.rb
When enabling repos on sles, zypper doesn't seem to acknowledge the
gpgkey entry in the repo file. Generally this will cause yum to auto
import the specified gpg key, and everything is hunky dory. With zypper,
it fetches the gpg key from the repo itself (found in
repodata/repomd.xml.key). This will allow zypper to install the package
and verify the key without failing, assuming the key provided in the
repo is the correct key.
=> (CPR-439) auto import gpg keys with zypper

beaker.gemspec, lib/beaker/dsl/structure.rb, lib/beaker/options/command_line_parser.rb, lib/beaker/subcommand.rb
Adds a --debug-errors option. When used, beaker will drop the runner into a pry console if/when a test fails or errors.
This is intended for the beaker run subcommand.
=> (BKR-1084) Add --debug-errors option to enter pry on a test failing

CONTRIBUTING.md
The CLA bot doesn't run on Beaker. According to internal conversation,
this is not a core requirement.
This commit removes mention of it from the CONTRIBUTING.md doc
=> (BKR-1206) Remove mention of the CLA bot

lib/beaker/dsl/structure.rb, lib/beaker/options/command_line_parser.rb, lib/beaker/subcommand.rb, spec/beaker/dsl/structure_spec.rb
Adds an option --exec-manual-tests
adds manual_tests. This allows use to do some automated setup for manual
test cases, but also skips them when run in CI
adds manual_step. This allows us to pass or fail a test after prompting
the tester
=> (BKR-1132) adds concept of manual_test and manual_step

CHANGELOG.md
We decided that in order to keep some idea of
a link to the changes that went into a release,
we would have the compare links present for each
release & stop including MAINT changes in the
CHANGELOG. This commit changes the format &
adds in a missed CHANGELOG entry from
BKR-1132 (submitted in PR #1444)
[skip ci]
=> (MAINT) fix CHANGELOG format

CHANGELOG.md, acceptance/lib/beaker/acceptance/install_utils.rb, lib/beaker/host/unix/exec.rb, lib/beaker/host/unix/pkg.rb, lib/beaker/host_prebuilt_steps.rb, lib/beaker/perf.rb, lib/beaker/platform.rb, spec/beaker/host_prebuilt_steps_spec.rb, spec/helpers.rb
We have converted two pipelines that require AWS resources to use ABS.  The pipelines previously used redhat as a platform when calling beaker.  Now that they will use ABS to acquire resources, the platform will be amazon which beaker did not yet support.
=> (QENG-5106) Update Beaker to support amazon as a platform

CHANGELOG.md
Note that a previously added changelog had
to be updated due to formatting & placement
issues
[skip ci]
=> (MAINT) update changelog for 3.28.0 release

acceptance/pre_suite/subcommands/05_install_ruby.rb
When a new VM is checked out from the vmpooler, bundler is already installed.
This bundler installation causes a conflict when the beaker acceptance tests
attempt to install bundler, which in turn, causes the acceptance tests to fail.
This change adds a --force flag to the bundler install, ignoring the conflict
=> (maint) Update the Ruby install of the pre-suite to force install bundler

lib/beaker/options/presets.rb
@tvpartytonight Added to presets to read from fog credentials in order to disable in beaker-aws
=> Adding default to read fog credentials

beaker.gemspec
This is needed for CI.Next support as some of the beaker acceptance
tests will be using always-be-scheduling. The beaker dependency in
beaker-abs has been removed as of 0.4.0, resolving the circular dependency
issue.
=> (maint) Add beaker-abs to optional hypervisors on bundle install

lib/beaker/cli.rb, spec/beaker/cli_spec.rb
This patch flips the logic that writes out the hosts_preserved.yml over from
using Beaker::Host#reachable_name to Beaker::Host#hostname. The reachable_name
method prefers to return a bare IP address if one is in use --- this makes it
unsuitable for identifying hosts from providers like Docker that put many SUTs
behind a single IP address using different SSH ports.
=> (BKR-1263) Preserve hosts using hostname

lib/beaker/cli.rb, lib/beaker/options/parser.rb, spec/beaker/cli_spec.rb, spec/beaker/options/parser_spec.rb
If .beaker.yml is present in the current working directory, then load
the project's options. The overall precedence from lowest to highest is:
defaults
.beaker.yml
~/.beaker/subcommand_options.yaml
./beaker/subcommand_options.yaml
etc
The project options (.beaker.yml) are essentially project defaults, so
they come after beaker defaults and before the subcommand options.
It is also possible for the project options to specify the options_file
to load so that it doesn't need to be specified on the command line.
Note this fixes a spec test that was stubbing part of the parse_args
method that it was trying to test.
=> (BKR-1268) Load project options from .beaker.yml

lib/beaker/dsl/structure.rb, lib/beaker/host.rb, lib/beaker/logger.rb, spec/beaker/dsl/structure_spec.rb, spec/beaker/host_spec.rb, spec/beaker/logger_spec.rb
Add `with_indent` method which indents the log for the duration of the
block. Use `ensure` so the indent level is always balanced, even if the
block raises an exception, e.g. due to skip_test.
Deprecate `step_in` and `step_out` since they can leave the indentation
unbalanced.
=> (BKR-1169) Ensure indentation is balanced

docs/concepts/argument_processing_and_precedence.md, docs/how_to/use_user_password_authentication.md, lib/beaker/options/presets.rb, spec/beaker/options/parser_spec.rb
Prior to this commit every time beaker made an SSH connection, it would
give a deprecation warning for the use of the `paranoid` setting, which
has been deprecated in favor of `verify_host_key`.
This commit removes all use of the `paranoid` setting in favor of
`verify_host_key`.
Example fixed output:
```
➜  frankenbuilder git:(master) ✗ BEAKER_VERSION="file:///s/beaker" ./frankenbuilder -v 2018.1 --install
Loading configs from ./.frankenbuilder
Cleaning /tmp/frankenmodules...
Done.
Using local copy of PE puppet-enterprise-2018.1.0-rc7-21-gc66e074-el-7-x86_64.tar
Extracting /s/frankenbuilder/tarballs/puppet-enterprise-2018.1.0-rc7-21-gc66e074-el-7-x86_64.tar...
PE 2018.1.0-rc7-21-gc66e074 has been extracted to /s/frankenbuilder/frankenbuild (2018.1.0-rc7-21-gc66e074)
:answers: …
```
=> (BKR-1384) Clean up ssh paranoid setting deprecation warnings

acceptance/scripts/all_but_host_test.sh
This change adds a simple script that will get all `acceptance/tests/base`
files except `host_test.rb` & format them to be passed to the `--tests`
CLI parameter.
The reason we want this is that for our nightly master test on ubuntu
during the VM re-use test, the ssh `port_open?` method continues to
fail when it clearly isn't the case, since commands can be executed
over SSH in every other step.
This is not something that we could reproduce locally. Since that's the
case & this issue hasn't been reported elsewhere (that we're aware of),
it seems to be irrelevant to us. Since that's the case, I've made this
script to help us avoid running it in the re-use case.
Created [this job](https://jenkins-beaker.delivery.puppetlabs.net/job/qe_beaker_intn-sys_beaker-acceptance-reuse-vpool-debug-beaker- …
=> (MAINT) add host_test-avoid script for vpool re-use test

lib/beaker/subcommand.rb
=> (maint) fix missing colon for subcommand option

lib/beaker/host/unix/exec.rb
Previous to this commit, the sles SSH restart command was not fully
qualified. This lead to the command not being found if the user did not
have `/usr/sbin` in their path for some reason as we could not set the
path until after we modify the ssh service to permit user environments
(which requires a ssh restart).
This commit fully qualifies the sles `rcsshd` command. From testing
internally it appears the command exists at `/usr/sbin` for sles 11
32/64 bit and sles 12 64 bit.
=> (BKR-1426) Fully qualify sles ssh restart cmd

lib/beaker/host_prebuilt_steps.rb
Previously, beaker didn't set the host type, e.g. aio, for network
device hosts during the `provision` subcommand, so the saved beaker
session file was missing `privatebindir` and other PATH related settings
for those hosts. The next `exec` subcommand would load the session file,
create new Host objects, and fail to find ruby during the
ruby_compiler_optimization.rb test.
This wasn't an issue prior to subcommands, because 1) puppet's pre-suite
always called `configure_type_defaults_on` after installing
puppet-agent[1], and 2) the `host['privatebindir']` settings stayed in
memory for the duration of the beaker run.
This commit ensures if `set_env` is called, then
`configure_type_defaults_on` will be too. It's important to do this
during the `provision` subcommand, as that's the last time …
=> (BKR-1429) Configure host type for all hosts

lib/beaker/subcommand.rb, spec/beaker/subcommand_spec.rb
Prior to this commit, beaker expanded out the entire file path for
beaker exec; this is unnecessary and results in including the "%"
character in the path for testing some of our internationalized
matrices.
=> (BKR-1430) Use relative paths for beaker exec

lib/beaker/subcommand.rb
Recursively glob directories when using the beaker exec subcommand.
=> (BKR-1444) Recursively glob the tests directory

lib/beaker/cli.rb, lib/beaker/subcommand.rb, spec/beaker/subcommand_spec.rb
Beaker's exec subcommand will now accept a comma-separated list of
file/directories. Each directory will be recursively globbed. All other
suites, e.g. pre-suite, will be skipped.
This commit preserves the ability to specify a comma-separated list of
suites, e.g. beaker exec pre-suite,tests. Beaker will skip any suite not
listed.  Note the tests to run must have have been specified in the
options file or specified on the command line:
beaker exec pre-suite --pre-suite step1.rb
It's kind of strange that the exec subcommand takes either a list of
testcases to execute or the names of suites to execute, because
specifying `beaker exec tests` is ambiguous. It could be "execute all of
the testcases in the tests directory", or "execute the 'tests' suite".
This commit preserves the ambiguity, but …
=> (BKR-1466) Accept comma-separated tests for exec subcommand

acceptance/tests/base/external_resources_test.rb
We've had a few jobs fail due to simple
network blips & other transient errors,
often having to do with simple curl
failures that would work on a retry. This
change adds a fibonacci backoff to our
external_resources_test.rb acceptance
test
=> (MAINT) add backoffs to external_resources_test.rb

DOCUMENTING.md, docs/concepts/testing_beaker_itself.md, docs/how_to/change_terminal_output_coloring.md, docs/how_to/debug_beaker_tests.md, docs/how_to/hosts/archlinux.md, docs/how_to/rake_tasks.md, docs/how_to/recipes.md, docs/how_to/run_in_parallel.md, docs/how_to/ssh_agent_forwarding.md, docs/how_to/ssh_connection_preference.md, docs/how_to/test_arbitrary_beaker_versions.md, docs/how_to/the_beaker_dsl.md, docs/how_to/use_hocon_helpers.md, docs/how_to/use_user_password_authentication.md, docs/how_to/write_a_beaker_test_for_a_module.md, docs/tutorials/creating_a_test_environment.md, docs/tutorials/installation.md, docs/tutorials/lets_write_a_test.md, docs/tutorials/quick_start_rake_tasks.md, docs/tutorials/subcommands.md, docs/tutorials/test_run.md, docs/tutorials/the_command_line.md
Numerous but straightforward Markdown formatting cleanup in `docs/`:
- Makes whitespace around headings and code blocks more uniform
- Unifies headings to Markdown style
- Applies language tag to code blocks, making fenced blocks where needed
- Cleans up list formatting
Split from #1513
[skip ci]
=> (BKR-1472) Tidy Markdown in Docs

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb, spec/beaker/host/unix_spec.rb
Adjusts the AIX package selection criteria: puppet-agent will use AIX
6.1 packages for both AIX 7.1 and 7.2 in puppet 6; puppet 5 maintains
existing behavior around these platforms.
=> (BKR-1007) Use AIX 6.1 packages everywhere for puppet6

CHANGELOG.md, lib/beaker/shared/host_manager.rb, spec/beaker/shared/host_manager_spec.rb
Passing `role = nil` to only_host_with_role or find_at_most_one_host_with_role is automatically invalid, since calling hosts_with_role(role = nil) returns all available hosts. So validate role before calling hosts_with_role, since that could return a single role in testing scenarios.
=>  (BKR-1105) nil is not a safe role

CHANGELOG.md, docs/concepts/glossary.md
Adds a glossary in `docs/concepts/glossary.md` for project-specific jargon which may be confusing.
Split from #1513
[skip ci]
=> (BKR-1472) Add Glossary to docs

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
The method uses to call "rpm -i" directly instead of using standardized "install_package_with_rpm"
This has been changed and package_proxy is passed, so the installation now works behind a proxy.
=> BKR-1467 - add_el_extras - use "install_package_with_rpm"

CHANGELOG.md, lib/beaker/cli.rb, spec/beaker/cli_spec.rb, spec/beaker/subcommand_spec.rb
Previously, some code paths could allow continued execution of Beaker after encountering these flags. This resulted in a not-so-dry run scenario which, at best, caused confusing error output when `beaker --version` was called and, at worst, may have led to the unintentional execution of a configured provisioning task.
=> (BKR-1168) Exit early on --version, --help, and --parse-only

lib/beaker/logger.rb, spec/beaker/logger_spec.rb
If a frozen string was passed into the logging routines, it would
fail with an exception about strings being frozen.  This change
allows frozen strings to be logged.  For example:
```
irb(main):001:0> foo = "hello there"
=> "hello there"
irb(main):002:0> foo.freeze
=> "hello there"
irb(main):003:0> foo.to_s.force_encoding('UTF-8')
RuntimeError: can't modify frozen String
from (irb):3:in `force_encoding'
from (irb):3
from /Users/jnewman/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
irb(main):004:0> foo.to_s.dup.force_encoding('UTF-8')
=> "hello there"
```
=> (maint) allow logging of frozen strings

acceptance/tests/base/host/file_test.rb, lib/beaker/host/unix/file.rb, lib/beaker/host/windows/file.rb, spec/beaker/host/unix/file_spec.rb, spec/beaker/host/windows/file_spec.rb
Adds chown and chgrp methods so that hosts can handle per-host peculiarities, e.g. Cygwin hosts must call `cygpath -u` to get UNIX/POSIX style paths to pass to chown, because Cygwin chown does not support Windows-style paths.
This helps with overall efforts to make host abstractions more platform-independent.
Needs PSWindows coverage.
=> (BKR-1499) Adds Beaker::Host#chown, #chgrp, and #ls_ld

CHANGELOG.md, acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb, acceptance/tests/base/dsl/helpers/host_helpers/rsync_to_test.rb, lib/beaker/host.rb, spec/beaker/host_spec.rb
Fixes BKR-463 as described, and includes improvement to spec mocking for rsync calls which should allow future rsync error handling improvements. Acceptance test coverage is modified to indicate fixed behavior.
=> (BKR-463) Rsync now fails with CommandFailed when destination path does not exist

acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb, acceptance/tests/base/dsl/helpers/host_helpers/rsync_to_test.rb
Before, we would have a number of tests fail where
it was caused by some connection error that if we
had run it again, it probably would not be a problem.
This change allows these calls to be made with backoffs
so that the tests will be a little slower occasionally,
but much more resilient to network issues
=> (MAINT) add rsync backoff for testing

CHANGELOG.md
The changelog entry from this PR is old:
https://github.com/puppetlabs/beaker/pull/1496
This change pulls the changelog entry from back
then into the now
[skip ci]
=> (MAINT) fix changelog entry

acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb, acceptance/tests/base/dsl/helpers/host_helpers/rsync_to_test.rb
In my previous work on this:
https://github.com/puppetlabs/beaker/pull/1546
I took care of the cases where the method returned successfully
but the issue we are seeing in CI is where exceptions are
being thrown by the Host#do_rsync_to method. These changes take
the exceptions into account, allowing them to be other cases that
end similarly to the first, where we just continue backoff
execution
=> (MAINT) handle commandfailures in rsync tests

CHANGELOG.md, lib/beaker/options/command_line_parser.rb, lib/beaker/subcommand.rb, spec/beaker/subcommand_spec.rb
Prior to this change, we were losing state that had been set up when
running our pre-suite. Unfortunately, this oversight wasn't felt because
beaker was loading these defaults automatically for every beaker
invocation. In beaker 4, that functionality was removed, and we found
that state between beaker subcommand invocations was unfortunately not
preserved. This commit adds in an optional flag `--preserve-state` that
users can pass into a `beaker exec` invocation. This will update the
beaker options file to amend the host has to include any new or updated
information. This is particularly relevant for paths like
`privatebindir` that are referenced in tests.
=> (PUP-9136) Preserve host hash from beaker exec run

lib/beaker/platform.rb
The alpine platform is common for docker containers; allowing for it
gives beaker-docker the context necessary to sideload ssh onto the
container.
=> (PUP-9212) Allow for alpine platform

CHANGELOG.md, docs/tutorials/lets_write_a_test.md, lib/beaker/options/parser.rb, spec/beaker/options/parser_spec.rb
Beaker already knows how to generate hosts on the fly using beaker-hostgenrator. The problem is that there's no way to choose the default hypervisor. This means you always specify the long form. Using an environment variable we can simplify configs.
=> Introduce BEAKER_HYPERVISOR

lib/beaker/network_manager.rb
This allows docker containers to be reused between invocations of the provision and exec beaker subcommands.
I know that docker was originally added alongside vagrant here to resolve buggy behavior (https://github.com/puppetlabs/beaker/pull/1077), but I'm not finding that it works (with beaker 4, anyway) unless I remove docker here. I've tested this with acceptance suites for puppet and the augeas_core module, and all seems well, but I'm not familiar with all use cases for this gem, so suggestions are very welcome!
=> (BKR-1547) Don't always start a new container with docker

lib/beaker/subcommand.rb, lib/beaker/subcommands/subcommand_util.rb, spec/beaker/subcommand/subcommand_util_spec.rb
Certain option keys (like :logger, for a logger object), should never be
persisted in a subcommand options yaml file. SubcommandUtil was already
removing these keys from the top level of any options hash before
persisting it, but it wasn't recursing into child values.
If a child value (like the HOSTS hash, written during provisioning)
contained a :logger entry, that entry was persisted to the options file
as a string. This string representation of the logger would subsequently
be used while trying to ssh to a host, raising an exception.
This change updates sanitize_options_for_save so that it recursively
removes unwanted keys from any configs that are about to be persisted.
=> (BKR-1549) Recursively remove unpersisted subcommand options

CHANGELOG.md
This commit updates the changelog for 4.3.0 release.
[skip ci]
=> (MAINT) update changelog for 4.3.0 release

lib/beaker/host/cisco.rb, spec/beaker/host/cisco_spec.rb
BK-1556 changes refactored the appending of strings and it was missed when the user is a root user, which caused an EOF error on some use cases, i.e. when running guestshell as a root user.
This commit adds in the root user check to only append `"` for non-root users.
=> (BK-1562) return root considerations for appending on nexus devices

lib/beaker/dsl/helpers/host_helpers.rb
These are generally useful helpers [from puppet's acceptance suite](https://github.com/puppetlabs/puppet/blob/master/acceptance/lib/puppet/acceptance/temp_file_utils.rb#L96) which don't require puppet to be installed on the SUT.
=> (BKR-1560) Add host helpers for working with files

CHANGELOG.md
This commit updates the changelog for 4.3.0 release.
[skip ci]
=> (MAINT) update changelog for 4.4.0 release

lib/beaker/host/unix/exec.rb
This mirroring is not needed since directly executed SSH commands ignore profile.d. This means it's sufficient to set ~/.ssh/environment.
The format is another issue with this function. In ~/.ssh/environment it'll be PATH=PATH:/opt/puppetlabs/bin but this breaks the PATH in an actual shell.
This only removes it on Debian because I've verified that works and I don't have any SLES-based machines nor knowledge.
=> (BKR-1559) Do not mirror profile.d on Debian

lib/beaker/host_prebuilt_steps.rb
pkgutil from Solaris 10 uses wget to retrieve the repo information. The wget version from our sparc instance is old: 1.12 from 2009. This version of wget does not support SSL CA 2.
This PR updates the wget version to the latest available, that contains support for SSL CA2.
=> (IMAGES-844) enable Solaris10Sparc pkgutil SSL CA2

lib/beaker/host/cisco.rb, spec/beaker/host/cisco_spec.rb
Other hosts have hostkey checks disabled as per the presets, but as cisco hosts tend to have custom ssh details the presets for ssh were overriden causing issues when reusing an IP from VMPooler.
Alternatively we could update the hostgenerator (https://github.com/puppetlabs/beaker-hostgenerator/blob/4f67207dab68246296f9d555d6eba01107a10aa9/lib/beaker-hostgenerator/data.rb#L235) if this is deemed only relevant to Puppet testing
=> (maint) disabling hostkey checks for cisco hosts

beaker.gemspec
Beaker is failing to run on newer systems due to https://github.com/net-ssh/net-ssh/issues/503
Updating to the latest `net-ssh` release family does not appear to demonstrate issues.
=> Provide for OpenSSL 1.1.x+ support

acceptance/pre_suite/subcommands/05_install_ruby.rb, acceptance/pre_suite/subcommands/08_install_beaker.rb
This is required for the updated byebug gem dependency. All ruby
unit tests have already been moved to ruby 2.3+, this is keeping
consistentcy.
=> (maint) Change subcommand pre-suite to install ruby 2.3.1

acceptance/tests/base/host/packages.rb
Installing zsh on windows caused the tests to fail and require a restart.
After restart, the machine would not come back online. Disabling the
tests for now until a new image for windows is available in vmpooler.
=> (MAINT) Disable package install test for windows

acceptance/fixtures/package/deb/pl-puppetserver-latest-jessie.list
Wheezy was dropped from our internal apt repo, so we moved to debian 8
for our full suite pipelines. That requires a small fixture to be in place
for certain tests.
=> (MAINT) Add debian jessie fixture for acceptance testing

lib/beaker/host/unix/file.rb, spec/beaker/host/unix/file_spec.rb
In JIRA ticket RE-1990, a bug was introduced that added the unnecessary
string "repos-pe" to repo filenames. Now that that bug has been
resolved, beaker itself no longer needs to prefix this string when
generating a repo filename.
=> (maint) remove "repos-pe" prefix

acceptance/tests/base/host/reboot_test.rb
This test has not been diagnostic of beaker-side
failures since early after the reboot functionality
was added to beaker.
Since this is the case, and testing results are
plagued by failures at the infrastructure-level,
this should be pulled from beaker itself and
debugged/verified at those levels.
=> (MAINT) remove reboot test from acceptance suite

lib/beaker/ssh_connection.rb, spec/beaker/ssh_connection_spec.rb
This commit removes the nested retry logic from the execute method. Without this change the retry logic in connect_block is duplicated in execute, creating nested retry logic, which causes beaker to take longer than expected to fail.
=> (BEAKER-1599) Execute repeats retry logic

lib/beaker/host.rb, spec/beaker/host_spec.rb
This commit adds a method that reports if FIPS mode is enabled for a
host. Currently, we only test on Redhat 7 with FIPS mode, which
indicates its state via a file. If we eventually expand support to
testing with FIPS on more operating systems, those cases and their
detection methods should be added. For now, all other platforms simply
return false.
=> (BKR-1604) Add FIPS detection method to Host

lib/beaker/host.rb, lib/beaker/shared/repetition.rb, spec/beaker/host_spec.rb
Before this change there was a slim chance that the system could go
down and back up within one tick of the fibonacci back off, especially
once you are at the higher end of the loop where it can sleep for 300+
seconds.
Introduced a new method that sleeps for x seconds, and wait for y seconds
between each loop. Set the down? method to use it with 3 minutes timeout
and 10 second interval for the check. This ensure that a node going down
will not be missed.
=> (BKR-1595) Do not use fibonacci back off

lib/beaker/host/unix/exec.rb, spec/beaker/host/unix/exec_spec.rb
This change adds the capability to configure syslog on ubuntu. Without this change we have no way via beaker to configure syslog.
=> (QENG-7466) Add capability to configure syslog

lib/beaker/hypervisor.rb, spec/beaker/hypervisor/hypervisor_spec.rb
Before this change we would sometimes hang in the prebuilt host steps
that beaker runs, and the CI system would then send a SIGTERM to stop
beaker. With this change, we want to get a stacktrace when this happens
to try and pinpoint where the issue is
=> (QENG-7466) Get stack trace for prebuild steps when aborted

lib/beaker/host.rb
fips_mode? should not fail if `/proc/sys/crypto/fips_enabled` is missing
=> (maint) fix fips_mode? detection

acceptance/pre_suite/subcommands/05_install_ruby.rb
This is required for the updated byebug gem dependency.
=> (maint) Change subcommand pre-suite to install ruby 2.4.1

Rakefile, acceptance/config/puppetpe/acceptance-options.rb, acceptance/fixtures/files/sles-11-x86_64.repo, acceptance/fixtures/files/sles-12-x86_64.repo
In reviewing #1614, I'm starting to suspect that the files @mwaggett is changing aren't being used in our system today. One of the files hadn't been updated in four years, for example.
I'm proposing this change to verify that in our CI, and suggest we get rid of our old configurations rather than worrying about keeping them up-to-date, so that Molly won't have to come through again in the future & update these files if artifactory details change.
=> (RE-13193) remove unused rake task and old RE references

README.md
also fixes references to non-existent MAINTAINERs doc
[skip ci]
=> (MAINT) add release section to README

lib/beaker/dsl/helpers/host_helpers.rb, lib/beaker/ssh_connection.rb
* Add Windows support to:
* file_exists_on
* directory_exists_on
* link_exists_on (fallback to file_exists_on)
* file_contents_on
* Expand windows environment variables on scp_from and scp_to
=> Windows support in host_helpers

beaker.gemspec
Facter 4 depends on Thor > 1.0 and some module's tests depend on Beaker which require Thor < 1.
Also Thor was released to a stable version and this is not breaking Beaker, as it was tested in: 
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/756/
=> (FACT-2392) Bump Thor dependency

lib/beaker/host.rb
Prior to this commit there was no default set for `packaging_platform`,
which would cause any host file that omitted that variable to fail.
This commit sets `packaging_platform` to the value of `platform` if it
is unset.
=> Set packaging_platform default

lib/beaker/host_prebuilt_steps.rb
the puppet-release package is now setting the url for apt puppet-agent repo to https transport. On the default Debian installation < 10 apt-transport-https is not provided causing the installation of puppet-agent to fail.
This PR adds apt-transport-https to the provisioning phase of beaker.
=> (RE-13304) add apt-transport-https to debian

lib/beaker/host/unix/exec.rb, spec/beaker/host/unix/exec_spec.rb
Prior to this commit there was no way to customize the behavior of the
Host::Unix::Exec.reboot method. This meant that if you had a host that
took a particularly long time to come back from a reboot, your tests
would fail.
This commit adds two parameters, `wait_time` and `max_connection_tries`,
which will modify how long to wait before checking on the host after
rebooting it and how many times to attempt connecting to the host after
the reboot. As noted in the method comment, the `max_connection_tries`
uses a fibbonacci backoff so increasing it will not increase the time
spent waiting for reconnection in a linear way.
Additionally, I have added specs for these parameters and mocked out
`Kernel.sleep` in the specs so that they run faster.
=> (QENG-7422) Add wait_time and max_connection_tries to exec.reboot

lib/beaker/shared/semvar.rb, spec/beaker/shared/semvar_spec.rb
The previous version of this function did not handle RC versions or post-release but not-RC-tagged versions vs. RC versions correctly (this is rare, but it crops up occasionally). This will allow us to compare dev builds to dev builds to determine which build is earlier.
=> (PE-27792) Fix version_is_less for current versioning scheme

lib/beaker/host.rb
Ensure that rsync connections use the on-disk Vagrant SSH configuraiton
if an alternate physical SSH configuration has not been specified.
Correlates directly with puppetlabs/beaker-vagrant#28
=> (BKR-1423) Pick up Vagrant config for rsync

lib/beaker/host/unix/exec.rb
In Ubuntu 20.04 openssh server was updated to `OpenSSH_8.1p1 Ubuntu-5`
and the way the environment is handled was changed: if a variable
is defined in `/etc/environment` it cannot be overwritten from
`~/.ssh/envirnment`.
With this change we empty `/etc/environment` on Ubuntu 20.04 to keep
the previous behaviour.
=> (BKR-1637) fix for Ubuntu 20.04 ssh cmd environment

acceptance/tests/base/external_resources_test.rb
Updated tests not to test EPEL5 source and added EPEL.
Starting with the 21st of April 2020, EPEL 5 was removed from the archive.
Google webcache: https://webcache.googleusercontent.com/search?q=cache:IF8cMImOVCYJ:https://archive.fedoraproject.org/pub/archive/epel/+&cd=1&hl=en&ct=clnk&gl=ro
Current:
https://archive.fedoraproject.org/pub/archive/epel/
=> (maint) Remove EPEL5 from External Resource Test

lib/beaker/host_prebuilt_steps.rb, lib/beaker/options/presets.rb, spec/beaker/host_prebuilt_steps_spec.rb
This commit removes support for adding the EPEL repos via Beaker.
This is being done because the EPEL mirrors provided by RedHat have
changed their structure significantly and we do not have time to update
Beaker's code to match.
Previously #1639 cleaned this up for the external resource test. This removes the remaining references.
=> (BKR-1651) Remove el-5 support

lib/beaker/host/unix/exec.rb, spec/beaker/host/unix/exec_spec.rb, spec/beaker/host_spec.rb
Prior to this commit single quotes were added around the `mkdir_p`
`rm_rf` and `mv` commands in `Beaker::Unix::Exec`. Refer to https://github.com/puppetlabs/beaker/commit/a60451cfa546126972f6588024552ca95c4ec9b5
These added single quotes caused interpolation of variables such as `~` for
the user HOME to stop working.
This commit removes the single quotes added to those command string in
the mentioned commit. We can consider adding double quote in the future,
although folks may be reliant on shell globbing and other features of
not having quotes so we may need to add a parameter to control the
behavior.
=> (hotfix) Remove single quotes from Unix host file ops

lib/beaker/dsl/helpers/host_helpers.rb, lib/beaker/dsl/wrappers.rb
As far as I can tell there is some problematic path mangling with cygwin configuration on vmpooler. For example a path like `C:\Windows\TEMP\install-puppet-2020-02-21_08.37.02.log` is magically turned in to `'C:\cygwin64\home\Administrator\WindowsTEMPinstall-puppet-2020-02-21_08.37.02.log'`. Base64 encoding the command appears to circumvent the conversion.
=> (maint) Encode powershell commands in file helpers

lib/beaker/host/unix/exec.rb, spec/beaker/host/unix/exec_spec.rb, spec/beaker/host_spec.rb
These are required on Windows with cygwin, directories do not get created/removed without single quotes.
Initially they were added on unix, but that failed when using `~\path` because it was not expanded correctly.
=> (FACT-2580) Added rm_rf, mkdir_p and mv for windows

beaker.gemspec
This commit relaxes the net-ssh dependency to support both the 5.x and 6.x series. This allows compatability with bolt features that rely on net-ssh 6.x. The 5 series is still supported in case other projects that use beaker are still restricted to the 5 series.
=> (maint) Add net-ssh 6.x compatability

lib/beaker/ssh_connection.rb
net-ssh 6+ uses :paranoid instead of :strict_host_key_checking
BRK-1655 #close
=> [BKR-1655] Adjust for net-ssh v6+

lib/beaker/host/unix/exec.rb, spec/beaker/host/unix/exec_spec.rb
This commit removes the now unused `uptime_int` and `parse_uptime`
methods and their respective spec tests. The only calls to these methods
were removed in #1643 c1f5e7546d2f45bf71b70600a35b380e1f31509a
=> (maint) Cleanup dead code

lib/beaker/host/pswindows/file.rb, spec/beaker/host/pswindows/file_spec.rb
These changes are needed in order to have the same output when these methods are used on different platforms. The implementation for unix is slightly different and had a different return values. 
Having the same return values for both unix and windows implementation will reduce the need to check which os you're running on when writing beaker tests.
**file_exist?** had a different output compared to the unix implementation (which returns bool). It actually returned the position of where it found the the match.
```
2.5.3 :001 > "true" =~ /true/
=> 0
2.5.3 :002 > "true" =~ /rue/
=> 1
```
**cat** had different output due to the fact that `execute` does not wrap the output in an `Response` object, but `exec` does.
=> (BKR-1656) Fixes for cat and file_exist? on PSWindows

lib/beaker/host/pswindows/exec.rb, spec/beaker/host/pswindows/exec_spec.rb, spec/beaker/host_spec.rb
Fixed a bug when creating a directory structure using poweshell on windows localhost
=> (BKR-1669) Fixed method mkdir_p for powershell localhost

lib/beaker/host/unix/exec.rb
In some cases, the initial check for the boot time appears to happen
before the system can correctly respond.
This adds the timeout check to the intial boot time check.
=> [BKR-1653] Fix boot time race condition

lib/beaker/host/unix/exec.rb
Before this change, the 'who -b' command was resilient when run before the reboot
Now making it retry too if it cannot find the /boot/ line after a reboot too.
We have seen one instance of a sles-12 machine rebooting, and the first request
for 'who -b' after the reboot failed the connection, which made the search for the line
be nil, and returning a stack trace when trying to convert that into Time with a
TypeError: no implicit conversion of nil into String. Now protects against that
and will retry as expected.
=> (maint) Improve reboot code

lib/beaker/ssh_connection.rb
* Take into account that :paranoid is deprecated
* Take into account that true/false is deprecated for :verify_host_key
=> [BRK-1655] Better strict_host_key_checking fix

CODEOWNERS
This removes Puppet teams as codeowners on the Beaker repo, since these
team references won't work once the repository is moved to the Vox
Pupuli organization. We tried to add a new clause to the CO file to
notify certain Puppet teams when `lib/beaker/version.rb` is updated but
teams cannot be referenced, and it's a security risk to add Puppet
emails to a public file. We determined that any individuals at Puppet
who want to be notified when Beaker is released can ask to be added
individually, either to a Vox organization team or individually to the
CO file, but that they should opt-in to getting notifications.
=> (maint) Remove codeowners content

.travis.yml, Rakefile, beaker.gemspec
This modifies the `:travis` rake task to run all available tests in the
Rakefile, including host generation tests and Beaker subcommand tests.
This ensures that any changes that may break Beaker host generation or
subcommands will be caught before the change is merged.
This additional bumps the required Ruby version to 2.4, since Beaker
uses the safe navigation operator `&.` which was introduced in Ruby 2.3,
and in order to use Ruby 2.3 the required pry and pry-byebug versions
that are compatible require Ruby 2.4.
It also updates the Travis ruby matrix to include the lowest supported
version - Ruby 2.4.
=> Run host generation tests in Travis

CHANGELOG.md
This updates the Changelog for the 4.27.0 release, which includes
updates to Beaker dependencies to prevent users from user version of
Ruby and pry that are not compatible with Beaker. This also adds Travis
testing and removes Jenkins testing, in preparation for transferring the
repo to Vox Pupuli
=> (maint) Prep Changelog for 4.27 release

.rspec, lib/beaker/host/unix/exec.rb, spec/beaker/host/unix/exec_spec.rb
Tries a more granular method for getting the seconds on a reboot.
Failing that, falls back to 'who -b' and sleeps for the remaining
seconds up to the next minute plus one to ensure that the reboot time
gets updated sufficiently.
Fixes #1674
=> Fix UNIX reboot check granularity

lib/beaker/host/pswindows/exec.rb, spec/beaker/host/pswindows/exec_spec.rb
If the specified path for deletion contains spaces,
the del command will fail with being unable to find
the specified path. Wrap the path around "" in order
for the path to be recognised.
This fixes https://github.com/puppetlabs/facter/pull/1992/checks
error:
```
Test Case tests/options/config_file/no_custom_facts_and_load_path.rb reported: #<Beaker::Host::CommandFailure: Host 'localhost' exited with 1 running:
del /s /q C:\Program Files\Puppet Labs\Puppet\puppet\lib\ruby\gems\2.5.0\gems\did_you_mean-1.2.0\lib\facter
Last 10 lines of output were:
```
=> (maint) wrap paths around "" on pswindows

lib/beaker/host.rb, lib/beaker/host/unix/exec.rb, spec/beaker/host/unix/exec_spec.rb
Updates the UNIX reboot method to handle systems that go back in time
after reboot.
This can happen often on virtual machines that are running on a heavily
loaded system.
The error handling had to be loosened to allow the loop to handle
whatever bizarre circumstances get thrown at it by the underlying
system.
Fixes #1674
=> Handle systems going back in time after reboot

LICENSE, beaker.gemspec
Use the full Apache-2 license text so that github recognises it and use
the proper SPDC license code in the gemspec file.
Also update the URL and email address.
=> Fix License text and SPDX code

beaker.gemspec
Prior to f70f673ec3da78a3dcb075ccda637b5a2a923fd3, it was not accepting any 1.x version. It should be safe to assume FakeFS follows semver and any 1.x version will do.
=> Loosen fakefs dependency

docs/how_to/ssh_connection_preference.md
Prior to this commit, the provided example was invalid YAML. This
commit fixes the example host file so that it is parseable.
=> (maint) update ssh_preference example

lib/beaker/host/unix/exec.rb, spec/beaker/host/unix/exec_spec.rb, spec/beaker/options/subcommand_options_parser_spec.rb
Fixed:
* Modify `which()` to do the following
* Try `type -P` first
* Fall back to `which`
* Fail if nothing is found
* Fixed the dates in the mock reboot test data
* Updated the subcommand_options_parser tests to properly isolate the
module stubs for Rspec 3.10
=> Fix the 'which' command

.github/workflows/test.yml, beaker.gemspec, lib/beaker/dsl/helpers/web_helpers.rb, spec/beaker/dsl/helpers/web_helpers_spec.rb
In Ruby 3.0 rexml is no longer bundled. This adds it as an explicit dependency.
<del>I fear this may break Ruby 2.4 but we'll see what CI says.</del>
=> Support Ruby 3.0

lib/beaker/host_prebuilt_steps.rb, spec/beaker/host_prebuilt_steps_spec.rb
The ntpdate package is no longer available starting with Fedora 34, the ntpdate binary is now provided by the ntpsec package.
Since chrony seems to be the preferred way of synchronizing time, use it on all Fedora. We tested this internally and the chrony package comes preinstalled since at least Fedora 30.
=> Use chrony instead of ntpdate on Fedora

lib/beaker/host/unix/exec.rb
Update the match in `get_ip` to match on any hypervisor matching
`vagrant`.
Fixes #1703
=> Fix vagrant matching in 'get_ip'

beaker.gemspec
beaker was pinned to 0.4.x, but the last release is 0.8.1
=> beaker-abs: allow latest releases

.github/workflows/test.yml, Gemfile, beaker.gemspec, spec/spec_helper.rb
this also updates the gemspec/spec_helper to not depend on simplecov.
Right now we need to pull in the gem on all beaker-* projects because
they load the spec_helper.rb from beaker, which loads simplecov, which
isn't an explicit dependency. This PR cleans this up and also adds
coverage reporting.
=> Implement codecov reporting

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb
The version string from Beaker::Platform was being compared to an integer. 
This was failing on fedora OS with:
```
An error occurred in a `before(:suite)` hook.
Failure/Error: host.install_local_package(package)
ArgumentError:
comparison of Beaker::Platform with 21 failed
```
Unit tests were mocking out `Beaker::Platform` and returning an integer. This commit updates the tests to return a `Beaker::Platform` object rather than a mock.
The change in test from `huawei` to `cisco_nexus` was so that the initialisation of the `Beaker::Platform` is successful, while still allowing the test case condition to be met.
=> Fix Platform version string comparison for install_local_package

lib/beaker/local_connection.rb
When running tests on localhost we don't see the output from the commands we run,
as beaker normally does, by default, on provisioned machines. 
As a fix I added logging messages.
=> (BKR-1690) Fix localhost logging

lib/beaker/host_prebuilt_steps.rb
Currently CentOS Stream 9 is being built. This changes things so EL8 and EL9 are treated the same. Both use systemd and chrony.
=> Initial EL9 support

lib/beaker/host_prebuilt_steps.rb
Both packages are required. net-tools provides netstat
=> Arch Linux: install net-tools and openssh

beaker.gemspec
Previously we had this on voxpupuli-acceptance, but it makes more sense
here. See https://github.com/voxpupuli/voxpupuli-acceptance/pull/29
=> Add ed25519 as runtime dependency 

lib/beaker/host/unix/exec.rb
These steps are all the same so there's no reason to separate them out.
=> Reduce duplication in ssh_permit_user_environment

lib/beaker/host_prebuilt_steps.rb
dnf depends on curl. By default curl-minimal is installed and running `dnf install curl` results in an error.
=> Do not install curl on EL9

.github/workflows/test.yml, Gemfile, lib/beaker/options/hosts_file_parser.rb, spec/beaker/cli_spec.rb, spec/beaker/host/unix/pkg_spec.rb, spec/beaker/options/hosts_file_parser_spec.rb, spec/beaker/platform_spec.rb
In Ruby 3.1 using trim_mode must be passed as a keyword argument or a deprecation warning is shown. However, that is only possible on Ruby 2.7 or newer.
=> Add Ruby 3.1 support

lib/beaker/host/unix/exec.rb
Clear out the environment file for ubuntu 2204 so ~/.ssh/environment can be used.
=> (maint) Remove /etc/environment file for ubuntu2204

lib/beaker/host/windows.rb, lib/beaker/host/windows/file.rb, spec/beaker/host/windows/file_spec.rb, spec/beaker/host/windows_spec.rb
Newer versions of Windows ship with Win32-OpenSSH (see https://github.com/PowerShell/openssh-portable) This PR makes it possible to detect when that implementation is used (based on the binary path of the `sshd` service) and it converts backslashes to forward slashes, such as when calling `scp_to`. This is similar to the work that was done to support BitVise and powershell (PSWindows)
=> Add support for Win32-OpenSSH

lib/beaker/host/windows/exec.rb, spec/beaker/host/windows/exec_spec.rb
Beaker executed `mkdir -p "~/.ssh"` on Windows hosts as part of the prebuilt
steps sequence. However, when using cygwin bash, the double quotes behave like
single quotes, disabling tilde expansion:
$ realpath "\~/.ssh"
/home/Administrator/\~/.ssh
So '~' was a directory containing the '.ssh' directory. This was never noticed
because all of our VM templates already have the expected ~/.ssh directory. But
if the directory doesn't exist, then later steps would fail trying to write to
~/.ssh/environment.
This commit changes beaker behavior in the case that the path starts with tilde
and does not contain a space, so it's safe to not quote the path.
See commit 54b35b7603d25f4b38d11d0173ecd489ee96cad4 which double quoted unix &
windows, which caused a regression that was fixed in …
=> Create ~/.ssh on Windows if it doesn't exist

lib/beaker/host/mac/pkg.rb
Assume PE tarballs for macOS include the architecture unless it's an older agent
version. This fixes an issue when beaker-pe tries to fetch the tarball from the
PE server.
=> macOS PE tarballs include arch now

lib/beaker/host/mac/pkg.rb, spec/beaker/host/mac_spec.rb
Commit 0008b7ffd3b0bd7891a5ddbf1bb58898b542406d incorrectly returned the old
scheme for agent version 6.28.0, since 6.18 < 7.18. It also incorrectly returned
the new scheme if the puppet_agent_version was omitted.
It now returns the new scheme for versions in the range >= 6.18 to < 7.0, and
returns the old scheme if the version is omitted.
=> Use the new scheme for agent versions >= 6.28 and < 7

beaker.gemspec, docs/how_to/debug_beaker_tests.md, lib/beaker.rb, lib/beaker/dsl/structure.rb, spec/beaker/dsl/structure_spec.rb
Ruby 3.1 bundles debug.gem which has similar capabilities. This reduces the dependencies that beaker always pulls in.
=> Drop pry dependency

lib/beaker/host/unix/pkg.rb
Before upgrading packages on Arch Linux, we need to ensure we've the latest keyring installed.
=> Arch Linux: Ensure keyring is up2date

lib/beaker/options/hosts_file_parser.rb, spec/beaker/options/data/hosts_preserved.yml, spec/beaker/options/hosts_file_parser_spec.rb
When trying to load hosts_preserved.yml, all of these classes need to be able to be loaded. We should probably serialize fewer things to this file, but in the meantime, this allows things to work. This also uses strings for the list, since not all the classes are loaded and available at the time we are declaring this array. This also allows aliases, since we are using those in the hosts_preserved.yml file.
=> Add to list of permitted classes and allow aliases

Rakefile, acceptance/fixtures/module/Rakefile, acceptance/tests/base/dsl/helpers/host_helpers/create_remote_file_test.rb, acceptance/tests/base/dsl/helpers/host_helpers/rsync_to_test.rb, acceptance/tests/base/host/packages.rb, acceptance/tests/base/host/packages_unix.rb, acceptance/tests/install/from_file.rb, lib/beaker/cli.rb, lib/beaker/command.rb, lib/beaker/dsl/helpers/host_helpers.rb, lib/beaker/dsl/helpers/web_helpers.rb, lib/beaker/dsl/structure.rb, lib/beaker/host/cisco.rb, lib/beaker/host/pswindows/pkg.rb, lib/beaker/host/unix/exec.rb, lib/beaker/host/unix/file.rb, lib/beaker/host/unix/pkg.rb, lib/beaker/host/windows.rb, lib/beaker/host/windows/pkg.rb, lib/beaker/host_prebuilt_steps.rb, lib/beaker/options/command_line_parser.rb, lib/beaker/options/parser.rb, lib/beaker/test_suite.rb
rubocop-performance recently updated to 1.16.0 and its Performance/StringInclude cop identified several instances where Beaker was matching against regex when a less-expensive `String#include?` could be used.
This commit updates those regex instances.
See also: recent GitHub Actions Rubocop failures: https://github.com/voxpupuli/beaker/actions/runs/4119323790/jobs/7112852805#logs
=> (maint) StringInclude Rubocop corrections

beaker.gemspec, lib/beaker/dsl/helpers/web_helpers.rb, spec/beaker/dsl/helpers/web_helpers_spec.rb
Prior to Ruby 2.4, the OpenURI module did not natively support HTTP => HTTPS redirections, necessitating a third-party gem, open_uri_redirections.
However, redirection functionality was added in Ruby 2.4:
https://github.com/ruby/ruby/commit/393ecc9f10016828a3713438ae216dc39b965364
And the `Kernel#open` method was deprecated in Ruby 2.7 and removed entirely in Ruby 3.0 in favor of the `URI#open` method:
https://bugs.ruby-lang.org/issues/15893
This commit removes the open_uri_redirections gem from the WebHelpers module and gemspec and replaces `Kernel#open` with `URI#open`.
=> (maint) Removes open_uri_redirections

spec/beaker/host/windows/exec_spec.rb
I'm not 100% sure this is correct, but it feels wrong to have both in there.
=> Do not include Unix::Exec on Windows::Exec tests

.github/workflows/test.yml, acceptance/tests/base/host/host_test.rb, lib/beaker/host/unix/exec.rb, lib/beaker/host/unix/pkg.rb, lib/beaker/host_prebuilt_steps.rb
This is just to see what would fail since I don't have 3.2 locally. Includes https://github.com/voxpupuli/beaker/pull/1761 for the deprecated method removal.
=> Test on Ruby 3.2

.rubocop.yml, .rubocop_todo.yml
In all other gems we've this disabled in rubocop.yml as well.
=> rubocop: disable Gemspec/DevelopmentDependencies

.github/workflows/test.yml
This provides a generic name for a CI job. It will pass when all other jobs passed. As a result, we can configure it in the GitHub branch protection (like we do it in other repos already).
=> Add a CI job we can enforce in branch protection

spec/beaker/shared/host_manager_spec.rb
The send method can be used to call private methods where normally you wouldn't be allowed to. This is useful in tests and both easier and safer than instance_eval.
=> Use send instead of instance_eval

beaker.gemspec, lib/beaker/dsl/helpers/web_helpers.rb, spec/beaker/dsl/helpers/web_helpers_spec.rb
Prior to Ruby 2.4, the OpenURI module did not natively support HTTP => HTTPS redirections, necessitating a third-party gem, open_uri_redirections.
However, redirection functionality was added in Ruby 2.4:
https://github.com/ruby/ruby/commit/393ecc9f10016828a3713438ae216dc39b965364
And the `Kernel#open` method was deprecated in Ruby 2.7 and removed entirely in Ruby 3.0 in favor of the `URI#open` method:
https://bugs.ruby-lang.org/issues/15893
This commit removes the open_uri_redirections gem from the WebHelpers module and gemspec and replaces `Kernel#open` with `URI#open`.
(cherry picked from commit 46ba6bfaf4fe39b0ef4d73648fefe09a8aa36d22)
=> (maint) Backport 'Removes open_uri_redirections'

Rakefile, beaker.gemspec
We don't use them anymore and dropped them already in other beaker plugins
=> Drop legacy yard tasks

docs/tutorials/creating_a_test_environment.md
if one does not set any role, you get an error
```bash
Failure/Error: it { is_expected.to be_installed }
Beaker::DSL::Outcomes::FailTest:
There should be one host with default defined!
```
One and only one is allowed to be default.
```
Failure/Error: configure_beaker
ArgumentError:
Only one host may have the role 'default', default roles assigned to [:"ubuntu-20-04", :"ubuntu-18-04", :"ubuntu-22-04"]
```
=> roles are not optional

.rubocop.yml
Caused by https://github.com/voxpupuli/voxpupuli-rubocop/commit/bde6dd440601d179e65956be11a2a51208c42320
=> Disable RSpec/IndexedLet

lib/beaker/host.rb, lib/beaker/host/freebsd/pkg.rb
All subclasses of Beaker::Host implement this, so this declares the API.  This is useful for consumers who want to use instance_double(Beaker::Host) and then call tmpfile.
=> Declare API interface on Beaker::Host

lib/beaker/host/aix/file.rb, lib/beaker/host/pswindows/file.rb, lib/beaker/host/unix/file.rb, lib/beaker/host/windows/file.rb
Sometimes tools expect a certain extension or it is just cleaner to have one. This adds an optional parameter which keeps the API compatible.
=> Support an extension to tmpfile

CHANGELOG.md, lib/beaker/version.rb
This assumes that https://github.com/voxpupuli/beaker/pull/1735 and https://github.com/voxpupuli/beaker/pull/1808 will be merged as well.
=> Release 5.2.0

beaker.gemspec
This is to fix the following Beaker error:
```
NotImplementedError: unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
* ed25519 (>= 1.2, < 2.0)
* bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
Gem::LoadError : "bcrypt_pbkdf is not part of the bundle. Add it to your Gemfile."
```
=> Add bcrypt_pbkdf to fix ed25519 ssh keys support

acceptance/lib/helpers/test_helper.rb, lib/beaker.rb, lib/beaker/options/command_line_parser.rb, lib/beaker/test_case.rb, spec/beaker/dsl/assertions_spec.rb, spec/beaker/dsl/structure_spec.rb, spec/beaker/host/mac/group_spec.rb, spec/beaker/host/mac/user_spec.rb
Minitest v5.19.0, released today, includes a commit[1] that only calls its compatibility layer when using an environment variable ("MT_COMPAT").
This means that calling "MiniTest" (with a capital "T") instead of "Minitest" (with all lowercase "T"s) no longer works.
This commit replaces all instances of "MiniTest" with "Minitest."
[1] https://github.com/minitest/minitest/commit/a2c6c18570f6f0a1bf6af70fe3b6d9599a13fdd6
=> (maint) Update Minitest capitalization

.rubocop_todo.yml, lib/beaker/host/unix/exec.rb, lib/beaker/host/unix/file.rb, lib/beaker/host/unix/pkg.rb, lib/beaker/host_prebuilt_steps.rb, lib/beaker/perf.rb, lib/beaker/platform.rb, spec/beaker/host/unix/file_spec.rb, spec/beaker/host/unix/pkg_spec.rb, spec/beaker/host_prebuilt_steps_spec.rb, spec/helpers.rb
Relates to:
- https://github.com/voxpupuli/beaker-hostgenerator/pull/333
- https://github.com/voxpupuli/beaker-hostgenerator/pull/335
=> Allow amazon as a platform

lib/beaker/host/unix/pkg.rb
Prior to this, Beaker used DNF for every type of Amazon Linux. However, DNF is only the default package manager for Amazon Linux >= 2023
=> Use DNF for Amazon Linux 2023

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb
Prior to this commit, the install_package and uninstall_package methods used Yum for all versions of Red Hat Enterprise Linux. However, RHEL has used DNF as its default package manager since version 8.
This commit updates those methods to use DNF for RHEL 8, 9, and any future versions and to explicitly use Yum on RHEL versions 1-7.
=> Use DNF for Fedora, newer Enterprise Linux

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb
AWS's documentation states: "In Amazon Linux 2 and Amazon Linux, the default software package management tool is YUM. In Amazon Linux 2023, the default software package management tool is DNF."[1]
This commit updates the install_package and uninstall_package methods to leverage DNF instead of Yum for Amazon Linux 2023 specifically (not Amazon Linux or Amazon Linux 2).
[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/find-install-software.html
=> (maint) Use DNF as Amazon Linux 2023 package manager

lib/beaker/options/hosts_file_parser.rb
This commit adds the PlatformTagContainer class to the HostsFileParser module so that tests can be re-run. This class was added to the 5.x series in a previous commit [1] but was not added to the 4.x branch. For context see issue #1753 
[1]: 45f0bf93577b744bda6843b372e0f3c8319fc5f5
[2]: https://github.com/voxpupuli/beaker/issues/1753
=> (maint) permit PlatformTagContainer class

lib/beaker/host_prebuilt_steps.rb
DNF depends on curl or curl-minimal. It's not needed to explicitly install this. This simplifies things.
=> Do not attempt to install curl on DNF-based distros

lib/beaker/host/unix/file.rb, spec/beaker/host/unix/file_spec.rb
Added 'amazon' support in #repo_filename method in lib/beaker/host/unix/file.rb.
=> PE-37978: Add 'amazon' to #repo-filename method

lib/beaker/host/unix/file.rb, spec/beaker/host/unix/file_spec.rb
Added 'amazon' support in #repo_filename method in lib/beaker/host/unix/file.rb.
This PR is raised by cherry-picking [commit](https://github.com/voxpupuli/beaker/commit/c8e03a21521a617bc6353822f08650ef70e9c85b) from master
=> PE-37978: Add 'amazon' to repo_filename method

lib/beaker/host.rb
Even though this doesn't implement it, it's still good to use the same signature consistently.
Fixes: 37dd194f11eda4e39dd8e3d5f3cde5014e7e42e5 ("Support an extension to tmpfile")
=> Add extension parameter to parent tmpfile method signature

lib/beaker/host/unix/exec.rb, lib/beaker/host/unix/file.rb, lib/beaker/host/unix/pkg.rb, lib/beaker/platform.rb, spec/beaker/host/unix/pkg_spec.rb, spec/helpers.rb
This isn't a supported platform anymore by puppet.
=> Drop EoL huaweios support

.rspec
When this option is set, rspec will stop after the first failure. We don't have this enabled in any other project and I think it's useful to know if you've 20 errors or just one. And the CI runtime isn't that long, so IMO it's fine.
=> .rspec: dont run with --fail-fast

.rubocop.yml, acceptance/fixtures/module/spec/acceptance/demo_spec.rb
I would like to clean up our .rubocop.yaml to follow our standards. I think enabling this cop makes sense, except for the `determine_if_x86_64` method. rubocop prefers `determine_if_x8664` but since `x86_64` is it's own name I disable the cop for this function.
=> Rubocop: Enable Naming/VariableNumber

.rubocop.yml
The cop provides some benefits, but also wants that method args have three chars or more. We use one char a lot, but we can configure this.
=> rubocop: Enable Naming/MethodParameterName

lib/beaker/host/unix/exec.rb
This is a followup of 3fb9a1bd857d21995d15d6cf876ce5c64fda0bb0
=> non-systemd SLES: Readd support for restarting sshd via `rcsshd`

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb
This commit adds logic for Amazon Linux 2 to Beaker's install_ and uninstall_package methods. (Note: AL2 is referred to in Vanagon and ABS as Amazon Linux 7, in reference to the assumed compatibility with Red Hat Enterprise Linux 7.)
=> Add package logic for Amazon Linux 2

lib/beaker/host/unix/pkg.rb, spec/beaker/host/unix/pkg_spec.rb, spec/helpers.rb
Copies Amazon 7 to 2, as the former is an implementation detail and the latter is the actual OS version: https://aws.amazon.com/amazon-linux-2
I was able to run facter beaker tests with this PR and https://github.com/voxpupuli/beaker-hostgenerator/pull/372
```
❯ env | grep BEAKER                                                                                     
BEAKER_VERSION=https://github.com/voxpupuli/beaker#amazon2
BEAKER_PUPPET_VERSION=~> 4.0
BEAKER_HOSTGENERATOR_VERSION=https://github.com/voxpupuli/beaker-hostgenerator#amazon2
❯ cd ~/work/facter/acceptance
❯ bundle update
❯ env SHA=c6c5de5b1457d0cad36bcbb0ee94ec3c3486014d HOSTS=amazon2-AARCH64a bundle exec rake ci:test:setup
...
❯ bundle exec beaker exec tests
... SNIP...
- Host Configuration Summary -
- Test Case Summary for …
```
=> Add Amazon 2

lib/beaker/host_prebuilt_steps.rb
Beaker assumes that the ping binary exists. in EL8 and EL9 that's provided by iputils.
cherry-picked from #1891
=> EL8/9 & Fedora: Install iputils

lib/beaker/host/unix/pkg.rb, lib/beaker/host_prebuilt_steps.rb, spec/beaker/host/unix/pkg_spec.rb, spec/beaker/host_prebuilt_steps_spec.rb
This replaces the old `apt-get update` with the newer `apt update`. This works on all modern Debian versions we support. Also `-qq` was added, to only output errors. This makes the beaker run a bit more readable.
=> Debian: Replace apt-get with apt for updates

lib/beaker/host/unix/pkg.rb
This will ensure we've a local keyring available. That's a requirement to instal and import keys. According to
https://gitlab.archlinux.org/archlinux/archlinux-docker#principles, the container images don't ship a local keyring by default.
=> Arch Linux: Generate keyring before installing packages

spec/beaker/command_spec.rb, spec/beaker/host/windows/file_spec.rb, spec/beaker/host_prebuilt_steps_spec.rb, spec/beaker/host_spec.rb, spec/beaker/hypervisor/hypervisor_spec.rb, spec/beaker/perf_spec.rb, spec/beaker/shared/host_manager_spec.rb, spec/helpers.rb
The regular option parser guarantees this and it sort of works because Beaker::Platform can behave as a string (since it inherits from it).  When you do want to use extended features, it fails.
This enhances the helper to guarantee it's the correct class instance. Then there are many changes to the tests to ensure a valid platform is passed in.
<del>Still incomplete and I wonder what we should do about the unix platform.</del>
<del>I'm also tempted to drop some platforms instead.</del>
=> Ensure platform is Beaker::Platform in tests

spec/beaker/host_prebuilt_steps_spec.rb
The stdout accessor should really be removed. The tests that needed it are enhanced to properly mock out the real implementations and return the information in a more precise way.
It also removes the common hosts in favor of explicit host definitions.
=> Avoid mocking stdout on host and use explicit hosts in host_prebuilt_steps_spec.rb

lib/beaker/platform.rb, spec/beaker/host_prebuilt_steps_spec.rb
`curl-minimal` was mistakenly added in commit 18e6e2292aeed5557c6a85e45ba86365ca43d6f6. Attempting to install it on EL 8 and newer causes errors because there is no such package.
`curl` is installed by default. See
https://fedoraproject.org/wiki/Changes/CurlMinimal_as_Default and #1854,
for example.
=> platform: don't install `curl-minimal` on EL family

lib/beaker/host/windows/group.rb, lib/beaker/host/windows/user.rb, spec/beaker/host/windows/group_spec.rb, spec/beaker/host/windows/user_spec.rb
With this PR trying to use powershell commands for `group_list` and `user_list` methods for windows as wmic is deprecated with windows 2025.
=> Changes to add powershell commands as wmic is deprecated in windows 2025

.rubocop_todo.yml, lib/beaker/host/mac/pkg.rb, spec/beaker/host/mac/pkg_spec.rb
The current macOS package installation code assumes that
* **(1)** the `name` input to `Mac::Pkg.install_package(name,...)` will be a filename without an extension
* **(2)** the `*.pkg` file inside a DMG will have the same base name as the DMG itself.
**(1)** caused failures in our CI because the subsequent code was mismatching some of the extensions so making the code look for a non-existent file/directory.
**(2)** caused failures because some of our DMGs do not have a `*pkg` name with the same basename as the `*.dmg`
For example:
```bash
utter-suzerain:~ root# hdiutil attach puppet-bolt-4.0.0-1.osx14.dmg 
Checksumming Protective Master Boot Record (MBR : 0)…
...
...
utter-suzerain:~ root#     
utter-suzerain:~ root# ls /Volumes/puppet-bolt-4.0.0-1.osx14/ …
```
=> Fix macOS package installation when DMG content differs from filename

beaker.gemspec
1.2.6 is broken. It introduced some frozen strings and docker-api isn't compatible with that. We need to pin to 1.2.5 until either of those gems are fixed.
=> pin excon to 1.2.5

beaker.gemspec
This reverts commit 12690002bd9ff47b600232ae035e4e80b03b2c4c.
not required anymore, upstream released a fixed version.
=> Revert "pin excon to 1.2.5"
